commands = [
'Accept Inline Completion',
'Accept Inline Edit',
'Accept Inline Suggestion',
'Accept Next Word Of Inline Suggestion',
'Accessible Diff Viewer: Go to Next Difference',
'Accessible Diff Viewer: Go to Previous Difference',
'Add Cursor Above',
'Add Cursor Below',
'Add Cursors to Line Ends',
'Add Line Comment',
'Add Selection To Next Find Match',
'Auto Fix...',
'C/C: Switch Header/Source',
'Calls: Show Call Hierarchy',
'Cancel Selection Anchor',
'Change All Occurrences',
'Change Language Mode',
'Chat: Insert at Cursor',
'Chat: Insert into Terminal',
'Chat: New Chat',
'Chat: Next Code Block',
'Chat: Next File Tree',
'Chat: Previous Code Block',
'Chat: Previous File Tree',
'Chat: Start Voice Chat',
'Chat: Stop Listening',
'Chat: Stop Listening and Submit',
'Close Exception Widget',
'Close Window',
'Comments: Add Comment on Current Selection',
'Comments: Go to Next Commenting Range',
'Comments: Go to Previous Commenting Range',
'Copy',
'Copy Line Down',
'Copy Line Up',
'Create Folding Range from Selection',
'Create: New File...',
'Cursor Undo',
'Cut',
'Debug: Continue',
'Debug: Disconnect',
'Debug: Focus Next Debug Console',
'Debug: Focus Previous Debug Console',
'Debug: Inline Breakpoint',
'Debug: Pause',
'Debug: Restart',
'Debug: Show Hover',
'Debug: Start Debugging',
'Debug: Start Debugging and Stop on Entry',
'Debug: Start Without Debugging',
'Debug: Step Into',
'Debug: Step Into Target',
'Debug: Step Out',
'Debug: Step Over',
'Debug: Stop',
'Define Keybinding',
'Delete Line',
'Detect Language from Content',
'Developer: Reload Window',
'Developer: Toggle Developer Tools',
'Disable Accessible View Hint',
'Emmet: Expand Abbreviation',
'Expand Line Selection',
'Expand Selection',
'Explorer: Focus on Open Editors View',
'File: Compare Active File with Clipboard',
'File: Compare Active File with Saved',
'File: Copy Path of Active File',
'File: Copy Relative Path of Active File',
'File: New Untitled Text File',
'File: Open File...',
'File: Open Folder...',
'File: Open Recent...',
'File: Open...',
'File: Reveal in File Explorer',
'File: Save',
'File: Save As...',
'File: Save without Formatting',
'File: Show All Editors By Appearance',
'Find',
'Find Next',
'Find Next Selection',
'Find Previous',
'Find Previous Selection',
'Focus and Select Breadcrumbs',
'Focus Breadcrumbs',
'Fold',
'Fold All',
'Fold All Block Comments',
'Fold All Except Selected',
'Fold All Regions',
'Fold Level 1',
'Fold Level 2',
'Fold Level 3',
'Fold Level 4',
'Fold Level 5',
'Fold Level 6',
'Fold Level 7',
'Fold Recursively',
'Format Cell',
'Format Document',
'Format Selection',
'Generate Docstring',
'Git: Revert Selected Ranges',
'Git: Stage Selected Ranges',
'Git: Unstage Selected Ranges',
'Go Back',
'Go Forward',
'Go To Bottom Hover',
'Go to Bracket',
'Go to Definition',
'Go to File...',
'Go to Implementations',
'Go to Last Edit Location',
'Go to Line/Column...',
'Go to Next Change',
'Go to Next Problem (Error, Warning, Info)',
'Go to Next Problem in Files (Error, Warning, Info)',
'Go to Next Reference',
'Go to Next Symbol Highlight',
'Go to Previous Change',
'Go to Previous Problem (Error, Warning, Info)',
'Go to Previous Problem in Files (Error, Warning, Info)',
'Go to Previous Reference',
'Go to Previous Symbol Highlight',
'Go to References',
'Go To Symbol in Accessible View',
'Go to Symbol in Editor...',
'Go to Symbol in Workspace...',
'Go To Top Hover',
'Help: Keyboard Shortcuts Reference',
'Hide Inline Suggestion',
'Hide the Color Picker',
'Indent Line',
'Inline Chat: Accept Changes',
'Inline Chat: Focus Input',
'Inline Chat: Move to Next Change',
'Inline Chat: Move to Previous Change',
'Inline Chat: Start Inline Chat',
'Inline Chat: Start Inline Voice Chat',
'Inline Chat: Stop Inline Voice Chat',
'Insert Color with Standalone Color Picker',
'Insert Line Above',
'Insert Line Below',
'Java: Copy Path',
'Java: Copy Relative Path',
'Java: Delete',
'Java: Delete Permanently',
'Java: Force Java Compilation',
'Java: Help Center',
'Java: Paste Clipboard Text Into a File',
'Java: Performs Cleanup Actions',
'Java: Reload Projects',
'Java: Rename',
'Java: Reveal in Explorer',
'Jump Back from Inline Edit',
'Jump to Inline Edit',
'Markdown: Open Preview',
'Markdown: Open Preview to the Side',
'Move Last Selection To Next Find Match',
'Move Line Down',
'Move Line Up',
'New Window',
'newline and auto indent',
'Notebook: Accept Changes',
'Notebook: Accept Detected Language for Cell',
'Notebook: Cell Cursor Page Down',
'Notebook: Cell Cursor Page Down Select',
'Notebook: Cell Cursor Page Up',
'Notebook: Cell Cursor Page Up Select',
'Notebook: Center Active Cell',
'Notebook: Change Cell to Code',
'Notebook: Change Cell to Markdown',
'Notebook: Clear Cell Outputs',
'Notebook: Collapse Cell Input',
'Notebook: Collapse Cell Output',
'Notebook: Copy Cell Down',
'Notebook: Copy Cell Up',
'Notebook: Cursor Down',
'Notebook: Cursor Up',
'Notebook: Delete Cell',
'Notebook: Discard',
'Notebook: Edit Cell',
'Notebook: Execute Cell',
'Notebook: Execute Notebook Cell and Insert Below',
'Notebook: Execute Notebook Cell and Select Below',
'Notebook: Expand Cell Input',
'Notebook: Expand Cell Output',
'Notebook: Focus Chat',
'Notebook: Focus Chat Widget',
'Notebook: Focus First Cell',
'Notebook: Focus In Active Cell Output',
'Notebook: Focus Last Cell',
'Notebook: Focus Next Cell',
'Notebook: Focus Next Cell Chat Widget',
'Notebook: Focus Next Cell Editor',
'Notebook: Focus Out Active Cell Output',
'Notebook: Focus Previous Cell',
'Notebook: Focus Previous Cell Editor',
'Notebook: Fold Cell',
'Notebook: Format Notebook',
'Notebook: Insert Code Cell Above',
'Notebook: Insert Code Cell Below',
'Notebook: Join With Next Cell',
'Notebook: Join With Previous Cell',
'Notebook: Make Request',
'Notebook: Move Cell Down',
'Notebook: Move Cell Up',
'Notebook: Paste Cell Above',
'Notebook: Split Cell',
'Notebook: Stop Editing Cell',
'Notebook: Toggle Scroll Cell Output',
'Notebook: Unfold Cell',
'Notifications: Accept Notification Primary Action',
'Notifications: Hide Notifications',
'Notifications: Show Notifications',
'Open Accessibility Help',
'Open Accessible View',
'Open Definition to the Side',
'Open New External Terminal',
'Organize Imports',
'Outdent Line',
'Page Down Hover',
'Page Up Hover',
'Paste',
'Peek Call Hierarchy',
'Peek Definition',
'Peek Implementations',
'Preferences: Clear Settings Search Results',
'Preferences: Color Theme',
'Preferences: Focus Settings Search',
'Preferences: Focus Settings Table of Contents',
'Preferences: Move Focus Up One Level',
'Preferences: Open Keyboard Shortcuts',
'Preferences: Show Setting Context Menu',
'Python: Refresh TensorBoard',
'Python: Run Selection/Line in Python Terminal',
'Quick Fix...',
'Redo',
'Refactor...',
'References: Find All References',
'Reject Inline Edit',
'Remote: Show Remote Menu',
'Remove Brackets',
'Remove Line Comment',
'Remove Manual Folding Ranges',
'Rename Symbol',
'REPL Accept Input',
'REPL Focus Content to Filter',
'Replace',
'Replace with Next Value',
'Replace with Previous Value',
'Scroll Down Hover',
'Scroll Left Hover',
'Scroll Right Hover',
'Scroll Up Hover',
'Search Editor: Decrease Context Lines',
'Search Editor: Delete File Results',
'Search Editor: Focus Search Editor Input',
'Search Editor: Increase Context Lines',
'Search Editor: Open Results in Editor',
'Search Editor: Search Again',
'Search Editor: Select All Matches',
'Search Editor: Toggle Context Lines',
'Search Editor: Toggle Match Case',
'Search Editor: Toggle Match Whole Word',
'Search Editor: Toggle Use Regular Expression',
'Search: Cancel Search',
'Search: Find in Files',
'Search: Focus Next Search Result',
'Search: Focus Previous Search Result',
'Search: Replace in Files',
'Select All',
'Select All Occurrences of Find Match',
'Select from Anchor to Cursor',
'Set Selection Anchor',
'Show All Commands',
'Show Editor Context Menu',
'Show Next Change',
'Show Next in Accessible View',
'Show Next Inline Suggestion',
'Show or Focus Hover',
'Show Previous Change',
'Show Previous in Accessible View',
'Show Previous Inline Suggestion',
'Shrink Selection',
'Start Linked Editing',
'Stop Inlay Hints Reading',
'Tasks: Run Build Task',
'Terminal: Accessible Buffer Go to Next Command',
'Terminal: Accessible Buffer Go to Previous Command',
'Terminal: Clear Selection',
'Terminal: Copy and Clear Selection',
'Terminal: Copy Selection',
'Terminal: Create New Terminal',
'Terminal: Find Next',
'Terminal: Find Previous',
'Terminal: Focus Find',
'Terminal: Focus Hover',
'Terminal: Focus Next Terminal Group',
'Terminal: Focus Next Terminal in Terminal Group',
'Terminal: Focus Previous Terminal Group',
'Terminal: Focus Previous Terminal in Terminal Group',
'Terminal: Focus Terminal',
'Terminal: Focus Terminal Tabs View',
'Terminal: Go to Recent Directory...',
'Terminal: Hide Find',
'Terminal: Kill the Active Terminal in Editor Area',
'Terminal: Open Detected Link...',
'Terminal: Paste into Active Terminal',
'Terminal: Run Recent Command...',
'Terminal: Scroll Down (Line)',
'Terminal: Scroll Down (Page)',
'Terminal: Scroll to Accessible View Bottom',
'Terminal: Scroll to Accessible View Top',
'Terminal: Scroll to Bottom',
'Terminal: Scroll To Next Command',
'Terminal: Scroll To Previous Command',
'Terminal: Scroll to Top',
'Terminal: Scroll Up (Line)',
'Terminal: Scroll Up (Page)',
'Terminal: Search Workspace',
'Terminal: Select To Next Command',
'Terminal: Select To Previous Command',
'Terminal: Show Terminal Quick Fixes',
'Terminal: Split Terminal',
'Terminal: Toggle Find Using Case Sensitive',
'Terminal: Toggle Find Using Regex',
'Terminal: Toggle Find Using Whole Word',
'Terminal: Toggle Size to Content Width',
'Test: Debug All Tests',
'Test: Debug Failed Tests',
'Test: Debug Last Run',
'Test: Debug Test at Cursor',
'Test: Debug Tests in Current File',
'Test: Go to Next Test Failure',
'Test: Go to Previous Test Failure',
'Test: Peek Output',
'Test: Refresh Tests',
'Test: Rerun Failed Tests',
'Test: Rerun Last Run',
'Test: Rerun Last Run with Coverage',
'Test: Run All Tests',
'Test: Run All Tests with Coverage',
'Test: Run Test at Cursor',
'Test: Run Test at Cursor with Coverage',
'Test: Run Tests in Current File',
'Test: Run Tests with Coverage in Current File',
'Test: Show Output',
'Test: Toggle Inline Test Output',
'Test: Toggle Test History in Peek',
'Toggle Block Comment',
'Toggle Fold',
'Toggle Line Comment',
'Toggle Screen Reader Accessibility Mode',
'Toggle Tab Key Moves Focus',
'Toggle Vertical/Horizontal Editor Layout',
'Trigger Inline Edit',
'Trigger Parameter Hints',
'Trigger Suggest',
'Trim Trailing Whitespace',
'Undo',
'Unfold',
'Unfold All',
'Unfold All Except Selected',
'Unfold All Regions',
'Unfold Recursively',
'View: Close All Editor Groups',
'View: Close All Editors',
'View: Close All Editors in Group',
'View: Close Editor',
'View: Close Saved Editors in Group',
'View: Copy Editor into New Window',
'View: Focus Editor Group Above',
'View: Focus Editor Group Below',
'View: Focus First Editor Group',
'View: Focus into Primary Side Bar',
'View: Focus Left Editor Group',
'View: Focus Next Part',
'View: Focus Previous Part',
'View: Focus Right Editor Group',
'View: Join Editor in Group',
'View: Keep Editor',
'View: Move Editor Group Down',
'View: Move Editor Group Left',
'View: Move Editor Group Right',
'View: Move Editor Group Up',
'View: Move Editor into First Group',
'View: Move Editor into Last Group',
'View: Move Editor into Next Group',
'View: Move Editor into Previous Group',
'View: Move Editor Left',
'View: Move Editor Right',
'View: Open Last Editor in Group',
'View: Open Next Editor',
'View: Open Next Editor in Group',
'View: Open Previous Editor',
'View: Open Previous Editor in Group',
'View: Pin Editor',
'View: Quick Open Least Recently Used Editor in Group',
'View: Quick Open Previous Recently Used Editor in Group',
'View: Reopen Closed Editor',
'View: Reset Zoom',
'View: Show Explorer',
'View: Show Extensions',
'View: Show Run and Debug',
'View: Show Search',
'View: Show Source Control',
'View: Split Editor',
'View: Split Editor Down',
'View: Split Editor in Group',
'View: Split Editor Left',
'View: Split Editor Orthogonal',
'View: Split Editor Right',
'View: Split Editor Up',
'View: Toggle Debug Console',
'View: Toggle Full Screen',
'View: Toggle Maximize Editor Group',
'View: Toggle Output',
'View: Toggle Panel Visibility',
'View: Toggle Primary Side Bar Visibility',
'View: Toggle Problems',
'View: Toggle Secondary Side Bar Visibility',
'View: Toggle Terminal',
'View: Toggle Word Wrap',
'View: Toggle Zen Mode',
'View: Unpin Editor',
'View: Zoom In',
'View: Zoom Out',
'Voice: Start Dictation in Editor',
'Voice: Stop Dictation in Editor',
'Welcome: Go Back',
'Workspaces: Close Workspace',
'Accept Next Line Of Inline Suggestion',
'Add Cursors To Bottom',
'Add Cursors To Top',
'Add example voice-assistant.json',
'Add Function Breakpoint',
'Add Selection To Previous Find Match',
'Add XHR/fetch Breakpoint',
'Auto Expand Lazy Variables',
'C/C: Add Debug Configuration',
'C/C: Add SSH target',
'C/C: Change Configuration Provider...',
'C/C: Clear All Code Analysis Problems',
'C/C: Connect to this SSH target in a new terminal',
'C/C: Copy vcpkg install command to clipboard',
'C/C: Create Declaration / Definition',
'C/C: Debug C/C File',
'C/C: Disable Error Squiggles',
'C/C: Edit Configurations (JSON)',
'C/C: Edit Configurations (UI)',
'C/C: Enable Error Squiggles',
'C/C: Generate Doxygen Comment',
'C/C: Generate EditorConfig contents from VC Format settings',
'C/C: Get the active SSH target',
'C/C: Go to next preprocessor directive in conditional group',
'C/C: Go to previous preprocessor directive in conditional group',
'C/C: Group by Reference Type',
'C/C: Install a C Compiler',
'C/C: Log Diagnostics',
'C/C: Refresh',
'C/C: Remove SSH target',
'C/C: Rescan for Compilers',
'C/C: Rescan Workspace',
'C/C: Reset IntelliSense Database',
'C/C: Restart IntelliSense for Active File',
'C/C: Run C/C File',
'C/C: Run Code Analysis on Active File',
'C/C: Run Code Analysis on All Files',
'C/C: Run Code Analysis on Open Files',
'C/C: Select a Configuration...',
'C/C: Select an active SSH target',
'C/C: Select IntelliSense Configuration...',
'C/C: Select SSH target',
'C/C: Set this SSH target as the active target',
'C/C: Take Survey',
'C/C: Toggle Inactive Region Colorization',
'C/C: Toggle IntelliSense Engine Fallback on Include Errors',
'C/C: Ungroup by Reference Type',
'C/C: Visit the vcpkg help page',
'Calls: Show Incoming Calls',
'Calls: Show Outgoing Calls',
'Change End of Line Sequence',
'Change File Encoding',
'Change Tab Display Size',
'Chat: Clear All Workspace Chats',
'Chat: Clear Input History',
'Chat: Export Session...',
'Chat: Import Session...',
'Chat: Inline Voice Chat',
'Chat: Insert into New File',
'Chat: Open Chat in Editor',
'Chat: Open Chat in New Window',
'Chat: Open Chat in Side Bar',
'Chat: Quick Voice Chat',
'Chat: Voice Chat in View',
'Clean Invalid Image Attachment Reference',
'Clean Workspace',
'Clear Command History',
'Clear Console',
'Clear Display Language Preference',
'Clear Editor History',
'Clear Profile Code Lenses',
'Cloud Changes: Focus on Cloud Changes View',
'Cloud Changes: Resume Latest Changes from Cloud',
'Cloud Changes: Show Cloud Changes',
'Cloud Changes: Store Working Changes in Cloud',
'Cloud Changes: Turn off Cloud Changes...',
'Cloud Changes: Turn on Cloud Changes...',
'Code: Check for Updates...',
'Code: Download Update',
'Code: Install Update',
'Code: Restart to Update',
'Code: Show Release Notes',
'Collapse All Diffs',
'Collapse Folders in Explorer',
'Comments: Collapse All Comments',
'Comments: Expand All Comments',
'Comments: Expand Unresolved Comments',
'Comments: Toggle Editor Commenting',
'Compare: Swap Left and Right Editor Side',
'Compare: Toggle Inline View',
'Configure Display Language',
'Configure Recommended Extensions (Workspace Folder)',
'Connect in Current Window...',
'Connect in New Window...',
'Connect using Distro in Current Window...',
'Connect using Distro in New Window...',
'Continue All',
'Continue Others',
'Convert Indentation to Spaces',
'Convert Indentation to Tabs',
'Copy All',
'Copy Forwarded Port Address',
'Copy Path',
'Copy vscode.dev Link',
'Copy With Syntax Highlighting',
'Create Environment',
'Create: New Jupyter Notebook',
'Cursor Redo',
'Customize Layout...',
'Debug',
'Debug Console: Focus on Debug Console View',
'Debug Java',
'Debug: Add Conditional Breakpoint...',
'Debug: Add Configuration...',
'Debug: Add Logpoint...',
'Debug: Add to Watch',
'Debug: Add Triggered Breakpoint...',
'Debug: Attach to Node Process',
'Debug: Console Copy All',
'Debug: Debug npm Script',
'Debug: Diagnose Breakpoint Problems',
'Debug: Disconnect and Suspend',
'Debug: Edit Breakpoint',
'Debug: Evaluate in Debug Console',
'Debug: Exclude Caller',
'Debug: Focus on Debug Console View',
'Debug: Focus Tab',
'Debug: Go to Next Breakpoint',
'Debug: Go to Previous Breakpoint',
'Debug: JavaScript Debug Terminal',
'Debug: Navigate Down Call Stack',
'Debug: Navigate to Bottom of Call Stack',
'Debug: Navigate to Top of Call Stack',
'Debug: Navigate Up Call Stack',
'Debug: Open Browser Devtools',
'Debug: Open Link',
'Debug: Open Loaded Script...',
'Debug: Pretty print for debugging',
'Debug: Run to Cursor',
'Debug: Save Diagnostic JS Debug Logs',
'Debug: Select and Start Debugging',
'Debug: Select Debug Console',
'Debug: Select Debug Session',
'Debug: Set Next Statement',
'Debug: Stop Performance Profile',
'Debug: Take Performance Profile',
'Debug: Terminate Thread',
'Debug: Toggle Auto Attach',
'Debug: Toggle Skipping this File',
'Decrease Current View Size',
'Decrease Editor Font Size',
'Decrease Editor Height',
'Decrease Editor Width',
'Delete All Left',
'Delete All Right',
'Delete Duplicate Lines',
'Delete Environment',
'Delete Word',
'Detect Indentation from Content',
'Developer: Cleanup Profiles',
'Developer: Clear Notebook Editor Type Cache',
'Developer: Clear Notebook Kernels MRU Cache',
'Developer: Connection: Pause socket writing',
'Developer: Connection: Trigger Reconnect',
'Developer: Download Settings Sync Activity',
'Developer: Force Retokenize',
'Developer: Generate Color Theme From Current Settings',
'Developer: Inspect Context Keys',
'Developer: Inspect Editor Tokens and Scopes',
'Developer: Inspect Key Mappings',
'Developer: Inspect Key Mappings (JSON)',
'Developer: Inspect Notebook Layout',
'Developer: Install Extension from Location...',
'Developer: Log Storage Database Contents',
'Developer: Log Working Copies',
'Developer: Measure Extension Host Latency',
'Developer: Open Current File as Release Notes',
'Developer: Open Extension Logs Folder',
'Developer: Open Log File...',
'Developer: Open Logs Folder',
'Developer: Open Process Explorer',
'Developer: Open URL',
'Developer: Open User Data Folder',
'Developer: Open Webview Developer Tools',
'Developer: Print Emitter Profiles',
'Developer: Print Service Cycles',
'Developer: Print Service Traces',
'Developer: Reinstall Extension...',
'Developer: Reload Webviews',
'Developer: Reload With Extensions Disabled',
'Developer: Remove Large Storage Database Entries...',
'Developer: Reset notebook getting started',
'Developer: Reset Welcome Page Walkthrough Progress',
'Developer: Reset Workspace Profiles Associations',
'Developer: Restart Extension Host',
'Developer: Restart Pty Host',
'Developer: Resume Changes from Serialized Data',
'Developer: Set Log Level...',
'Developer: Show Logs...',
'Developer: Show Running Extensions',
'Developer: Show Terminal Texture Atlas',
'Developer: Show Window Log',
'Developer: Start Text Mate Syntax Grammar Logging',
'Developer: Startup Performance',
'Developer: Stop Tracing',
'Developer: Toggle Keyboard Shortcuts Troubleshooting',
'Developer: Toggle Layout Troubleshoot',
'Developer: Toggle Notebook Clipboard Troubleshooting',
'Developer: Toggle Screencast Mode',
'Developer: Write Data to Terminal',
'Diff Editor: Collapse All Unchanged Regions',
'Diff Editor: Show All Unchanged Regions',
'Diff Editor: Switch Side',
"Disable 'toString()' Object View",
'Disable All Breakpoints',
'Disable highlighting of ambiguous characters',
'Disable highlighting of invisible characters',
'Disable highlighting of non basic ASCII characters',
'Disable Logical Structure View',
'Disable Source Mapped Stepping',
'Dismiss',
'Download and setup Python',
'Download Visual Studio Code',
'Duplicate Selection',
'Edit Profile...',
'Edit XHR/fetch Breakpoint',
'Emmet: Balance (inward)',
'Emmet: Balance (outward)',
'Emmet: Decrement by 0.1',
'Emmet: Decrement by 1',
'Emmet: Decrement by 10',
'Emmet: Evaluate Math Expression',
'Emmet: Go to Matching Pair',
'Emmet: Go to Next Edit Point',
'Emmet: Go to Previous Edit Point',
'Emmet: Increment by 0.1',
'Emmet: Increment by 1',
'Emmet: Increment by 10',
'Emmet: Merge Lines',
'Emmet: Reflect CSS Value',
'Emmet: Remove Tag',
'Emmet: Select Next Item',
'Emmet: Select Previous Item',
'Emmet: Split/Join Tag',
'Emmet: Toggle Comment',
'Emmet: Update Image Size',
'Emmet: Update Tag',
'Emmet: Wrap with Abbreviation',
"Enable 'toString()' Object View",
'Enable All Breakpoints',
'ESLint: Create ESLint configuration',
'ESLint: Fix all auto-fixable Problems',
'ESLint: Migrate Settings',
'ESLint: Restart ESLint Server',
'ESLint: Show Output Channel',
'Expand All Diffs',
'Explorer: Focus on Java Projects View',
'Explorer: Focus on Maven View',
'Explorer: Focus on No Folder Opened View',
'Explorer: Focus on NPM Scripts View',
'Explorer: Focus on Outline View',
'Explorer: Focus on Timeline View',
'Export Environment',
'Extensions: Add Extension to Workspace Folder Ignored Recommendations',
'Extensions: Add Extension to Workspace Folder Recommendations',
'Extensions: Add Extension to Workspace Ignored Recommendations',
'Extensions: Add Extension to Workspace Recommendations',
'Extensions: Check for Extension Updates',
'Extensions: Clear Extensions Search Results',
'Extensions: Configure Recommended Extensions (Workspace)',
'Extensions: Disable All Installed Extensions',
'Extensions: Disable All Installed Extensions for this Workspace',
'Extensions: Disable Auto Update for All Extensions',
'Extensions: Enable All Extensions',
'Extensions: Enable All Extensions for this Workspace',
'Extensions: Enable Auto Update for All Extensions',
'Extensions: Focus on Available Updates View',
'Extensions: Focus on Builtin View',
'Extensions: Focus on Deprecated View',
'Extensions: Focus on Disabled in Restricted Mode View',
'Extensions: Focus on Disabled in Virtual Workspaces View',
'Extensions: Focus on Disabled View',
'Extensions: Focus on Enabled View',
'Extensions: Focus on Extensions View',
'Extensions: Focus on Features View',
'Extensions: Focus on Installed View',
'Extensions: Focus on Limited in Restricted Mode View',
'Extensions: Focus on Limited in Virtual Workspaces View',
'Extensions: Focus on Marketplace View',
'Extensions: Focus on Other Recommendations View',
'Extensions: Focus on Popular View',
'Extensions: Focus on Programming Languages View',
'Extensions: Focus on Recently Updated View',
'Extensions: Focus on Recommended View',
'Extensions: Focus on Themes View',
'Extensions: Focus on Workspace Recommendations View',
'Extensions: Focus on Workspace Unsupported View',
'Extensions: Install Extensions',
'Extensions: Install from VSIX...',
'Extensions: Install Missing Dependencies',
'Extensions: Install Specific Version of Extension...',
'Extensions: Manage Authorized Extension URIs...',
'Extensions: Open Extensions Folder',
'Extensions: Refresh',
'Extensions: Show Built-in Extensions',
'Extensions: Show Disabled Extensions',
'Extensions: Show Enabled Extensions',
'Extensions: Show Extension Updates',
'Extensions: Show Extensions Unsupported By Workspace',
'Extensions: Show Featured Extensions',
'Extensions: Show Popular Extensions',
'Extensions: Show Recently Published Extensions',
'Extensions: Show Recommended Extensions',
'Extensions: Update All Extensions',
'File: Clear Recently Opened...',
'File: Compare Active File With...',
'File: Compare New Untitled Text Files',
'File: Focus on Files Explorer',
'File: New File...',
'File: New Folder...',
'File: Open Active File in New Empty Workspace',
'File: Open Workspace from File...',
'File: Reset Active Editor Read-only in Session',
'File: Reveal Active File in Explorer View',
'File: Revert File',
'File: Save All Files',
'File: Save All in Group',
'File: Set Active Editor Read-only in Session',
'File: Set Active Editor Writeable in Session',
'File: Toggle Active Editor Read-only in Session',
'File: Toggle Auto Save',
'Find With Arguments',
'Find With Selection',
'Fix All',
'Focus Next Cursor',
'Focus Previous Cursor',
'Focus Sticky Scroll',
'Format Document (Forced)',
'Format Document With...',
'Format Modified Lines',
'Format Selection With...',
'Forward a Port',
'Get Configured Package Manager',
'Git API: Get Remote Sources',
'Git API: Get Repositories',
'Git API: Get Repository State',
'Git Base API: Get Remote Sources',
'Git: Abort Merge',
'Git: Abort Rebase',
'Git: Accept Commit Message',
'Git: Add Remote...',
'Git: Add to .gitignore',
'Git: Apply Latest Stash',
'Git: Apply Stash',
'Git: Apply Stash...',
'Git: Checkout to (Detached)...',
'Git: Checkout to...',
'Git: Cherry Pick...',
'Git: Clone',
'Git: Clone (Recursive)',
'Git: Clone Repository Locally and Open on Desktop...',
'Git: Close All Diff Editors',
'Git: Close All Unmodified Editors',
'Git: Close Other Repositories',
'Git: Close Repository',
'Git: Commit',
'Git: Commit (Amend, No Verify)',
'Git: Commit (Amend)',
'Git: Commit (No Verify)',
'Git: Commit (Signed Off, No Verify)',
'Git: Commit (Signed Off)',
'Git: Commit All',
'Git: Commit All (Amend, No Verify)',
'Git: Commit All (Amend)',
'Git: Commit All (No Verify)',
'Git: Commit All (Signed Off, No Verify)',
'Git: Commit All (Signed Off)',
'Git: Commit Empty',
'Git: Commit Empty (No Verify)',
'Git: Commit Staged',
'Git: Commit Staged (Amend, No Verify)',
'Git: Commit Staged (Amend)',
'Git: Commit Staged (No Verify)',
'Git: Commit Staged (Signed Off, No Verify)',
'Git: Commit Staged (Signed Off)',
'Git: Compare with Selected',
'Git: Complete Merge',
'Git: Compute Conflicts With Git',
'Git: Compute Conflicts With Git (Diff3)',
'Git: Copy Commit ID',
'Git: Copy Commit Message',
'Git: Create Branch From...',
'Git: Create Branch...',
'Git: Create Tag',
'Git: Delete Branch...',
'Git: Delete Remote Tag...',
'Git: Delete Tag...',
'Git: Discard All Changes',
'Git: Discard All Tracked Changes',
'Git: Discard All Untracked Changes',
'Git: Discard Changes',
'Git: Discard Commit Message',
'Git: Drop All Stashes...',
'Git: Drop Stash',
'Git: Drop Stash...',
'Git: Fetch',
'Git: Fetch (Prune)',
'Git: Fetch From All Remotes',
'Git: Initialize Repository',
'Git: Manage Unsafe Repositories',
'Git: Merge...',
'Git: Open All Changes',
'Git: Open Changes',
'Git: Open Containing Folder',
'Git: Open File',
'Git: Open File (HEAD)',
'Git: Open Repositories In Parent Folders',
'Git: Open Repository',
'Git: Pop Latest Stash',
'Git: Pop Stash',
'Git: Pop Stash...',
'Git: Publish Branch...',
'Git: Pull',
'Git: Pull (Rebase)',
'Git: Pull from...',
'Git: Push',
'Git: Push (Follow Tags, Force)',
'Git: Push (Follow Tags)',
'Git: Push (Force)',
'Git: Push Tags',
'Git: Push to...',
'Git: Push to... (Force)',
'Git: Rebase Branch...',
'Git: Refresh',
'Git: Remove Remote',
'Git: Rename',
'Git: Rename Branch...',
'Git: Reopen Closed Repositories...',
'Git: Resolve in Merge Editor',
'Git: Restore Commit Template',
'Git: Reveal in Explorer View',
'Git: Reveal in File Explorer',
'Git: Reveal in Finder',
'Git: Revert Change',
'Git: Select for Compare',
'Git: Show Git Output',
'Git: Stage All Changes',
'Git: Stage All Merge Changes',
'Git: Stage All Tracked Changes',
'Git: Stage All Untracked Changes',
'Git: Stage Change',
'Git: Stage Changes',
'Git: Stash',
'Git: Stash (Include Untracked)',
'Git: Stash Staged',
'Git: Sync',
'Git: Sync (Rebase)',
'Git: Undo Last Commit',
'Git: Unstage All Changes',
'Git: Unstage Changes',
'Git: View All Changes',
'Git: View Commit',
'Git: View Stash...',
'Go Back in Edit Locations',
'Go Back in Navigation Locations',
'Go Forward in Edit Locations',
'Go Forward in Navigation Locations',
'Go Previous',
'Go Previous in Edit Locations',
'Go Previous in Navigation Locations',
'Go to caller location',
'Go to Declaration',
'Go to Last Navigation Location',
'Go to Match...',
'Go to Next Folding Range',
'Go to Parent Fold',
'Go to Previous Folding Range',
'Go to Selection Anchor',
'Go to target location',
'Go to Type Definition',
'Help: About',
'Help: Continue Extension Bisect',
'Help: Documentation',
'Help: Interactive Editor Playground',
'Help: Join Us on YouTube',
'Help: List Signal Announcements',
'Help: List Signal Sounds',
'Help: Privacy Statement',
'Help: Profiles',
'Help: Report Issue...',
'Help: Report Performance Issue...',
'Help: Search Feature Requests',
'Help: Settings Sync',
'Help: Signup for the VS Code Newsletter',
'Help: Start Extension Bisect',
'Help: Stop Extension Bisect',
'Help: Stop Troubleshoot Issue',
'Help: Tips and Tricks',
'Help: Troubleshoot Issue...',
'Help: Video Tutorials',
'Help: View License',
'Help: Welcome',
'Hide Custom Title Bar',
'Hide Custom Title Bar In Full Screen',
'Hide Static Variables',
'Hot Code Replace',
'Image Preview: Copy',
'Image Preview: Zoom in',
'Image Preview: Zoom out',
'Increase Current View Size',
'Increase Editor Font Size',
'Increase Editor Height',
'Increase Editor Width',
'Indent Using Spaces',
'Indent Using Tabs',
'Inline Chat: (Developer) Write Exchange to Clipboard',
'Install Package',
'Interactive Window: Focus History',
'Interactive Window: Focus Input Editor',
"Java: Abstract Class...",
"Java: Add Folder to Java Source Path",
"Java: Add Jar Libraries to Project Classpath...",
"Java: Add Library Folders to Project Classpath...",
"Java: Annotation...",
"Java: Attach Source...",
"Java: Base on this Type",
"Java: Class...",
"Java: Clean Java Language Server Workspace",
"Java: Clean Shared Indexes",
"Java: Configure Classpath",
"Java: Configure Java Runtime",
"Java: Create Java Project...",
"Java: Create module-info.java",
"Java: Debug Tests",
"Java: Enum...",
"Java: Export Jar...",
"Java: Extensions Guide",
"Java: File...",
"Java: Flat View",
"Java: Folder...",
"Java: Go to Super Implementation",
"Java: Go to Test",
"Java: Go to Test Subject",
"Java: Hide Non-Java Resources",
"Java: Hierarchical View",
"Java: Import Java Projects into Workspace",
"Java: Install New JDK",
"Java: Interface...",
"Java: Link with Editor",
"Java: List All Java Source Paths",
"Java: New Java File",
"Java: New...",
"Java: Open All Log Files",
"Java: Open Java Extension Log File",
"Java: Open Java Formatter Settings",
"Java: Open Java Formatter Settings with Preview",
"Java: Open Java Language Server Log File",
"Java: Open Text Editor",
"Java: Overview",
"Java: Package...",
"Java: Rebuild Projects",
"Java: Record...",
"Java: Refresh",
"Java: Reload Java Project",
"Java: Remove Folder from Java Source Path",
"Java: Remove from Project Classpath",
"Java: Restart Java Language Server",
"Java: Reveal in Java Project Explorer",
"Java: Run Tests",
"Java: Show Build Job Status",
"Java: Show Class Hierarchy",
"Java: Show Non-Java Resources",
"Java: Show Supertype Hierarchy",
"Java: Show Type Hierarchy",
"Java: Switch to Standard Mode",
"Java: Tips for Beginners",
"Java: Unlink with Editor",
"JavaScript: Go to Project Configuration (jsconfig / tsconfig)",
"JavaScript: Reload Project",
"JavaScript: Remove Unused Imports",
"JavaScript: Sort Imports",
"Join Lines",
"JSON: Clear Schema Cache",
"JSON: Sort Document",
"Learn more about import resolution",
"Loading Environments",
"Local History: Create Entry",
"Local History: Delete All",
"Local History: Find Entry to Restore",
"Manage Trusted Domains",
"Manual Expand Lazy Variables",
"Markdown: Change Preview Security Settings",
"Markdown: Find File References",
"Markdown: Insert Image from Workspace",
"Markdown: Insert Link to File in Workspace",
"Markdown: Open Locked Preview to the Side",
"Markdown: Refresh Preview",
"Markdown: Show Source",
"Markdown: Toggle Preview Locking",
"Maven: Add a dependency...",
"Maven: Add a favorite...",
"Maven: clean",
"Maven: compile",
"Maven: Custom... ",
"Maven: Debug",
"Maven: deploy",
"Maven: Deselect",
"Maven: Exclude Dependency",
"Maven: Execute Commands...",
"Maven: Favorites...",
"Maven: Go to Definition",
"Maven: Go to Effective Dependency",
"Maven: History...",
"Maven: install",
"Maven: New Module...",
"Maven: New Project...",
"Maven: Open POM file",
"Maven: package",
"Maven: Refresh",
"Maven: Reload All Maven Projects",
"Maven: Resolve Conflict...",
"Maven: Run",
"Maven: Run Maven Commands...",
"Maven: Select",
"Maven: Show Dependencies",
"Maven: Show Effective POM",
"Maven: site",
"Maven: Switch to flat view",
"Maven: Switch to hierarchical view",
"Maven: test",
"Maven: test-compile",
"Maven: Update Maven Archetype Catalog",
"Maven: validate",
"Maven: verify",
"Merge Conflict: Accept All Both",
"Merge Conflict: Accept All Current",
"Merge Conflict: Accept All Incoming",
"Merge Conflict: Accept Both",
"Merge Conflict: Accept Current",
"Merge Conflict: Accept Incoming",
"Merge Conflict: Accept Selection",
"Merge Conflict: Compare Current Conflict",
"Merge Conflict: Next Conflict",
"Merge Conflict: Previous Conflict",
"Merge Editor (Dev): Copy Merge Editor State as JSON",
"Merge Editor (Dev): Load Merge Editor State from Folder",
"Merge Editor (Dev): Open Merge Editor State from JSON",
"Merge Editor (Dev): Open Selection In Temporary Merge Editor",
"Merge Editor (Dev): Save Merge Editor State to Folder",
"Merge Editor: Accept All Changes from Left",
"Merge Editor: Accept All Changes from Right",
"Merge Editor: Compare Input 1 With Base",
"Merge Editor: Compare Input 2 With Base",
"Merge Editor: Go to Next Unhandled Conflict",
"Merge Editor: Go to Previous Unhandled Conflict",
"Merge Editor: Open Base File",
"Merge Editor: Reset Choice for 'Close with Conflicts'",
"Merge Editor: Reset Result",
"Merge Editor: Toggle Current Conflict from Left",
"Merge Editor: Toggle Current Conflict from Right",
"Message",
"Move Last Selection To Previous Find Match",
"Move Selected Text Left",
"Move Selected Text Right",
"Navigate Next in Quick Open",
"Navigate Previous in Quick Open",
"New Remote",
"Notebook: Change Cell Language",
"Notebook: Clear All Outputs",
"Notebook: Close Chat",
"Notebook: Collapse All Cell Inputs",
"Notebook: Collapse All Cell Outputs",
"Notebook: Copy Cell",
"Notebook: Copy Cell Output",
"Notebook: Customize Notebook Layout",
"Notebook: Cut Cell",
"Notebook: Execute Above Cells",
"Notebook: Execute Cell and Below",
"Notebook: Execute Cell and Focus Container",
"Notebook: Expand All Cell Inputs",
"Notebook: Expand All Cell Outputs",
"Notebook: Go to Most Recently Failed Cell",
"Notebook: Go to Running Cell",
"Notebook: Helpful",
"Notebook: Insert Code Cell Above and Focus Container",
"Notebook: Insert Code Cell Below and Focus Container",
"Notebook: Insert Markdown Cell Above",
"Notebook: Insert Markdown Cell Below",
"Notebook: Interrupt",
"Notebook: Join Selected Cells",
"Notebook: Paste Cell",
"Notebook: Render All Markdown Cells",
"Notebook: Report Issue",
"Notebook: Run All",
"Notebook: Save Mimetype Display Order",
"Notebook: Select between Notebook Layouts",
"Notebook: Select Indentation",
"Notebook: Show Cell Line Numbers",
"Notebook: Stop Cell Execution",
"Notebook: Stop Execution",
"Notebook: Stop Request",
"Notebook: Toggle Notebook Line Numbers",
"Notebook: Toggle Outputs",
"Notebook: Unhelpful",
"Notifications: Clear All Notifications",
"Notifications: Focus Notification Toast",
"Notifications: Toggle Do Not Disturb Mode",
"Notifications: Toggle Do Not Disturb Mode By Source...",
"Open",
"Open 'launch.json'",
"Open Disassembly View",
"Open in Terminal",
"Open in vscode.dev",
"Open IPYNB File In Notebook Editor",
"Open Java Language Server Error Log File",
"Open Java Language Server Output Log File",
"Open Link",
"Open Port in Browser",
"Open SSH Config File",
"Output: Focus on Output View",
"Output: Show Output Channels...",
"Paste as Text",
"Paste As...",
"Pause All",
"Pause Others",
"Peek Declaration",
"Peek References",
"Peek Type Definition",
"Peek Type Hierarchy",
"Port Forwarding: Restart Forwarding System",
"Port Forwarding: Show Log",
"Ports: Focus on Ports View",
"Preferences: Browse Color Themes in Marketplace",
"Preferences: Clear Keyboard Shortcuts Search History",
"Preferences: Configure Language Specific Settings...",
"Preferences: Configure Runtime Arguments",
"Preferences: File Icon Theme",
"Preferences: Keymaps",
"Preferences: Language Extensions",
"Preferences: Open Accessibility Settings",
"Preferences: Open Application Settings (JSON)",
"Preferences: Open Default Keyboard Shortcuts (JSON)",
"Preferences: Open Default Settings (JSON)",
"Preferences: Open Folder Settings",
"Preferences: Open Folder Settings (JSON)",
"Preferences: Open Keyboard Shortcuts (JSON)",
"Preferences: Open Remote Settings (JSON) (vscode-remote)",
"Preferences: Open Remote Settings (vscode-remote)",
"Preferences: Open Settings (UI)",
"Preferences: Open User Settings",
"Preferences: Open User Settings (JSON)",
"Preferences: Open Workspace Settings",
"Preferences: Open Workspace Settings (JSON)",
"Preferences: Product Icon Theme",
"Preferences: Toggle between Light/Dark Themes",
"Prettier: Create Configuration File",
"Problems: Focus on Problems View",
"Problems: Show message in multiple lines",
"Problems: Show message in single line",
"Profiles: Create a Temporary Profile",
"Profiles: Create Profile...",
"Profiles: Delete Profile...",
"Profiles: Export Profile...",
"Profiles: Import Profile...",
"Profiles: Rename...",
"Profiles: Save Current Profile As...",
"Profiles: Show Profile Contents",
"Profiles: Switch Profile...",
"Publish to GitHub",
"Pylance debugging: Dump parse tree ...",
"Pylance debugging: Dump token streams ...",
"Pylance debugging: Dump type info ...",
"Pylance debugging: Pylance: Dump cached type info ...",
"Pylance debugging: Pylance: Dump code flow graph for node ...",
"Pylance: Clear All Persisted Indices",
"Pylance: Report Issue...",
"Python Debugger: Clear Cache and Reload Window",
"Python Debugger: Python Debugger: Debug Python File",
"Python Debugger: Python Debugger: Debug using launch.json",
"Python Debugger: Show Output",
"Python: Clear Cache and Reload Window",
"Python: Clear Environment Manager cache",
"Python: Clear Workspace Interpreter Setting",
"Python: Configure Tests",
"Python: Create Environment...",
"Python: Create Terminal",
"Python: Enable Source Map Support For Extension Debugging",
"Python: Focus on Global Environments View",
"Python: Focus on Workspace Environments View",
"Python: Install the Jupyter extension",
"Python: Launch TensorBoard",
"Python: New Python File",
"Python: Report Issue...",
"Python: Restart Language Server",
"Python: Run Python File",
"Python: Run Python File in Dedicated Terminal",
"Python: Run Python File in Terminal",
"Python: Run Selection/Line in Django Shell",
"Python: Select Interpreter",
"Python: Show Language Server Output",
"Python: Show Output",
"Python: Start REPL",
"Quick Open Previous Editor from History",
"Read Line With Inline Hints",
"Reapply All Breakpoints",
"Rebuild All",
"Rebuild Project",
"Refactor Preview: Focus on Refactor Preview View",
"References: Clear",
"References: Clear History",
"References: Find All Implementations",
"References: Focus on C/C: Other references results View",
"References: Focus on Reference Search Results View",
"References: Refresh",
"References: Show History",
"Refresh",
"Refresh Environments",
"Refresh Explorer",
"Reindent Lines",
"Reindent Selected Lines",
"Reload definition",
"Reload Project",
"Remote Explorer: Focus on Remotes (Tunnels/SSH) View",
"Remote Explorer: Focus on WSL Targets View",
"Remote Tunnels: Configure Tunnel Name...",
"Remote Tunnels: Copy Browser URI to Clipboard",
"Remote Tunnels: Show Remote Tunnel Service Log",
"Remote Tunnels: Turn off Remote Tunnel Access...",
"Remote Tunnels: Turn on Remote Tunnel Access...",
"Remote-SSH: Add New SSH Host...",
"Remote-SSH: Connect Current Window to Host...",
"Remote-SSH: Connect to Host...",
"Remote-SSH: Get Started with SSH",
"Remote-SSH: Help",
"Remote-SSH: Kill Current VS Code Server",
"Remote-SSH: Kill Local Connection Server For Host...",
"Remote-SSH: Kill VS Code Server on Host...",
"Remote-SSH: New Window on Active Host",
"Remote-SSH: Open SSH Configuration File...",
"Remote-SSH: Open Web UI",
"Remote-SSH: Provide Feedback",
"Remote-SSH: Report Issue...",
"Remote-SSH: Settings",
"Remote-SSH: Show Log",
"Remote-SSH: Uninstall VS Code Server from Host...",
"Remote: Close Remote Connection",
"Remote: Install Remote Development Extensions",
"Remove All Breakpoints",
"Remove All Event Listener Breakpoints",
"Remove all excluded callers",
"Remove excluded caller",
"Remove from Recent List",
"Remove XHR/fetch Breakpoint",
"Rerun",
"Reset choice for 'File operation needs preview'",
"Reset Editor Font Size",
"Reset Suggest Widget Size",
"Run",
"Run and Debug: Focus on Breakpoints View",
"Run and Debug: Focus on Call Stack View",
"Run and Debug: Focus on Cpptools: SSH targets View",
"Run and Debug: Focus on Event Listener Breakpoints View",
"Run and Debug: Focus on Excluded Callers View",
"Run and Debug: Focus on Loaded Scripts View",
"Run and Debug: Focus on Run View",
"Run and Debug: Focus on Variables View",
"Run and Debug: Focus on Watch View",
"Run Install",
"Run Java",
"Run NPM Script in Folder...",
"Run Script",
"Save All",
"Search Editor: Focus Search Editor Files to Exclude",
"Search Editor: Focus Search Editor Files to Include",
"Search Editor: New Search Editor",
"Search Editor: Open New Search Editor to the Side",
"Search Editor: Open Search Editor",
"Search: Clear Search History",
"Search: Clear Search Results",
"Search: Collapse All",
"Search: Expand All",
"Search: Focus List",
"Search: Focus on Search View",
"Search: Quick Search (Experimental)",
"Search: Refresh",
"Search: View as List",
"Search: View as Tree",
"Select Next in Quick Open",
"Select Previous in Quick Open",
"Select to Bracket",
"Set as active workspace interpreter",
"Settings Sync: Backup and Sync Settings...",
"Settings Sync: Configure...",
"Settings Sync: Focus on Conflicts View",
"Settings Sync: Focus on Sync Activity (Developer) View",
"Settings Sync: Focus on Sync Activity (Local) View",
"Settings Sync: Focus on Sync Activity (Remote) View",
"Settings Sync: Focus on Synced Machines View",
"Settings Sync: Focus on Troubleshoot View",
"Settings Sync: Open Local Backups Folder",
"Settings Sync: Show Conflicts (0)",
"Settings Sync: Show Log",
"Settings Sync: Show Settings",
"Settings Sync: Show Synced Data",
"Settings Sync: Sync Now",
"Settings Sync: Turn Off",
"Show as Dec",
"Show as Hex",
"Show CodeLens Commands For Current Line",
"Show Custom Title Bar",
"Show Definition Preview Hover",
"Show Emmet Commands",
"Show Exclude Options",
"Show or Focus Standalone Color Picker",
'Show Qualified Names',
'Show Simple Names',
'Show Static Variables',
'Sign in with GitHub',
'Sign in with Microsoft',
'Simple Browser: Show',
'Snippets: Configure User Snippets',
'Snippets: Fill File with Snippet',
'Snippets: Insert Snippet',
'Snippets: Surround with Snippet...',
'Sort Lines Ascending',
'Sort Lines Descending',
'Source Action...',
'Source Control: Focus on Source Control Repositories View',
'Source Control: Focus on Source Control View',
'Step Into Target',
'Stop Forwarding Port',
'Switch Window...',
'Tasks: Configure Default Build Task',
'Tasks: Configure Default Test Task',
'Tasks: Configure Task',
'Tasks: Manage Automatic Tasks',
'Tasks: Open User Tasks',
'Tasks: Open Workspace Tasks',
'Tasks: Rerun Last Task',
'Tasks: Restart Running Task',
'Tasks: Run Task',
'Tasks: Run Test Task',
'Tasks: Show Running Tasks',
'Tasks: Show Task Log',
'Tasks: Terminate Task',
'Terminal: Attach to Session',
'Terminal: Change Color...',
'Terminal: Change Icon...',
'Terminal: Clear',
'Terminal: Clear Previous Session History',
'Terminal: Configure Terminal Settings',
'Terminal: Copy Last Command',
'Terminal: Copy Last Command and Output',
'Terminal: Copy Last Command Output',
'Terminal: Copy Selection as HTML',
'Terminal: Create New Terminal (In Active Workspace)',
'Terminal: Create New Terminal (With Profile)',
'Terminal: Create New Terminal in Editor Area',
'Terminal: Create New Terminal in Editor Area to the Side',
'Terminal: Create New Terminal Starting in a Custom Working Directory',
'Terminal: Decrease Font Size',
'Terminal: Detach Session',
'Terminal: Focus on Terminal View',
'Terminal: Increase Font Size',
'Terminal: Join Terminals',
'Terminal: Kill All Terminals',
'Terminal: Kill the Active Terminal Instance',
'Terminal: Move Terminal into Editor Area',
'Terminal: Move Terminal into New Window',
'Terminal: Move Terminal into Panel',
'Terminal: Open Last Local File Link',
'Terminal: Open Last URL Link',
'Terminal: Relaunch Active Terminal',
'Terminal: Rename the Currently Active Terminal',
'Terminal: Rename...',
'Terminal: Reset Font Size',
'Terminal: Resize Terminal Down',
'Terminal: Resize Terminal Left',
'Terminal: Resize Terminal Right',
'Terminal: Resize Terminal Up',
'Terminal: Run Active File In Active Terminal',
'Terminal: Run Selected Text In Active Terminal',
'Terminal: Select All',
'Terminal: Select Default Profile',
'Terminal: Select To Next Line',
'Terminal: Select To Previous Line',
'Terminal: Set Fixed Dimensions',
'Terminal: Show Environment Contributions',
'Terminal: Split Terminal (In Active Workspace)',
'Terminal: Start Terminal Voice',
'Terminal: Stop Terminal Voice',
'Terminal: Switch Active Terminal',
'Terminal: Switch Terminal',
'Terminal: Toggle Sticky Scroll',
'Terminal: Unsplit Terminal',
'Test Results: Focus on Test Results View',
'Test: Cancel Test Refresh',
'Test: Clear All Results',
'Test: Clear Coverage',
'Test: Configure Test Profiles',
'Test: Open Coverage',
'Test: Start Continuous Run',
'Test: Stop Continuous Run',
'Testing: Focus on Test Coverage View',
'Testing: Focus on Test Explorer View',
'Toggle Activate Breakpoints',
'Toggle Column Selection Mode',
'Toggle Event Listener Breakpoints',
'Toggle Multi-Cursor Modifier',
'Toggle Source Code in Disassembly View',
'Transform to Camel Case',
'Transform to Kebab Case',
'Transform to Lowercase',
'Transform to Snake Case',
'Transform to Title Case',
'Transform to Uppercase',
'Transpose Characters around the Cursor',
'Transpose Letters',
'Trigger Inline Suggestion',
'Trigger Symbol Highlight',
'Types: Show Subtypes',
'Types: Show Supertypes',
'Types: Show Type Hierarchy',
'TypeScript: Find File References',
'TypeScript: Go to Project Configuration (tsconfig)',
'TypeScript: Go to Source Definition',
'TypeScript: Open TS Server log',
'TypeScript: Reload Project',
'TypeScript: Remove Unused Imports',
'TypeScript: Restart TS Server',
'TypeScript: Select TypeScript Version...',
'TypeScript: Sort Imports',
'Uninstall Package',
'Unregister Tunnel',
'Update All Packages',
'Update Package',
'View Packages',
'View: Clear Output',
'View: Close Editor Group',
'View: Close Editor in All Groups',
'View: Close Editors in Other Groups',
'View: Close Editors to the Left in Group',
'View: Close Editors to the Right in Group',
'View: Close Other Editors in Group',
'View: Close Pinned Editor',
'View: Close Primary Side Bar',
'View: Copy Editor Group into New Window',
'View: Duplicate Editor Group Down',
'View: Duplicate Editor Group Left',
'View: Duplicate Editor Group Right',
'View: Duplicate Editor Group Up',
'View: Expand Editor Group',
'View: Expand Editor Group and Hide Side Bars',
'View: Focus Active Editor Group',
'View: Focus Activity Bar',
'View: Focus Banner',
'View: Focus First Side in Active Editor',
'View: Focus into Panel',
'View: Focus into Secondary Side Bar',
'View: Focus Last Editor Group',
'View: Focus Next Editor Group',
'View: Focus Other Side in Active Editor',
'View: Focus Previous Editor Group',
'View: Focus Problems (Errors, Warnings, Infos)',
'View: Focus Second Side in Active Editor',
'View: Focus Status Bar',
'View: Focus Title Bar',
'View: Grid Editor Layout (2x2)',
'View: Hide Activity Bar',
'View: Hide Editor Actions',
'View: Hide Editor Tabs',
'View: Hide Editor Tabs in Zen Mode',
'View: Hide Panel',
'View: Hide Secondary Side Bar',
'View: Join All Editor Groups',
'View: Join Editor Group with Next Group',
'View: Lock Editor Group',
'View: Maximize Editor Group and Hide Side Bars',
'View: Move Activity Bar to Side',
'View: Move Activity Bar to Top',
'View: Move Editor Actions to Tab Bar',
'View: Move Editor Actions to Title Bar',
'View: Move Editor Group into New Window',
'View: Move Editor into Group Above',
'View: Move Editor into Group Below',
'View: Move Editor into Left Group',
'View: Move Editor into New Window',
'View: Move Editor into Right Group',
'View: Move Focused View',
'View: Move Panel Left',
'View: Move Panel Right',
'View: Move Panel To Bottom',
'View: Move Panel Views To Secondary Side Bar',
'View: Move Secondary Side Bar Views To Panel',
'View: Move View',
'View: Navigate Between Editor Groups',
'View: Navigate to the View Above',
'View: Navigate to the View Below',
'View: Navigate to the View on the Left',
'View: Navigate to the View on the Right',
'View: New Editor Group Above',
'View: New Editor Group Below',
'View: New Editor Group to the Left',
'View: New Editor Group to the Right',
'View: New Empty Editor Window',
'View: Next Panel View',
'View: Next Primary Side Bar View',
'View: Open First Editor in Group',
'View: Open Next Recently Used Editor',
'View: Open Next Recently Used Editor In Group',
'View: Open Previous Recently Used Editor',
'View: Open Previous Recently Used Editor In Group',
'View: Open View',
'View: Previous Panel View',
'View: Previous Primary Side Bar View',
'View: Quick Open Least Recently Used Editor',
'View: Quick Open Previous Recently Used Editor',
'View: Reopen Editor With Text Editor',
'View: Reopen Editor With...',
'View: Reset All Menus',
'View: Reset Editor Group Sizes',
'View: Reset Focused View Location',
'View: Reset Language Status Interaction Counter',
'View: Reset View Locations',
'View: Restore Editors into Main Window',
'View: Revert and Close Editor',
'View: Separate Pinned Editor Tabs',
'View: Set Panel Alignment to Center',
'View: Set Panel Alignment to Justify',
'View: Set Panel Alignment to Left',
'View: Set Panel Alignment to Right',
'View: Show All Editors By Most Recently Used',
'View: Show Chat',
'View: Show Editor Actions',
'View: Show Editors in Active Group By Most Recently Used',
'View: Show Multiple Editor Tabs',
'View: Show Multiple Editor Tabs in Zen Mode',
'View: Show Profiles',
'View: Show Python',
'View: Show References',
'View: Show Remote Explorer',
'View: Show Settings Sync',
'View: Show Single Editor Tab',
'View: Show Single Editor Tab in Zen Mode',
'View: Show Testing',
'View: Show Voice Assistant',
'View: Single Column Editor Layout',
'View: Split Editor into First Group',
'View: Split Editor into Group Above',
'View: Split Editor into Group Below',
'View: Split Editor into Last Group',
'View: Split Editor into Left Group',
'View: Split Editor into Next Group',
'View: Split Editor into Previous Group',
'View: Split Editor into Right Group',
'View: Three Columns Editor Layout',
'View: Three Rows Editor Layout',
'View: Toggle Breadcrumbs',
'View: Toggle Centered Layout',
'View: Toggle Control Characters',
'View: Toggle Editor Area Visibility',
'View: Toggle Editor Group Lock',
'View: Toggle Editor Group Sizes',
'View: Toggle Editor Sticky Scroll',
'View: Toggle Editor Type',
'View: Toggle Layout of Split Editor in Group',
'View: Toggle Maximized Panel',
'View: Toggle Menu Bar',
'View: Toggle Minimap',
'View: Toggle Notebook Sticky Scroll',
'View: Toggle Ports',
'View: Toggle Primary Side Bar Position',
'View: Toggle Refactor Preview',
'View: Toggle Render Whitespace',
'View: Toggle Split Editor in Group',
'View: Toggle Status Bar Visibility',
'View: Toggle Tree Sticky Scroll',
'View: Two Columns Bottom Editor Layout',
'View: Two Columns Editor Layout',
'View: Two Rows Editor Layout',
'View: Two Rows Right Editor Layout',
'View: Unlock Editor Group',
'Voice Assistant: Focus on Voice Assistant View',
'Welcome: Open Walkthrough...',
'Workspaces: Add Folder to Workspace...',
'Workspaces: Configure Workspace Trust Settings',
'Workspaces: Duplicate As Workspace in New Window',
'Workspaces: Manage Workspace Trust',
'Workspaces: Open Workspace Configuration File',
'Workspaces: Remove Folder from Workspace...',
'Workspaces: Save Workspace As...',
'WSL: Add a Distro',
'WSL: Connect in Current Window',
'WSL: Connect in New Window',
'WSL: Connect to WSL',
'WSL: Connect to WSL in New Window',
'WSL: Connect to WSL using Distro in New Window...',
'WSL: Connect to WSL using Distro...',
'WSL: Delete Distro',
'WSL: Get Started with WSL',
'WSL: Help',
'WSL: Open Folder in WSL',
'WSL: Open Folder in WSL...',
'WSL: Provide Feedback',
'WSL: Refresh',
'WSL: Remove Recent Folder',
'WSL: Reopen Folder in Windows',
'WSL: Reopen Folder in WSL',
'WSL: Report Issue...',
'WSL: Set as Default Distro',
'WSL: Show Log'
]