commands = ["Delete Line",
"Terminal: Create New Terminal",
"Terminal: Resize Terminal Left",
"Terminal: Resize Terminal Up",
"Terminal: Resize Terminal Down",
"Terminal: Resize Terminal Right",
"Terminal: Kill All Terminals",
"Terminal: Focus on Terminal View",
"Terminal: Clear",
"Add Cursor Above",
"Add Cursor Below",
"Add Cursors To Top",
"Add Cursors to Line Ends",
"Add Cursors To Bottom",
"View: Zoom In",
"View: Zoom Out",
"View: Reset Zoom",
"Undo",
"Redo",
"Copy",
"Paste",
]