export interface StringDictionary {
    [key: string]: string;
}

export let commandNameToIDZhCn: StringDictionary = {
    '帮助: 键盘快捷方式参考': 'workbench.action.keybindingsReference',
    '笔记本: 编辑单元格': 'notebook.cell.edit',
    '笔记本: 拆分单元格': 'notebook.cell.split',
    '笔记本: 单元格光标 Page Down': 'notebook.cell.cursorPageDown',
    '笔记本: 单元格光标 Page Down 选择': 'notebook.cell.cursorPageDownSelect',
    '笔记本: 单元格光标 Page Up': 'notebook.cell.cursorPageUp',
    '笔记本: 单元格光标 Page Up 选择': 'notebook.cell.cursorPageUpSelect',
    '笔记本: 复制单元格': 'notebook.cell.copy',
    '笔记本: 加入上一个单元格': 'notebook.cell.joinAbove',
    '笔记本: 加入下一个单元格': 'notebook.cell.joinBelow',
    '笔记本: 剪切单元格': 'notebook.cell.cut',
    '笔记本: 将查找匹配项添加到所选内容': 'notebook.addFindMatchToSelection',
    '笔记本: 将单元格更改为 Markdown': 'notebook.cell.changeToMarkdown',
    '笔记本: 将单元格更改为代码': 'notebook.cell.changeToCode',
    '笔记本: 接受单元格检测到的语言': 'notebook.cell.detectLanguage',
    '笔记本: 解除活动单元格输出聚焦': 'notebook.cell.focusOutOutput',
    '笔记本: 聚焦第一个单元格': 'notebook.focusTop',
    '笔记本: 聚焦活动单元格输出': 'notebook.cell.focusInOutput',
    '笔记本: 聚焦上一个单元格编辑器': 'notebook.focusPreviousEditor',
    '笔记本: 聚焦下一个单元格编辑器': 'notebook.focusNextEditor',
    '笔记本: 聚焦最后一个单元格': 'notebook.focusBottom',
    '笔记本: 批注所选单元格': 'notebook.commentSelectedCells',
    '笔记本: 切换笔记本行号': 'notebook.toggleLineNumbers',
    '笔记本: 切换滚动单元格输出': 'notebook.cell.toggleOutputScrolling',
    '笔记本: 切换输出': 'notebook.cell.toggleOutputs',
    '笔记本: 清除单元格输出': 'notebook.cell.clearOutputs',
    '笔记本: 全选': 'notebook.cell.output.selectAll',
    '笔记本: 删除单元格': 'notebook.cell.delete',
    '笔记本: 删除权利': 'noteMultiCursor.deleteRight',
    '笔记本: 上移单元格': 'notebook.cell.moveUp',
    '笔记本: 设置笔记本的格式': 'notebook.format',
    '笔记本: 停止编辑单元格': 'notebook.cell.quitEdit',
    '笔记本: 退出多光标模式': 'noteMultiCursor.exit',
    '笔记本: 下移单元格': 'notebook.cell.moveDown',
    '笔记本: 显示单元格行号': 'notebook.cell.toggleLineNumbers',
    '笔记本: 显示单元故障操作': 'notebook.cell.openFailureActions',
    '笔记本: 向上复制单元格': 'notebook.cell.copyUp',
    '笔记本: 向下复制单元格': 'notebook.cell.copyDown',
    '笔记本: 向左删除': 'noteMultiCursor.deleteLeft',
    '笔记本: 在笔记本中查找': 'notebook.find',
    '笔记本: 在上方插入代码单元格': 'notebook.cell.insertCodeCellAbove',
    '笔记本: 在上方插入代码单元格和焦点容器': 'notebook.cell.insertCodeCellAboveAndFocusContainer',
    '笔记本: 在上方粘贴单元格': 'notebook.cell.pasteAbove',
    '笔记本: 粘贴单元格': 'notebook.cell.paste',
    '笔记本: 展开单元格': 'notebook.unfold',
    '笔记本: 展开单元格输出': 'notebook.cell.expandCellOutput',
    '笔记本: 展开单元格输入': 'notebook.cell.expandCellInput',
    '笔记本: 折叠单元格': 'notebook.fold',
    '笔记本: 折叠单元格输出': 'notebook.cell.collapseCellOutput',
    '笔记本: 折叠单元格输入': 'notebook.cell.collapseCellInput',
    '笔记本: 执行笔记本单元格并在下方插入': 'notebook.cell.executeAndInsertBelow',
    '笔记本: 执行笔记本单元格并在下方选择': 'notebook.cell.executeAndSelectBelow',
    '笔记本: 执行单元格': 'notebook.cell.execute',
    '笔记本: 执行单元格和焦点容器': 'notebook.cell.executeAndFocusContainer',
    '笔记本: 中心活动单元格': 'notebook.centerActiveCell',
    裁剪尾随空格: 'editor.action.trimTrailingWhitespace',
    '测试: 调试上次运行': 'testing.debugLastRun',
    '测试: 调试失败的测试': 'testing.debugFailTests',
    '测试: 调试所有测试': 'testing.debugAll',
    '测试: 对所有测试运行覆盖率测试': 'testing.coverageAll',
    '测试: 快速查看输出': 'testing.openOutputPeek',
    '测试: 切换内联测试输出': 'testing.toggleInlineTestOutput',
    '测试: 切换内联覆盖率': 'testing.toggleInlineCoverage',
    '测试: 刷新测试': 'testing.refreshTests',
    '测试: 显示输出': 'testing.showMostRecentOutput',
    '测试: 运行光标下覆盖率测试': 'testing.coverageAtCursor',
    '测试: 运行所有测试': 'testing.runAll',
    '测试: 在当前文件中调试测试': 'testing.debugCurrentFile',
    '测试: 在当前文件中运行测试': 'testing.runCurrentFile',
    '测试: 在当前文件中运行覆盖率测试': 'testing.coverageCurrentFile',
    '测试: 在光标处调试测试': 'testing.debugAtCursor',
    '测试: 在光标处运行测试': 'testing.runAtCursor',
    '测试: 在速览中切换测试历史记录': 'testing.toggleTestingPeekHistory',
    '测试: 重新运行上次运行': 'testing.reRunLastRun',
    '测试: 重新运行上一次覆盖率测试': 'testing.coverageLastRun',
    '测试: 转到“上一个测试失败”': 'testing.goToPreviousMessage',
    '测试: 转到“下一个测试失败”': 'testing.goToNextMessage',
    '查看: 保留编辑器': 'workbench.action.keepEditor',
    '查看: 拆分编辑器': 'workbench.action.splitEditor',
    '查看: 打开上一个编辑器': 'workbench.action.previousEditor',
    '查看: 打开下一个编辑器': 'workbench.action.nextEditor',
    '查看: 打开组中的下一个编辑器': 'workbench.action.nextEditorInGroup',
    '查看: 打开组中上一个编辑器': 'workbench.action.previousEditorInGroup',
    '查看: 打开组中最后一个编辑器': 'workbench.action.lastEditorInGroup',
    '查看: 放大': 'workbench.action.zoomIn',
    '查看: 固定编辑器': 'workbench.action.pinEditor',
    '查看: 关闭编辑器': 'workbench.action.closeActiveEditor',
    '查看: 关闭所有编辑器': 'workbench.action.closeAllEditors',
    '查看: 关闭所有编辑器组': 'workbench.action.closeAllGroups',
    '查看: 关闭组中的所有编辑器': 'workbench.action.closeEditorsInGroup',
    '查看: 关闭组中已保存的编辑器': 'workbench.action.closeUnmodifiedEditors',
    '查看: 将编辑器复制到新窗口': 'workbench.action.copyEditorToNewWindow',
    '查看: 将编辑器移动到第一组': 'workbench.action.moveEditorToFirstGroup',
    '查看: 将编辑器移动到上一组': 'workbench.action.moveEditorToPreviousGroup',
    '查看: 将编辑器移动到下一组': 'workbench.action.moveEditorToNextGroup',
    '查看: 将编辑器移动到最后一组': 'workbench.action.moveEditorToLastGroup',
    '查看: 将焦点置于主侧栏': 'workbench.action.focusSideBar',
    '查看: 聚焦到右侧编辑器组': 'workbench.action.focusRightGroup',
    '查看: 聚焦到左侧编辑器组': 'workbench.action.focusLeftGroup',
    '查看: 聚焦于第一个编辑器组': 'workbench.action.focusFirstEditorGroup',
    '查看: 快速打开组中上一个最近使用过的编辑器': 'workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup',
    '查看: 快速打开组中最近使用频率最低的编辑器': 'workbench.action.quickOpenLeastRecentlyUsedEditorInGroup',
    '查看: 切换 调试控制台': 'workbench.debug.action.toggleRepl',
    '查看: 切换 输出': 'workbench.action.output.toggleOutput',
    '查看: 切换 问题': 'workbench.actions.view.problems',
    '查看: 切换 终端': 'workbench.action.terminal.toggleTerminal',
    '查看: 切换禅模式': 'workbench.action.toggleZenMode',
    '查看: 切换辅助侧栏可见性': 'workbench.action.toggleAuxiliaryBar',
    '查看: 切换面板可见性': 'workbench.action.togglePanel',
    '查看: 切换全屏': 'workbench.action.toggleFullScreen',
    '查看: 切换主侧栏可见性': 'workbench.action.toggleSidebarVisibility',
    '查看: 切换自动换行': 'editor.action.toggleWordWrap',
    '查看: 切换最大化编辑器组': 'workbench.action.toggleMaximizeEditorGroup',
    '查看: 取消固定编辑器': 'workbench.action.unpinEditor',
    '查看: 缩小': 'workbench.action.zoomOut',
    '查看: 显示 扩展': 'workbench.view.extensions',
    '查看: 显示 搜索': 'workbench.view.search',
    '查看: 显示 源代码管理': 'workbench.view.scm',
    '查看: 显示 运行和调试': 'workbench.view.debug',
    '查看: 显示 资源管理器': 'workbench.view.explorer',
    '查看: 向上拆分编辑器': 'workbench.action.splitEditorUp',
    '查看: 向上移动编辑器组': 'workbench.action.moveActiveEditorGroupUp',
    '查看: 向下拆分编辑器': 'workbench.action.splitEditorDown',
    '查看: 向下移动编辑器组': 'workbench.action.moveActiveEditorGroupDown',
    '查看: 向右拆分编辑器': 'workbench.action.splitEditorRight',
    '查看: 向右移动编辑器': 'workbench.action.moveEditorRightInGroup',
    '查看: 向右移动编辑器组': 'workbench.action.moveActiveEditorGroupRight',
    '查看: 向左拆分编辑器': 'workbench.action.splitEditorLeft',
    '查看: 向左移动编辑器': 'workbench.action.moveEditorLeftInGroup',
    '查看: 向左移动编辑器组': 'workbench.action.moveActiveEditorGroupLeft',
    '查看: 在组中拆分编辑器': 'workbench.action.splitEditorInGroup',
    '查看: 在组中加入编辑器': 'workbench.action.joinEditorInGroup',
    '查看: 正交拆分编辑器': 'workbench.action.splitEditorOrthogonal',
    '查看: 重新打开已关闭的编辑器': 'workbench.action.reopenClosedEditor',
    '查看: 重置缩放': 'workbench.action.zoomReset',
    '查看: 专注上述编辑器组': 'workbench.action.focusAboveGroup',
    '查看: 专注上一部分': 'workbench.action.focusPreviousPart',
    '查看: 专注下一部分': 'workbench.action.focusNextPart',
    '查看: 专注以下编辑器组': 'workbench.action.focusBelowGroup',
    查看实现: 'editor.action.peekImplementation',
    查找: 'actions.find',
    查找上一个: 'editor.action.previousMatchFindAction',
    查找上一个选择: 'editor.action.previousSelectionMatchFindAction',
    查找下一个: 'editor.action.nextMatchFindAction',
    查找下一个选择: 'editor.action.nextSelectionMatchFindAction',
    撤消: 'undo',
    触发参数提示: 'editor.action.triggerParameterHints',
    触发建议: 'editor.action.triggerSuggest',
    '创建: 新建文件...': 'welcome.showNewFileEntries',
    打开侧边的定义: 'editor.action.revealDefinitionAside',
    打开辅助功能帮助: 'editor.action.accessibilityHelp',
    打开辅助视图: 'editor.action.accessibleView',
    打开新的外部终端: 'workbench.action.terminal.openNativeConsole',
    '调试: 单步调试': 'workbench.action.debug.stepInto',
    '调试: 单步跳出': 'workbench.action.debug.stepOut',
    '调试: 单步执行目标': 'workbench.action.debug.stepIntoTarget',
    '调试: 断开连接': 'workbench.action.debug.disconnect',
    '调试: 继续': 'workbench.action.debug.continue',
    '调试: 聚焦上一个调试控制台': 'workbench.action.debug.prevConsole',
    '调试: 聚焦下一个调试控制台': 'workbench.action.debug.nextConsole',
    '调试: 开始调试': 'workbench.action.debug.start',
    '调试: 开始执行(不调试)': 'workbench.action.debug.run',
    '调试: 内联断点': 'editor.debug.action.toggleInlineBreakpoint',
    '调试: 切换断点': 'editor.debug.action.toggleBreakpoint',
    '调试: 停止': 'workbench.action.debug.stop',
    '调试: 显示悬停': 'editor.debug.action.showDebugHover',
    '调试: 暂停': 'workbench.action.debug.pause',
    '调试: 重启': 'workbench.action.debug.restart',
    '调试: 逐过程': 'workbench.action.debug.stepOver',
    '调试控制台：接受输入': 'repl.action.acceptInput',
    定义键绑定: 'editor.action.defineKeybinding',
    返回: 'workbench.action.navigateBack',
    复制: 'editor.action.clipboardCopyAction',
    格式化文档: 'editor.action.formatDocument',
    格式化选定内容: 'editor.action.formatSelection',
    根据所选内容创建折叠范围: 'editor.createFoldingRangeFromSelection',
    更改所有匹配项: 'editor.action.changeAll',
    更改语言模式: 'workbench.action.editor.changeLanguageMode',
    '工作区: 关闭工作区': 'workbench.action.closeFolder',
    关闭窗口: 'workbench.action.closeWindow',
    关闭异常小组件: 'editor.debug.action.closeExceptionWidget',
    光标撤消: 'cursorUndo',
    '欢迎: 后退': 'welcome.goBack',
    恢复: 'redo',
    剪切: 'editor.action.clipboardCutAction',
    检测内容中的语言: 'editor.detectLanguage',
    将上次选择移动到下一个查找匹配项: 'editor.action.moveSelectionToNextFindMatch',
    将下一个查找匹配项添加到选择: 'editor.action.addSelectionToNextFindMatch',
    '交互窗口: 焦点历史记录': 'interactive.history.focus',
    '交互窗口: 焦点输入编辑器': 'interactive.input.focus',
    接受内联建议: 'editor.action.inlineSuggest.commit',
    接受内联建议的下一个字: 'editor.action.inlineSuggest.acceptNextWord',
    接受内联完成: 'editor.action.accessibleViewAcceptInlineCompletion',
    禁用辅助视图提示: 'editor.action.accessibleViewDisableHint',
    聚焦并选择痕迹导航: 'breadcrumbs.focusAndSelect',
    '聚焦到“导航路径”视图': 'breadcrumbs.focus',
    '开发人员: 切换开发人员工具': 'workbench.action.toggleDevTools',
    '开发人员: 重新加载窗口': 'workbench.action.reloadWindow',
    '可访问的差异查看器: 转至上一个差异': 'editor.action.accessibleDiffViewer.prev',
    '可访问的差异查看器: 转至下一个差异': 'editor.action.accessibleDiffViewer.next',
    '快速修复...': 'editor.action.quickFix',
    '聊天: 插入到终端中': 'workbench.action.chat.runInTerminal',
    '聊天: 打开聊天': 'workbench.action.chat.open',
    '聊天: 开始语音聊天': 'workbench.action.chat.startVoiceChat',
    '聊天: 上一个代码块': 'workbench.action.chat.previousCodeBlock',
    '聊天: 上一文件树': 'workbench.action.chat.previousFileTree',
    '聊天: 停止大声朗读': 'workbench.action.speech.stopReadAloud',
    '聊天: 停止收听': 'workbench.action.chat.stopListening',
    '聊天: 停止收听并提交': 'workbench.action.chat.stopListeningAndSubmit',
    '聊天: 下一个代码块': 'workbench.action.chat.nextCodeBlock',
    '聊天: 下一文件树': 'workbench.action.chat.nextFileTree',
    '聊天: 新建聊天': 'workbench.action.chat.newChat',
    '聊天: 在编辑器中应用': 'workbench.action.chat.applyInEditor',
    '聊天: 在光标处插入': 'workbench.action.chat.insertCodeBlock',
    '内联聊天: 编辑器内联聊天': 'inlineChat.start',
    '内联聊天: 焦点终端输入': 'workbench.action.terminal.chat.focusInput',
    '内联聊天: 焦点终端响应': 'workbench.action.terminal.chat.focusResponse',
    '内联聊天: 接受更改': 'inlineChat.acceptChanges',
    '内联聊天: 聚焦输入': 'inlineChat.focus',
    '内联聊天: 移动到上一个更改': 'inlineChat.moveToPreviousHunk',
    '内联聊天: 移动到下一个更改': 'inlineChat.moveToNextHunk',
    '内联聊天: 在终端中启动': 'workbench.action.terminal.chat.start',
    启动链接编辑: 'editor.action.linkedEditing',
    前进: 'workbench.action.navigateForward',
    '切换 Tab 键移动焦点': 'editor.action.toggleTabFocusMode',
    '切换垂直/水平编辑器布局': 'workbench.action.toggleEditorGroupLayout',
    切换块注释: 'editor.action.blockComment',
    切换屏幕阅读器辅助功能模式: 'editor.action.toggleScreenReaderAccessibilityMode',
    切换行注释: 'editor.action.commentLine',
    切换折叠: 'editor.toggleFold',
    取消选择定位点: 'editor.action.cancelSelectionAnchor',
    全部展开: 'editor.unfoldAll',
    全部折叠: 'editor.foldAll',
    '任务: 运行生成任务': 'workbench.action.tasks.build',
    删除括号: 'editor.action.removeBrackets',
    删除手动折叠范围: 'editor.removeManualFoldingRanges',
    删除行: 'editor.action.deleteLines',
    删除行注释: 'editor.action.removeCommentLine',
    设置单元格格式: 'notebook.formatCell',
    设置选择定位点: 'editor.action.setSelectionAnchor',
    使用独立颜色选取器插入颜色: 'editor.action.insertColorWithStandaloneColorPicker',
    收起选择: 'editor.action.smartSelect.shrink',
    '首选项: 打开键盘快捷方式': 'workbench.action.openGlobalKeybindings',
    '首选项: 将焦点上移一级': 'settings.action.focusLevelUp',
    '首选项: 聚焦到设置目录': 'settings.action.focusTOC',
    '首选项: 聚焦到设置搜索': 'settings.action.search',
    '首选项: 清除设置搜索结果': 'settings.action.clearSearchResults',
    '首选项: 显示设置上下文菜单': 'settings.action.showContextMenu',
    '首选项: 颜色主题': 'workbench.action.selectTheme',
    '搜索: 聚焦到上一搜索结果': 'search.action.focusPreviousSearchResult',
    '搜索: 聚焦下一搜索结果': 'search.action.focusNextSearchResult',
    '搜索: 取消搜索': 'search.action.cancel',
    '搜索: 在文件中查找': 'workbench.action.findInFiles',
    '搜索: 在文件中替换': 'workbench.action.replaceInFiles',
    '搜索编辑器: 减少上下文行': 'decreaseSearchEditorContextLines',
    '搜索编辑器: 聚焦搜索编辑器输入': 'search.action.focusQueryEditorWidget',
    '搜索编辑器: 切换匹配大小写': 'toggleSearchEditorCaseSensitive',
    '搜索编辑器: 切换全字匹配': 'toggleSearchEditorWholeWord',
    '搜索编辑器: 切换上下文行': 'toggleSearchEditorContextLines',
    '搜索编辑器: 切换使用正则表达式': 'toggleSearchEditorRegex',
    '搜索编辑器: 删除文件结果': 'search.searchEditor.action.deleteFileResults',
    '搜索编辑器: 选择所有匹配项': 'selectAllSearchEditorMatches',
    '搜索编辑器: 再次搜索': 'rerunSearchEditorSearch',
    '搜索编辑器: 在编辑器中打开结果': 'search.action.openInEditor',
    '搜索编辑器: 增加上下文行': 'increaseSearchEditorContextLines',
    速览调用层次结构: 'editor.showCallHierarchy',
    速览定义: 'editor.action.peekDefinition',
    替换: 'editor.action.startFindReplaceAction',
    替换为上一个值: 'editor.action.inPlaceReplace.up',
    替换为下一个值: 'editor.action.inPlaceReplace.down',
    添加行注释: 'editor.action.addCommentLine',
    跳转到下一个内联编辑: 'editor.action.inlineSuggest.jump',
    停止内嵌提示读取: 'inlayHints.stopReadingLineWithHint',
    '通知: 接受通知主要操作': 'notification.acceptPrimaryAction',
    '通知: 显示通知': 'notifications.showList',
    '通知: 隐藏通知': 'notifications.hideList',
    '文件: 按外观显示所有编辑器': 'workbench.action.showAllEditors',
    '文件: 保存': 'workbench.action.files.save',
    '文件: 保存但不格式化': 'workbench.action.files.saveWithoutFormatting',
    '文件: 比较活动文件与剪贴板': 'workbench.files.action.compareWithClipboard',
    '文件: 比较活动与已保存的文件': 'workbench.files.action.compareWithSaved',
    '文件: 打开...': 'workbench.action.files.openFileFolder',
    '文件: 打开文件...': 'workbench.action.files.openFile',
    '文件: 打开文件夹...': 'workbench.action.files.openFolderViaWorkspace',
    '文件: 打开最近的文件…': 'workbench.action.openRecent',
    '文件: 复制活动文件的路径': 'copyFilePath',
    '文件: 复制活动文件的相对路径': 'copyRelativeFilePath',
    '文件: 另存为...': 'workbench.action.files.saveAs',
    '文件: 新的无标题文本文件': 'workbench.action.files.newUntitledFile',
    '文件: 在文件资源管理器中显示': 'revealFileInOS',
    显示编辑器上下文菜单: 'editor.action.showContextMenu',
    显示或聚焦悬停: 'editor.action.showHover',
    显示上一个更改: 'editor.action.dirtydiff.previous',
    显示上一个内联建议: 'editor.action.inlineSuggest.showPrevious',
    显示所有命令: 'workbench.action.showCommands',
    显示下一个更改: 'editor.action.dirtydiff.next',
    显示下一个内联建议: 'editor.action.inlineSuggest.showNext',
    向上翻页悬停: 'editor.action.pageUpHover',
    向上复制行: 'editor.action.copyLinesUpAction',
    向上滚动悬停: 'editor.action.scrollUpHover',
    向上移动行: 'editor.action.moveLinesUpAction',
    向下翻页悬停: 'editor.action.pageDownHover',
    向下复制行: 'editor.action.copyLinesDownAction',
    向下滚动悬停: 'editor.action.scrollDownHover',
    向下移动行: 'editor.action.moveLinesDownAction',
    向右滚动悬停: 'editor.action.scrollRightHover',
    向左滚动悬停: 'editor.action.scrollLeftHover',
    新建窗口: 'workbench.action.newWindow',
    行减少缩进: 'editor.action.outdentLines',
    行缩进: 'editor.action.indentLines',
    选择从定位点到光标: 'editor.action.selectFromAnchorToCursor',
    选择全部: 'editor.action.selectAll',
    选择所有找到的查找匹配项: 'editor.action.selectHighlights',
    以递归方式切换折叠: 'editor.toggleFoldRecursively',
    以递归方式展开: 'editor.unfoldRecursively',
    以递归方式折叠: 'editor.foldRecursively',
    '引用: 查找所有引用': 'references-view.findReferences',
    隐藏内联建议: 'editor.action.inlineSuggest.hide',
    隐藏颜色选取器: 'editor.action.hideColorPicker',
    '语音: 在编辑器中启动听写': 'workbench.action.editorDictation.start',
    '语音: 在编辑器中停止听写': 'workbench.action.editorDictation.stop',
    '远程: 显示远程菜单': 'workbench.action.remote.showMenu',
    在辅助视图中显示上一个: 'editor.action.accessibleViewPrevious',
    在辅助视图中显示下一个: 'editor.action.accessibleViewNext',
    在上面插入行: 'editor.action.insertLineBefore',
    在上面添加光标: 'editor.action.insertCursorAbove',
    在下面插入行: 'editor.action.insertLineAfter',
    在下面添加光标: 'editor.action.insertCursorBelow',
    在行尾添加光标: 'editor.action.insertCursorAtEndOfEachLineSelected',
    粘贴: 'editor.action.clipboardPasteAction',
    展开: 'editor.unfold',
    展开除所选区域之外的所有区域: 'editor.unfoldAllExcept',
    展开所有区域: 'editor.unfoldAllMarkerRegions',
    展开行选择: 'expandLineSelection',
    展开选择: 'editor.action.smartSelect.expand',
    折叠: 'editor.fold',
    折叠除选定项以外的所有项: 'editor.foldAllExcept',
    '折叠级别 1': 'editor.foldLevel1',
    '折叠级别 2': 'editor.foldLevel2',
    '折叠级别 3': 'editor.foldLevel3',
    '折叠级别 4': 'editor.foldLevel4',
    '折叠级别 5': 'editor.foldLevel5',
    '折叠级别 6': 'editor.foldLevel6',
    '折叠级别 7': 'editor.foldLevel7',
    折叠所有块注释: 'editor.foldAllBlockComments',
    折叠所有区域: 'editor.foldAllMarkerRegions',
    '整理 import 语句': 'editor.action.organizeImports',
    '终端: 插入第一个聊天命令': 'workbench.action.terminal.chat.insertFirstCommand',
    '终端: 插入聊天命令': 'workbench.action.terminal.chat.insertCommand',
    '终端: 查找上一个': 'workbench.action.terminal.findPrevious',
    '终端: 查找下一个': 'workbench.action.terminal.findNext',
    '终端: 拆分终端': 'workbench.action.terminal.split',
    '终端: 创建新的终端': 'workbench.action.terminal.new',
    '终端: 打开检测到的链接...': 'workbench.action.terminal.openDetectedLink',
    '终端: 发出聊天请求': 'workbench.action.terminal.chat.makeRequest',
    '终端: 复制和清除选择': 'workbench.action.terminal.copyAndClearSelection',
    '终端: 复制所选内容': 'workbench.action.terminal.copySelection',
    '终端: 关闭聊天': 'workbench.action.terminal.chat.close',
    '终端: 滚动到底部': 'workbench.action.terminal.scrollToBottom',
    '终端: 滚动到底部的可访问视图': 'workbench.action.terminal.scrollToBottomAccessibleView',
    '终端: 滚动到顶部': 'workbench.action.terminal.scrollToTop',
    '终端: 滚动到顶部的可访问视图': 'workbench.action.terminal.scrollToTopAccessibleView',
    '终端: 滚动到上一条命令': 'workbench.action.terminal.scrollToPreviousCommand',
    '终端: 滚动到下一条命令': 'workbench.action.terminal.scrollToNextCommand',
    '终端: 将大小切换为内容宽度': 'workbench.action.terminal.sizeToContentWidth',
    '终端: 焦点终端选项卡视图': 'workbench.action.terminal.focusTabs',
    '终端: 聚焦查找': 'workbench.action.terminal.focusFind',
    '终端: 聚焦到终端': 'workbench.action.terminal.focus',
    '终端: 聚焦上一终端组': 'workbench.action.terminal.focusPrevious',
    '终端: 聚焦下一终端组': 'workbench.action.terminal.focusNext',
    '终端: 聚焦悬停': 'workbench.action.terminal.focusHover',
    '终端: 可访问的缓冲区转到上一命令': 'workbench.action.terminal.accessibleBufferGoToPreviousCommand',
    '终端: 可访问的缓冲区转到下一命令': 'workbench.action.terminal.accessibleBufferGoToNextCommand',
    '终端: 历史记录中的上一个': 'workbench.action.terminal.chat.previousFromHistory',
    '终端: 历史记录中的下一个': 'workbench.action.terminal.chat.nextFromHistory',
    '终端: 聊天命令': 'workbench.action.terminal.chat.runCommand',
    '终端: 切换使用区分大小写进行查找': 'workbench.action.terminal.toggleFindCaseSensitive',
    '终端: 切换使用全字匹配进行查找': 'workbench.action.terminal.toggleFindWholeWord',
    '终端: 切换使用正则表达式进行查找': 'workbench.action.terminal.toggleFindRegex',
    '终端: 取消选择': 'workbench.action.terminal.clearSelection',
    '终端: 搜索工作区': 'workbench.action.terminal.searchWorkspace',
    '终端: 显示终端快速修复': 'workbench.action.terminal.showQuickFixes',
    '终端: 向上滚动(行)': 'workbench.action.terminal.scrollUp',
    '终端: 向上滚动(页)': 'workbench.action.terminal.scrollUpPage',
    '终端: 向下滚动(行)': 'workbench.action.terminal.scrollDown',
    '终端: 向下滚动(页)': 'workbench.action.terminal.scrollDownPage',
    '终端: 选择上一条命令所有内容': 'workbench.action.terminal.selectToPreviousCommand',
    '终端: 选择下一条命令所有内容': 'workbench.action.terminal.selectToNextCommand',
    '终端: 隐藏查找': 'workbench.action.terminal.hideFind',
    '终端: 运行第一个聊天命令': 'workbench.action.terminal.chat.runFirstCommand',
    '终端: 运行最近使用的命令...': 'workbench.action.terminal.runRecentCommand',
    '终端: 在终端组中聚焦上一终端': 'workbench.action.terminal.focusPreviousPane',
    '终端: 在终端组中聚焦下一终端': 'workbench.action.terminal.focusNextPane',
    '终端: 粘贴到活动终端中': 'workbench.action.terminal.paste',
    '终端: 终止编辑器区域中的活动终端': 'workbench.action.terminal.killEditor',
    '终端: 转到“最近使用的目录”...': 'workbench.action.terminal.goToRecentDirectory',
    '重构...': 'editor.action.refactor',
    重命名符号: 'editor.action.rename',
    '注释: 转到上一个注释范围': 'editor.action.previousCommentedRangeAction',
    '注释: 转到下一个注释范围': 'editor.action.nextCommentedRangeAction',
    '转到编辑器中的符号...': 'workbench.action.gotoSymbol',
    转到底部悬停: 'editor.action.goToBottomHover',
    转到顶部悬停: 'editor.action.goToTopHover',
    转到定义: 'editor.action.revealDefinition',
    '转到工作区中的符号...': 'workbench.action.showAllSymbols',
    转到括号: 'editor.action.jumpToBracket',
    转到上一编辑位置: 'workbench.action.navigateToLastEditLocation',
    转到上一个更改: 'workbench.action.compareEditor.previousChange',
    转到上一个突出显示的符号: 'editor.action.wordHighlight.prev',
    '转到上一个问题 (错误、警告、信息)': 'editor.action.marker.prev',
    转到上一个引用: 'references-view.prev',
    转到实现: 'editor.action.goToImplementation',
    '转到文件...': 'workbench.action.quickOpen',
    '转到文件中的上一个问题 (错误、警告、信息)': 'editor.action.marker.prevInFiles',
    '转到文件中的下一个问题 (错误、警告、信息)': 'editor.action.marker.nextInFiles',
    转到下一个更改: 'workbench.action.compareEditor.nextChange',
    转到下一个突出显示的符号: 'editor.action.wordHighlight.next',
    '转到下一个问题 (错误、警告、信息)': 'editor.action.marker.next',
    转到下一个引用: 'references-view.next',
    '转到行/列...': 'workbench.action.gotoLine',
    转到引用: 'editor.action.goToReferences',
    转动辅助视图中的符号: 'editor.action.accessibleViewGoToSymbol',
    '资源管理器: 焦点在 打开的编辑器 视图上': 'workbench.files.action.focusOpenEditorsView',
    '自动修复...': 'editor.action.autoFix',
    'Accept Inline Edit': 'editor.action.inlineEdit.accept',
    'Calls: 显示调用层次结构': 'references-view.showCallHierarchy',
    'Comments: 添加对当前所选内容的注释': 'workbench.action.addComment',
    'Comments: 转到上一个注释范围': 'editor.action.previousCommentingRange',
    'Comments: 转到下一注释范围': 'editor.action.nextCommentingRange',
    'Debug: 开始调试并在输入时停止': 'extension.node-debug.startWithStopOnEntry',
    'Emmet: 展开缩写': 'editor.emmet.action.expandAbbreviation',
    'Git: 还原所选更改': 'git.revertSelectedRanges',
    'Git: 取消暂存所选范围': 'git.unstageSelectedRanges',
    'Git: 暂存所选范围': 'git.stageSelectedRanges',
    'Jump Back from Inline Edit': 'editor.action.inlineEdit.jumpBack',
    'Jump to Inline Edit': 'editor.action.inlineEdit.jumpTo',
    'Jupyter: 按上面的单元格扩展选择': 'jupyter.extendSelectionByCellAbove',
    'Jupyter: 按下面的单元格扩展所选内容': 'jupyter.extendSelectionByCellBelow',
    'Jupyter: 按行运行': 'jupyter.runByLine',
    'Jupyter: 调试单元格': 'jupyter.runAndDebugCell',
    'Jupyter: 继续执行': 'jupyter.runByLineStop',
    'Jupyter: 将单元格更改为 Markdown': 'jupyter.changeCellToMarkdown',
    'Jupyter: 将单元格更改为代码': 'jupyter.changeCellToCode',
    'Jupyter: 删除所选单元格': 'jupyter.deleteCells',
    'Jupyter: 刷新数据查看器': 'jupyter.refreshDataViewer',
    'Jupyter: 向上移动所选单元格': 'jupyter.moveCellsUp',
    'Jupyter: 向下移动所选单元格': 'jupyter.moveCellsDown',
    'Jupyter: 选择单元格': 'jupyter.selectCell',
    'Jupyter: 选择单元格内容': 'jupyter.selectCellContents',
    'Jupyter: 运行当前单元格': 'jupyter.runcurrentcell',
    'Jupyter: 运行当前单元格并前进': 'jupyter.runcurrentcelladvance',
    'Jupyter: 运行下一行': 'jupyter.runByLineNext',
    'Jupyter: 在交互窗口中运行选择/行': 'jupyter.execSelectionInteractive',
    'Jupyter: 在上方插入单元格': 'jupyter.insertCellAbove',
    'Jupyter: 在位置下方插入单元格': 'jupyter.insertCellBelowPosition',
    'Jupyter: 在下方插入单元格': 'jupyter.insertCellBelow',
    'Jupyter: 转到“下一个单元格”': 'jupyter.gotoNextCellInFile',
    'Jupyter: 转到上一个单元格': 'jupyter.gotoPrevCellInFile',
    'Markdown: 打开侧边预览': 'markdown.showPreviewToSide',
    'Markdown: 打开预览': 'markdown.showPreview',
    'Python: 刷新 TensorBoard': 'python.refreshTensorBoard',
    'Python: 在 Python 终端中运行选择/行': 'python.execSelectionInTerminal',
    'Python: 在 Python REPL 中运行选择/行': 'python.execInREPL',
    'Reject Inline Edit': 'editor.action.inlineEdit.reject',
    'Test: 重新运行失败的测试': 'testing.reRunFailTests',
    'Trigger Inline Edit': 'editor.action.inlineEdit.trigger',
    按降序排列行: 'editor.action.sortLinesDescending',
    按升序排列行: 'editor.action.sortLinesAscending',
    '帮助: 查看许可证': 'workbench.action.openLicenseUrl',
    '帮助: 订阅 VS Code 新闻邮件': 'workbench.action.openNewsletterSignupUrl',
    '帮助: 辅助功能入门': 'workbench.action.getStartedWithAccessibilityFeatures',
    '帮助: 个人资料': 'workbench.profiles.actions.help',
    '帮助: 关于': 'workbench.action.showAboutDialog',
    '帮助: 欢迎': 'workbench.action.openWalkthrough',
    '帮助: 继续扩展二等分': 'extension.bisect.next',
    '帮助: 交互式编辑器操场': 'workbench.action.showInteractivePlayground',
    '帮助: 开始扩展二等分': 'extension.bisect.start',
    '帮助: 列出信号公告': 'accessibility.announcement.help',
    '帮助: 列出信号声音': 'signals.sounds.help',
    '帮助: 排查问题...': 'workbench.action.troubleshootIssue.start',
    '帮助: 视频教程': 'workbench.action.openVideoTutorialsUrl',
    '帮助: 搜索功能请求': 'workbench.action.openRequestFeatureUrl',
    '帮助: 提示与技巧': 'workbench.action.openTipsAndTricksUrl',
    '帮助: 停止扩展二等分': 'extension.bisect.stop',
    '帮助: 停止排查问题': 'workbench.action.troubleshootIssue.stop',
    '帮助: 文档': 'workbench.action.openDocumentationUrl',
    '帮助: 隐私声明': 'workbench.action.openPrivacyStatementUrl',
    '帮助: 在 YouTube 上加入我们': 'workbench.action.openYouTubeUrl',
    '本地历史记录: 查找要还原的条目': 'workbench.action.localHistory.restoreViaPicker',
    '本地历史记录: 创建条目': 'workbench.action.localHistory.create',
    '本地历史记录: 全部删除': 'workbench.action.localHistory.deleteAll',
    '比较: 切换编辑器左右端': 'workbench.action.compareEditor.swapSides',
    '比较: 切换内联视图': 'toggle.diff.renderSideBySide',
    '笔记本: 保存 Mimetype 显示顺序': 'notebook.saveMimeTypeOrder',
    '笔记本: 呈现所有 Markdown 单元格': 'notebook.renderAllMarkdownCells',
    '笔记本: 更改单元格语言': 'notebook.cell.changeLanguage',
    '笔记本: 联接所选单元格': 'notebook.cell.joinSelected',
    '笔记本: 清除所有输出': 'notebook.clearAllCellsOutputs',
    '笔记本: 全部运行': 'notebook.execute',
    '笔记本: 停止单元格执行': 'notebook.cell.cancelExecution',
    '笔记本: 停止执行': 'notebook.cancelExecution',
    '笔记本: 选择缩进': 'notebook.selectIndentation',
    '笔记本: 在笔记本布局之间选择': 'workbench.notebook.layout.select',
    '笔记本: 在上方插入 Markdown 单元格': 'notebook.cell.insertMarkdownCellAbove',
    '笔记本: 在下方插入 Markdown 单元格': 'notebook.cell.insertMarkdownCellBelow',
    '笔记本: 展开所有单元格输出': 'notebook.cell.expandAllCellOutputs',
    '笔记本: 展开所有单元格输入': 'notebook.cell.expandAllCellInputs',
    '笔记本: 折叠所有单元格输出': 'notebook.cell.collapseAllCellOutputs',
    '笔记本: 折叠所有单元格输入': 'notebook.cell.collapseAllCellInputs',
    '笔记本: 执行单元格及以下': 'notebook.cell.executeCellAndBelow',
    '笔记本: 执行上方所有的单元格': 'notebook.cell.executeCellsAbove',
    '笔记本: 中断': 'notebook.interruptExecution',
    '笔记本: 转到正在运行的单元格': 'notebook.revealRunningCell',
    '笔记本: 转到最近失败的单元格': 'notebook.revealLastFailedCell',
    '笔记本: 自定义笔记本布局': 'workbench.notebook.layout.configure',
    '编辑 XHR/提取断点': 'extension.js-debug.editXHRBreakpoints',
    '编辑位置中的“返回”': 'workbench.action.navigateBackInEditLocations',
    '编辑位置中的“前进”': 'workbench.action.navigateForwardInEditLocations',
    '编辑位置中的“转到上一页”': 'workbench.action.navigatePreviousInEditLocations',
    '测试: 按测试筛选覆盖率': 'testing.coverageFilterToTest',
    '测试: 测试覆盖率工具栏': 'testing.coverageToggleToolbar',
    '测试: 打开覆盖率文件': 'testing.openCoverage',
    '测试: 焦点在 测试覆盖率 视图上': 'workbench.view.testCoverage.focus',
    '测试: 焦点在 测试资源管理器 视图上': 'workbench.view.testing.focus',
    '测试: 配置测试配置文件': 'testing.configureProfile',
    '测试: 启动连续运行': 'testing.startContinuousRun',
    '测试: 清除覆盖率': 'testing.coverage.close',
    '测试: 清除所有结果': 'testing.clearTestResults',
    '测试: 取消测试刷新': 'testing.cancelTestRefresh',
    '测试: 速览相关测试': 'testing.peekRelatedTest',
    '测试: 速览相关代码': 'testing.peekRelatedCode',
    '测试: 停止连续运行': 'testing.stopContinuousRun',
    '测试: 转到“相关测试”': 'testing.goToRelatedTest',
    '测试: 转到“相关代码”': 'testing.goToRelatedCode',
    '测试结果: 焦点在 测试结果 视图上': 'workbench.panel.testResults.view.focus',
    '查看: 2x2 网格编辑器布局': 'workbench.action.editorLayoutTwoByTwoGrid',
    '查看: 按最近使用显示活动组中的编辑器': 'workbench.action.showEditorsInActiveGroup',
    '查看: 按最近使用显示所有编辑器': 'workbench.action.showAllEditorsByMostRecentlyUsed',
    '查看: 打开上一个最近使用的编辑器': 'workbench.action.openPreviousRecentlyUsedEditor',
    '查看: 打开视图': 'workbench.action.openView',
    '查看: 打开下一个最近使用的编辑器': 'workbench.action.openNextRecentlyUsedEditor',
    '查看: 打开组中的第一个编辑器': 'workbench.action.firstEditorInGroup',
    '查看: 打开组中上一个最近使用的编辑器': 'workbench.action.openPreviousRecentlyUsedEditorInGroup',
    '查看: 打开组中下一个最近使用的编辑器': 'workbench.action.openNextRecentlyUsedEditorInGroup',
    '查看: 单列编辑器布局': 'workbench.action.editorLayoutSingle',
    '查看: 导航到上方视图': 'workbench.action.navigateUp',
    '查看: 导航到下方视图': 'workbench.action.navigateDown',
    '查看: 导航到右侧视图': 'workbench.action.navigateRight',
    '查看: 导航到左侧视图': 'workbench.action.navigateLeft',
    '查看: 底部双列编辑器布局': 'workbench.action.editorLayoutTwoColumnsBottom',
    '查看: 分离已固定编辑器选项卡': 'workbench.action.toggleSeparatePinnedEditorTabs',
    '查看: 关闭编辑器组': 'workbench.action.closeEditorsAndGroup',
    '查看: 关闭固定的编辑器': 'workbench.action.closeActivePinnedEditor',
    '查看: 关闭其他组中的编辑器': 'workbench.action.closeEditorsInOtherGroups',
    '查看: 关闭主侧栏': 'workbench.action.closeSidebar',
    '查看: 关闭组中其他编辑器': 'workbench.action.closeOtherEditors',
    '查看: 关闭组中右侧编辑器': 'workbench.action.closeEditorsToTheRight',
    '查看: 关闭组中左侧编辑器': 'workbench.action.closeEditorsToTheLeft',
    '查看: 还原并关闭编辑器': 'workbench.action.revertAndCloseActiveEditor',
    '查看: 合并所有编辑器组': 'workbench.action.joinAllGroups',
    '查看: 将编辑器操作移动到标题栏': 'workbench.action.editorActionsTitleBar',
    '查看: 将编辑器操作移动到选项卡栏': 'workbench.action.editorActionsDefault',
    '查看: 将编辑器拆分为第一组': 'workbench.action.splitEditorToFirstGroup',
    '查看: 将编辑器拆分为上述组': 'workbench.action.splitEditorToAboveGroup',
    '查看: 将编辑器拆分为上一组': 'workbench.action.splitEditorToPreviousGroup',
    '查看: 将编辑器拆分为下一组': 'workbench.action.splitEditorToNextGroup',
    '查看: 将编辑器拆分为以下组': 'workbench.action.splitEditorToBelowGroup',
    '查看: 将编辑器拆分为右组': 'workbench.action.splitEditorToRightGroup',
    '查看: 将编辑器拆分为最后一个组': 'workbench.action.splitEditorToLastGroup',
    '查看: 将编辑器拆分为左组': 'workbench.action.splitEditorToLeftGroup',
    '查看: 将编辑器还原到主窗口': 'workbench.action.restoreEditorsToMainWindow',
    '查看: 将编辑器移动到上述组': 'workbench.action.moveEditorToAboveGroup',
    '查看: 将编辑器移动到新窗口': 'workbench.action.moveEditorToNewWindow',
    '查看: 将编辑器移动到以下组': 'workbench.action.moveEditorToBelowGroup',
    '查看: 将编辑器移动到右侧组': 'workbench.action.moveEditorToRightGroup',
    '查看: 将编辑器移动到左侧组': 'workbench.action.moveEditorToLeftGroup',
    '查看: 将编辑器组复制到新窗口': 'workbench.action.copyEditorGroupToNewWindow',
    '查看: 将编辑器组移动到新窗口': 'workbench.action.moveEditorGroupToNewWindow',
    '查看: 将编辑器组与下一组合并': 'workbench.action.joinTwoGroups',
    '查看: 将辅助侧栏视图移动到面板': 'workbench.action.moveSecondarySideBarToPanel',
    '查看: 将活动栏移动到底部': 'workbench.action.activityBarLocation.bottom',
    '查看: 将活动栏移至侧边': 'workbench.action.activityBarLocation.default',
    '查看: 将活动栏移至顶部': 'workbench.action.activityBarLocation.top',
    '查看: 将焦点放在活动栏上': 'workbench.action.focusActivityBar',
    '查看: 将焦点置于辅助侧栏': 'workbench.action.focusAuxiliaryBar',
    '查看: 将面板对齐方式设置为“右对齐”': 'workbench.action.alignPanelRight',
    '查看: 将面板对齐方式设置为“左对齐”': 'workbench.action.alignPanelLeft',
    '查看: 将面板对齐设置为“居中”': 'workbench.action.alignPanelCenter',
    '查看: 将面板对齐设置为“两端对齐”': 'workbench.action.alignPanelJustify',
    '查看: 将面板视图移动到辅助侧栏': 'workbench.action.movePanelToSecondarySideBar',
    '查看: 将面板移到顶部': 'workbench.action.positionPanelTop',
    '查看: 将面板移至底部': 'workbench.action.positionPanelBottom',
    '查看: 将面板移至右侧': 'workbench.action.positionPanelRight',
    '查看: 将面板移至左侧': 'workbench.action.positionPanelLeft',
    '查看: 焦点标题栏': 'workbench.action.focusTitleBar',
    '查看: 焦点横幅': 'workbench.action.focusBanner',
    '查看: 焦点状态栏': 'workbench.action.focusStatusBar',
    '查看: 解锁编辑器组': 'workbench.action.unlockEditorGroup',
    '查看: 聚焦到活动编辑器组': 'workbench.action.focusActiveEditorGroup',
    '查看: 聚焦到面板中': 'workbench.action.focusPanel',
    '查看: 聚焦到上一组编辑器': 'workbench.action.focusPreviousGroup',
    '查看: 聚焦到问题 (错误、警告、信息)': 'workbench.action.problems.focus',
    '查看: 聚焦到下一组编辑器': 'workbench.action.focusNextGroup',
    '查看: 聚焦到最终组编辑器': 'workbench.action.focusLastEditorGroup',
    '查看: 快速打开上一个最近使用过的编辑器': 'workbench.action.quickOpenPreviousRecentlyUsedEditor',
    '查看: 快速打开最近使用频率最低的编辑器': 'workbench.action.quickOpenLeastRecentlyUsedEditor',
    '查看: 扩展编辑器组并隐藏侧栏': 'workbench.action.minimizeOtherEditorsHideSidebar',
    '查看: 切换 重构预览': 'refactorPreview',
    '查看: 切换 Jupyter': 'workbench.view.extension.jupyter-variables',
    '查看: 切换笔记本粘滞滚动': 'notebook.action.toggleNotebookStickyScroll',
    '查看: 切换编辑器类型': 'workbench.action.toggleEditorType',
    '查看: 切换编辑器区域可见性': 'workbench.action.toggleEditorVisibility',
    '查看: 切换编辑器粘滞滚动': 'editor.action.toggleStickyScroll',
    '查看: 切换编辑器组大小': 'workbench.action.toggleEditorWidths',
    '查看: 切换编辑器组锁定': 'workbench.action.toggleEditorGroupLock',
    '查看: 切换菜单栏': 'workbench.action.toggleMenuBar',
    '查看: 切换呈现空格': 'editor.action.toggleRenderWhitespace',
    '查看: 切换导航路径': 'breadcrumbs.toggle',
    '查看: 切换到迷你地图': 'editor.action.toggleMinimap',
    '查看: 切换居中布局': 'workbench.action.toggleCenteredLayout',
    '查看: 切换控制字符': 'editor.action.toggleRenderControlCharacter',
    '查看: 切换主侧栏位置': 'workbench.action.toggleSidebarPosition',
    '查看: 切换状态栏可见性': 'workbench.action.toggleStatusbarVisibility',
    '查看: 切换组中拆分编辑器的布局': 'workbench.action.toggleSplitEditorInGroupLayout',
    '查看: 切换最大化面板': 'workbench.action.toggleMaximizedPanel',
    '查看: 三列编辑器布局': 'workbench.action.editorLayoutThreeColumns',
    '查看: 三行编辑器布局': 'workbench.action.editorLayoutThreeRows',
    '查看: 上一个面板视图': 'workbench.action.previousPanelView',
    '查看: 上一个主侧栏视图': 'workbench.action.previousSideBarView',
    '查看: 使用文本编辑器重新打开编辑器': 'workbench.action.reopenTextEditor',
    '查看: 双列编辑器布局': 'workbench.action.editorLayoutTwoColumns',
    '查看: 双行编辑器布局': 'workbench.action.editorLayoutTwoRows',
    '查看: 锁定编辑器组': 'workbench.action.lockEditorGroup',
    '查看: 下一个面板视图': 'workbench.action.nextPanelView',
    '查看: 下一个主侧栏视图': 'workbench.action.nextSideBarView',
    '查看: 显示 测试': 'workbench.view.extension.test',
    '查看: 显示 聊天': 'workbench.panel.chatSidebar',
    '查看: 显示 引用': 'workbench.view.extension.references-view',
    '查看: 显示 远程资源管理器': 'workbench.view.remote',
    '查看: 显示 Jupyter': 'workbench.view.extension.jupyter',
    '查看: 显示编辑器操作': 'workbench.action.showEditorActions',
    '查看: 显示单个编辑器选项卡': 'workbench.action.showEditorTab',
    '查看: 显示多个编辑器选项卡': 'workbench.action.showMultipleEditorTabs',
    '查看: 向上复制编辑器组': 'workbench.action.duplicateActiveEditorGroupUp',
    '查看: 向下复制编辑器组': 'workbench.action.duplicateActiveEditorGroupDown',
    '查看: 向右复制编辑器组': 'workbench.action.duplicateActiveEditorGroupRight',
    '查看: 向左复制编辑器组': 'workbench.action.duplicateActiveEditorGroupLeft',
    '查看: 新建空编辑器窗口': 'workbench.action.newEmptyEditorWindow',
    '查看: 移动焦点视图': 'workbench.action.moveFocusedView',
    '查看: 移动视图': 'workbench.action.moveView',
    '查看: 隐藏编辑器操作': 'workbench.action.hideEditorActions',
    '查看: 隐藏编辑器选项卡': 'workbench.action.hideEditorTabs',
    '查看: 隐藏辅助侧栏': 'workbench.action.closeAuxiliaryBar',
    '查看: 隐藏活动栏': 'workbench.action.activityBarLocation.hide',
    '查看: 隐藏面板': 'workbench.action.closePanel',
    '查看: 右侧双行编辑器布局': 'workbench.action.editorLayoutTwoRowsRight',
    '查看: 在编辑器组间进行导航': 'workbench.action.navigateEditorGroups',
    '查看: 在禅模式下显示单个编辑器选项卡': 'workbench.action.zenShowEditorTab',
    '查看: 在禅模式下显示多个编辑器选项卡': 'workbench.action.zenShowMultipleEditorTabs',
    '查看: 在禅模式下隐藏编辑器选项卡': 'workbench.action.zenHideEditorTabs',
    '查看: 在活动编辑器中专注第二侧': 'workbench.action.focusSecondSideEditor',
    '查看: 在活动编辑器中专注第一侧': 'workbench.action.focusFirstSideEditor',
    '查看: 在活动编辑器中专注其他侧': 'workbench.action.focusOtherSideEditor',
    '查看: 在上方新建编辑器组': 'workbench.action.newGroupAbove',
    '查看: 在所有组中关闭此编辑器': 'workbench.action.closeEditorInAllGroups',
    '查看: 在下方新建编辑器组': 'workbench.action.newGroupBelow',
    '查看: 在右侧新建编辑器组': 'workbench.action.newGroupRight',
    '查看: 在组中切换拆分编辑器': 'workbench.action.toggleSplitEditorInGroup',
    '查看: 在左侧新建编辑器组': 'workbench.action.newGroupLeft',
    '查看: 展开编辑器组': 'workbench.action.minimizeOtherEditors',
    '查看: 重新打开编辑器的方式…': 'workbench.action.reopenWithEditor',
    '查看: 重置编辑器组大小': 'workbench.action.evenEditorWidths',
    '查看: 重置焦点视图位置': 'workbench.action.resetFocusedViewLocation',
    '查看: 重置视图位置': 'workbench.action.resetViewLocations',
    '查看: 重置所有菜单': 'menu.resetHiddenStates',
    '查看: 重置语言状态交互计数器': 'editor.inlayHints.Reset',
    '查看: 最大化编辑器组并隐藏侧栏': 'workbench.action.maximizeEditorHideSidebar',
    查看声明: 'editor.action.peekDeclaration',
    查看引用: 'editor.action.referenceSearch.trigger',
    查找选定内容: 'actions.findWithSelection',
    '差异编辑器: 切换侧面': 'diffEditor.switchSide',
    '差异编辑器: 显示所有未更改的区域': 'diffEditor.showAllUnchangedRegions',
    '差异编辑器: 折叠所有未更改的区域': 'diffEditor.collapseAllUnchangedRegions',
    触发符号高亮: 'editor.action.wordHighlight.trigger',
    触发内联建议: 'editor.action.inlineSuggest.trigger',
    从历史记录中快速打开上一个编辑器: 'workbench.action.openPreviousEditorFromHistory',
    从内容中检测缩进方式: 'editor.action.detectIndentation',
    打开: 'npm.openScript',
    '打开“launch.json”': 'workbench.action.debug.configure',
    打开反汇编视图: 'debug.action.openDisassemblyView',
    打开链接: 'editor.action.openLink',
    打开响应正文: 'extension.js-debug.network.openBody',
    '代码片段: 插入片段': 'editor.action.insertSnippet',
    '代码片段: 配置代码片段': 'workbench.action.openSnippets',
    '代码片段: 使用代码片段填充文件': 'workbench.action.populateFileFromSnippet',
    '代码片段: 由代码片段包围...': 'editor.action.surroundWithSnippet',
    单步执行目标: 'editor.debug.action.stepIntoTargets',
    '导航位置中的“返回”': 'workbench.action.navigateBackInNavigationLocations',
    '导航位置中的“前进”': 'workbench.action.navigateForwardInNavigationLocations',
    '导航位置中的“转到上一页”': 'workbench.action.navigatePreviousInNavigationLocations',
    调试: 'npm.debugScript',
    '调试: 编辑断点': 'editor.debug.action.editBreakpoint',
    '调试: 打开已加载脚本...': 'workbench.action.debug.showLoadedScripts',
    '调试: 导航到调用堆栈底部': 'workbench.action.debug.callStackBottom',
    '调试: 导航到调用堆栈顶部': 'workbench.action.debug.callStackTop',
    '调试: 断开连接和暂停': 'workbench.action.debug.disconnectAndSuspend',
    '调试: 复制控制台所有内容': 'repl.action.copyAll',
    '调试: 聚焦到“调试控制台”视图': 'workbench.debug.action.focusRepl',
    '调试: 设置下一语句': 'debug.jumpToCursor',
    '调试: 添加到监视': 'editor.debug.action.selectionToWatch',
    '调试: 添加记录点...': 'editor.debug.action.addLogPoint',
    '调试: 添加配置…': 'debug.addConfiguration',
    '调试: 添加条件断点...': 'editor.debug.action.conditionalBreakpoint',
    '调试: 向上导航调用堆栈': 'workbench.action.debug.callStackUp',
    '调试: 向下导航调用堆栈': 'workbench.action.debug.callStackDown',
    '调试: 选择并开始调试': 'workbench.action.debug.selectandstart',
    '调试: 选择调试会话': 'workbench.action.debug.selectDebugSession',
    '调试: 选择调试控制台': 'workbench.action.debug.selectDebugConsole',
    '调试: 运行到光标处': 'editor.debug.action.runToCursor',
    '调试: 在调试控制台中评估': 'editor.debug.action.selectionToRepl',
    '调试: 终止线程': 'workbench.action.debug.terminateThread',
    '调试: 转到上一个断点': 'editor.debug.action.goToPreviousBreakpoint',
    '调试: 转到下一个断点': 'editor.debug.action.goToNextBreakpoint',
    '调试：添加触发的断点...': 'editor.debug.action.triggerByBreakpoint',
    '调试控制台: 焦点在 调试控制台 视图上': 'workbench.panel.repl.view.focus',
    '端口转发: 显示日志': 'tunnel-forwarding.showLog',
    '端口转发: 重新启动转发系统': 'tunnel-forwarding.restart',
    复制并突出显示语法: 'editor.action.clipboardCopyWithSyntaxHighlightingAction',
    复制路径: 'references-view.copyPath',
    '复制请求 URL': 'extension.js-debug.network.copyUri',
    复制转发的端口地址: 'remote.tunnel.copyAddressCommandPalette',
    '格式化文件（强制）': 'prettier.forceFormatDocument',
    '格式化选定内容的方式...': 'editor.action.formatSelection.multiple',
    '个人资料: 创建临时配置文件': 'workbench.profiles.actions.createTemporaryProfile',
    '个人资料: 打开 默认 配置文件': 'workbench.action.openProfile.默认',
    '个人资料: 导出配置文件...': 'workbench.profiles.actions.exportProfile',
    '个人资料: 将当前配置文件另存为……': 'workbench.profiles.actions.createFromCurrentProfile',
    '个人资料: 删除配置文件...': 'workbench.profiles.actions.deleteProfile',
    '个人资料: 使用配置文件新建窗口...': 'workbench.profiles.actions.newWindowWithProfile',
    '个人资料: 新建配置文件...': 'workbench.profiles.actions.createProfile',
    '个人资料: Switch 配置文件...': 'workbench.profiles.actions.switchProfile',
    更改文件编码: 'workbench.action.editor.changeEncoding',
    更改行尾序列: 'workbench.action.editor.changeEOL',
    更改制表符显示大小: 'editor.action.changeTabDisplaySize',
    '工作区: 打开工作区配置文件': 'workbench.action.openWorkspaceConfigFile',
    '工作区: 管理工作区信任': 'workbench.trust.manage',
    '工作区: 将工作区另存为...': 'workbench.action.saveWorkspaceAs',
    '工作区: 将文件夹从工作区删除…': 'workbench.action.removeRootFolder',
    '工作区: 将文件夹添加到工作区...': 'workbench.action.addRootFolder',
    '工作区: 配置工作区信任设置': 'workbench.trust.configure',
    '工作区: 在新窗口中复制工作区': 'workbench.action.duplicateWorkspaceInNewWindow',
    关闭: 'references-view.removeReferenceItem',
    管理受信任的域: 'workbench.action.manageTrustedDomain',
    光标重做: 'cursorRedo',
    '合并编辑器: 从右侧切换当前冲突': 'merge.toggleActiveConflictInput2',
    '合并编辑器: 从左侧切换当前冲突': 'merge.toggleActiveConflictInput1',
    '合并编辑器: 打开基本文件': 'merge.openBaseEditor',
    '合并编辑器: 将输入 1 与基本值进行比较': 'mergeEditor.compareInput1WithBase',
    '合并编辑器: 将输入 2 与基本值进行比较': 'mergeEditor.compareInput2WithBase',
    '合并编辑器: 接受来自右侧的所有更改': 'merge.acceptAllInput2',
    '合并编辑器: 接受来自左侧的所有更改': 'merge.acceptAllInput1',
    '合并编辑器: 重置“关闭并存在冲突”选项': 'mergeEditor.resetCloseWithConflictsChoice',
    '合并编辑器: 重置结果': 'mergeEditor.resetResultToBaseAndAutoMerge',
    '合并编辑器: 转到上一个未处理的冲突': 'merge.goToPreviousUnhandledConflict',
    '合并编辑器: 转到下一个未处理的冲突': 'merge.goToNextUnhandledConflict',
    '合并编辑器(开发): 从 JSON 打开合并编辑器状态': 'merge.dev.openContentsJson',
    '合并编辑器(开发): 从文件夹加载合并编辑器状态': 'merge.dev.loadContentsFromFolder',
    '合并编辑器(开发): 将合并编辑器状态保存到文件夹': 'merge.dev.saveContentsToFolder',
    '合并编辑器(开发): 将合并编辑器状态复制为 JSON': 'merge.dev.copyContentsJson',
    '合并编辑器(开发): 在临时合并编辑器中打开所选内容': 'merge.dev.openSelectionInTemporaryMergeEditor',
    '合并冲突: 保留两者': 'merge-conflict.accept.both',
    '合并冲突: 比较当前冲突': 'merge-conflict.compare',
    '合并冲突: 采用传入内容': 'merge-conflict.accept.incoming',
    '合并冲突: 采用当前内容': 'merge-conflict.accept.current',
    '合并冲突: 采用选中版本': 'merge-conflict.accept.selection',
    '合并冲突: 全部保留两者': 'merge-conflict.accept.all-both',
    '合并冲突: 全部采用传入版本': 'merge-conflict.accept.all-incoming',
    '合并冲突: 全部采用当前内容': 'merge-conflict.accept.all-current',
    '合并冲突: 上一个冲突': 'merge-conflict.previous',
    '合并冲突: 下一个冲突': 'merge-conflict.next',
    合并行: 'editor.action.joinLines',
    '欢迎: 打开演练...': 'welcome.showAllWalkthroughs',
    获取已配置的包管理器: 'npm.packageManager',
    减小编辑器字号: 'editor.action.fontZoomOut',
    减小当前视图大小: 'workbench.action.decreaseViewSize',
    将焦点放在编辑器粘性滚动上: 'editor.action.focusStickyScroll',
    将上个选择内容移动到上一查找匹配项: 'editor.action.moveSelectionToPreviousFindMatch',
    将缩进转换为空格: 'editor.action.indentationToSpaces',
    将缩进转换为制表符: 'editor.action.indentationToTabs',
    将选择内容添加到上一查找匹配项: 'editor.action.addSelectionToPreviousFindMatch',
    降低编辑器高度: 'workbench.action.decreaseViewHeight',
    降低编辑器宽度: 'workbench.action.decreaseViewWidth',
    降低悬停详细程度级别: 'editor.action.decreaseHoverVerbosityLevel',
    接受内联建议的下一行: 'editor.action.inlineSuggest.acceptNextLine',
    禁用所有断点: 'workbench.debug.viewlet.action.disableAllBreakpoints',
    禁用源映射单步执行: 'extension.js-debug.disableSourceMapStepping',
    禁止突出显示不可见字符: 'editor.action.unicodeHighlight.disableHighlightingOfInvisibleCharacters',
    '禁止突出显示非基本 ASCII 字符': 'editor.action.unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters',
    禁止突出显示歧义字符: 'editor.action.unicodeHighlight.disableHighlightingOfAmbiguousCharacters',
    聚焦上一个光标: 'editor.action.focusPreviousCursor',
    聚焦下一个光标: 'editor.action.focusNextCursor',
    '开发人员: 测量扩展主机延迟': 'editor.action.measureExtHostLatency',
    '开发人员: 打开 URL': 'workbench.action.url.openUrl',
    '开发人员: 打开 Webview 开发人员工具': 'workbench.action.webview.openDeveloperTools',
    '开发人员: 打开进程资源管理器': 'workbench.action.openProcessExplorer',
    '开发人员: 打开扩展日志文件夹': 'workbench.action.openExtensionLogsFolder',
    '开发人员: 打开日志文件夹': 'workbench.action.openLogsFolder',
    '开发人员: 打开用户数据文件夹': 'workbench.action.openUserDataFolder',
    '开发人员: 打印发射器配置文件': 'perf.event.profiling',
    '开发人员: 打印服务跟踪': 'perf.insta.printTraces',
    '开发人员: 打印服务周期': 'perf.insta.printAsyncCycles',
    '开发人员: 调试编辑器 GPU 呈现器': 'editor.action.debugEditorGpuRenderer',
    '开发人员: 记录存储数据库内容': 'workbench.action.logStorage',
    '开发人员: 记录终端会话': 'workbench.action.terminal.recordSession',
    '开发人员: 检查按键映射': 'workbench.action.inspectKeyMappings',
    '开发人员: 检查按键映射(JSON)': 'workbench.action.inspectKeyMappingsJSON',
    '开发人员: 检查笔记本布局': 'notebook.inspectLayout',
    '开发人员: 检查编辑器标记和作用域': 'editor.action.inspectTMScopes',
    '开发人员: 检查上下文键值': 'workbench.action.inspectContextKeys',
    '开发人员: 将当前文件作为发行说明打开': 'developer.showCurrentFileAsReleaseNotes',
    '开发人员: 将数据写入终端': 'workbench.action.terminal.writeDataToTerminal',
    '开发人员: 连接: 触发器重新连接': 'workbench.action.triggerReconnect',
    '开发人员: 连接: 暂停套接字写入': 'workbench.action.pauseSocketWriting',
    '开发人员: 启动 TextMate 语法语法日志记录': 'editor.action.startDebugTextMate',
    '开发人员: 启动性能': 'perfview.show',
    '开发人员: 强制重新进行标记': 'editor.action.forceRetokenize',
    '开发人员: 切换笔记本剪贴板疑难解答': 'workbench.action.toggleNotebookClipboardLog',
    '开发人员: 切换布局疑难解答': 'notebook.toggleLayoutTroubleshoot',
    '开发人员: 切换键盘快捷方式疑难解答': 'workbench.action.toggleKeybindingsLog',
    '开发人员: 切换屏幕模式': 'workbench.action.toggleScreencastMode',
    '开发人员: 清除笔记本编辑器类型缓存': 'notebook.clearNotebookEdtitorTypeCache',
    '开发人员: 清除笔记本内核 MRU 缓存': 'notebook.clearNotebookKernelsMRUCache',
    '开发人员: 清理配置文件': 'workbench.profiles.actions.cleanupProfiles',
    '开发人员: 日志工作副本': 'workbench.action.logWorkingCopies',
    '开发人员: 日志聊天输入历史记录': 'workbench.action.chat.logInputHistory',
    '开发人员: 删除大型存储数据库条目...': 'workbench.action.removeLargeStorageDatabaseEntries',
    '开发人员: 设置日志级别...': 'workbench.action.setLogLevel',
    '开发人员: 使用当前设置生成颜色主题': 'workbench.action.generateColorTheme',
    '开发人员: 停止跟踪': 'workbench.action.stopTracing',
    '开发人员: 下载设置同步活动': 'workbench.userDataSync.actions.downloadSyncActivity',
    '开发人员: 显示正在运行的扩展': 'workbench.action.showRuntimeExtensions',
    '开发人员: 显示终端纹理图集': 'workbench.action.terminal.showTextureAtlas',
    '开发人员: 在禁用扩展的情况下重新加载': 'workbench.action.reloadWindowWithExtensionsDisabled',
    '开发人员: 在新窗口中启动调试扩展主机': 'workbench.extensions.action.debugExtensionHost',
    '开发人员: 重启 pty 主机': 'workbench.action.terminal.restartPtyHost',
    '开发人员: 重启扩展宿主': 'workbench.action.restartExtensionHost',
    '开发人员: 重新加载 Web 视图': 'workbench.action.webview.reloadWebviewAction',
    '开发人员: 重置笔记本入门': 'workbench.notebook.layout.gettingStarted',
    '开发人员: 重置工作区配置文件关联': 'workbench.profiles.actions.resetWorkspaces',
    '开发人员: 重置欢迎页面演练进度': 'resetGettingStartedProgress',
    快速查看类型定义: 'editor.action.peekTypeDefinition',
    '扩展: 管理授权扩展 URI...': 'workbench.extensions.action.manageAuthorizedExtensionURIs',
    '聊天: 插入到新文件中': 'workbench.action.chat.insertIntoNewFile',
    '聊天: 打开编辑器': 'workbench.action.openChat',
    '聊天: 打开快速聊天': 'workbench.action.openQuickChat',
    '聊天: 导出聊天...': 'workbench.action.chat.export',
    '聊天: 导入聊天...': 'workbench.action.chat.import',
    '聊天: 焦点在 GitHub Copilot 视图上': 'workbench.panel.chat.view.copilot.focus',
    '聊天: 开始编辑会话': 'chatEditing.startSession',
    '聊天: 快速语音聊天': 'workbench.action.chat.quickVoiceChat',
    '聊天: 聊天视图中的语音聊天': 'workbench.action.chat.voiceChatInChatView',
    '聊天: 内联语音聊天': 'workbench.action.chat.inlineVoiceChat',
    '聊天: 清除输入历史记录': 'workbench.action.chat.clearInputHistory',
    '聊天: 清除所有工作区聊天': 'workbench.action.chat.clearHistory',
    '聊天: 停止编辑会话': 'chatEditing.stopSession',
    '聊天: 显示聊天...': 'workbench.action.chat.history',
    '聊天: 应用所有编辑': 'workbench.action.chat.applyAll',
    '聊天: 在编辑器中打开聊天': 'workbench.action.chat.openInEditor',
    '聊天: 在侧边栏中打开聊天': 'workbench.action.chat.openInSidebar',
    '聊天: 在新窗口中打开聊天': 'workbench.action.chat.openInNewWindow',
    '列表: 调整列大小': 'list.resizeColumn',
    '内联聊天: 接受并运行': 'notebook.inlineChat.acceptChangesAndRun',
    '内联聊天: 配置内联聊天': 'inlineChat.configure',
    '内联聊天: 在编辑器中从当前行开始': 'inlineChat.startWithCurrentLine',
    启用所有断点: 'workbench.debug.viewlet.action.enableAllBreakpoints',
    启用源映射单步执行: 'extension.js-debug.enableSourceMapStepping',
    '切换窗口...': 'workbench.action.switchWindow',
    切换导入折叠: 'editor.toggleImportFold',
    切换多行修改键: 'workbench.action.toggleMultiCursorModifier',
    切换激活断点: 'workbench.debug.viewlet.action.toggleBreakpointsActivatedAction',
    切换列选择模式: 'editor.action.toggleColumnSelection',
    切换事件侦听器断点: 'extension.js-debug.addCustomBreakpoints',
    清除编辑器历史记录: 'workbench.action.clearEditorHistory',
    清除控制台: 'workbench.debug.panel.action.clearReplAction',
    清除命令历史记录: 'workbench.action.clearCommandHistory',
    清除网络日志: 'extension.js-debug.network.clear',
    清理无效图像附件引用: 'ipynb.cleanInvalidImageAttachment',
    取消: 'references-view.removeCallItem',
    全部保存: 'workbench.action.files.saveAll',
    全部复制: 'references-view.copyAll',
    全部修复: 'editor.action.fixAll',
    '任务: 打开工作区任务': 'workbench.action.tasks.openWorkspaceFileTasks',
    '任务: 打开用户任务': 'workbench.action.tasks.openUserTasks',
    '任务: 管理自动任务': 'workbench.action.tasks.manageAutomaticRunning',
    '任务: 配置默认测试任务': 'workbench.action.tasks.configureDefaultTestTask',
    '任务: 配置默认生成任务': 'workbench.action.tasks.configureDefaultBuildTask',
    '任务: 配置任务': 'workbench.action.tasks.configureTaskRunner',
    '任务: 显示任务日志': 'workbench.action.tasks.showLog',
    '任务: 显示运行中的任务': 'workbench.action.tasks.showTasks',
    '任务: 运行测试任务': 'workbench.action.tasks.test',
    '任务: 运行任务': 'workbench.action.tasks.runTask',
    '任务: 终止任务': 'workbench.action.tasks.terminate',
    '任务: 重启正在运行的任务': 'workbench.action.tasks.restartTask',
    '任务: 重新运行上一个任务': 'workbench.action.tasks.reRunTask',
    '删除 Word': 'deleteInsideWord',
    '删除 XHR/提取断点': 'extension.js-debug.removeXHRBreakpoint',
    删除所有断点: 'workbench.debug.viewlet.action.removeAllBreakpoints',
    删除所有排除的调用方: 'extension.js-debug.callers.removeAll',
    删除右侧所有内容: 'deleteAllRight',
    删除重复行: 'editor.action.removeDuplicateLines',
    删除左侧所有内容: 'deleteAllLeft',
    '设置同步: 打开本地备份文件夹': 'workbench.userData.actions.openSyncBackupsFolder',
    设置修改过的行的格式: 'editor.action.formatChanges',
    '使用...格式化文档': 'editor.action.formatDocument.multiple',
    使用参数查找: 'editor.actions.findWithArgs',
    使用空格缩进: 'editor.action.indentUsingSpaces',
    使用内联提示读取行: 'inlayHints.startReadingLineWithHint',
    使用制表符缩进: 'editor.action.indentUsingTabs',
    '首选项: 产品图标主题': 'workbench.action.selectProductIconTheme',
    '首选项: 打开辅助功能设置': 'workbench.action.openAccessibilitySettings',
    '首选项: 打开工作区设置': 'workbench.action.openWorkspaceSettings',
    '首选项: 打开工作区设置(JSON)': 'workbench.action.openWorkspaceSettingsFile',
    '首选项: 打开键盘快捷方式(JSON)': 'workbench.action.openGlobalKeybindingsFile',
    '首选项: 打开默认键盘快捷键(JSON)': 'workbench.action.openDefaultKeybindingsFile',
    '首选项: 打开默认设置(JSON)': 'workbench.action.openRawDefaultSettings',
    '首选项: 打开配置文件(UI)': 'workbench.profiles.actions.manageProfiles',
    '首选项: 打开设置 (ui)': 'workbench.action.openSettings2',
    '首选项: 打开文件夹设置': 'workbench.action.openFolderSettings',
    '首选项: 打开文件夹设置(JSON)': 'workbench.action.openFolderSettingsFile',
    '首选项: 打开应用程序设置(JSON)': 'workbench.action.openApplicationSettingsJson',
    '首选项: 打开用户设置': 'workbench.action.openGlobalSettings',
    '首选项: 打开用户设置(JSON)': 'workbench.action.openSettingsJson',
    '首选项: 配置语言特定的设置...': 'workbench.action.configureLanguageBasedSettings',
    '首选项: 配置运行时参数': 'workbench.action.configureRuntimeArguments',
    '首选项: 清除键盘快捷方式搜索历史记录': 'keybindings.editor.clearSearchHistory',
    '首选项: 文件图标主题': 'workbench.action.selectIconTheme',
    '首选项: 在浅色/深色主题之间切换': 'workbench.action.toggleLightDarkThemes',
    '首选项: 在市场中浏览颜色主题': 'workbench.action.browseColorThemesInMarketplace',
    '输出: 焦点在 输出 视图上': 'workbench.panel.output.focus',
    刷新: 'npm.refresh',
    刷新资源管理器: 'workbench.files.action.refreshFilesExplorer',
    '搜索: 焦点在 搜索 视图上': 'workbench.view.search.focus',
    '搜索: 聚焦到列表': 'search.action.focusSearchList',
    '搜索: 快速搜索': 'workbench.action.quickTextSearch',
    '搜索: 清除搜索结果': 'search.action.clearSearchResults',
    '搜索: 清除搜索历史记录': 'search.action.clearHistory',
    '搜索: 全部展开': 'search.action.expandSearchResults',
    '搜索: 全部折叠': 'search.action.collapseSearchResults',
    '搜索: 刷新': 'search.action.refreshSearchResults',
    '搜索: 以列表形式查看': 'search.action.viewAsList',
    '搜索: 以树形式查看': 'search.action.viewAsTree',
    '搜索编辑器: 打开侧边的新搜索编辑器': 'search.action.openNewEditorToSide',
    '搜索编辑器: 打开搜索编辑器': 'search.action.openEditor',
    '搜索编辑器: 新的搜索编辑器': 'search.action.openNewEditor',
    '搜索编辑器: 要包括的焦点搜索编辑器文件': 'search.action.focusFilesToInclude',
    '搜索编辑器: 要排除的焦点搜索编辑器文件': 'search.action.focusFilesToExclude',
    速览类型层次结构: 'editor.showTypeHierarchy',
    提高悬停详细程度级别: 'editor.action.increaseHoverVerbosityLevel',
    '添加 XHR/提取断点': 'extension.js-debug.addXHRBreakpoints',
    添加函数断点: 'workbench.debug.viewlet.action.addFunctionBreakpointAction',
    跳转到父级折叠: 'editor.gotoParentFold',
    停止转发端口: 'remote.tunnel.closeCommandPalette',
    '通知: 按源切换“请勿打扰”模式...': 'notifications.toggleDoNotDisturbModeBySource',
    '通知: 将焦点放在通知横幅上': 'notifications.focusToasts',
    '通知: 切换“请勿打扰”模式': 'notifications.toggleDoNotDisturbMode',
    '通知: 清除所有通知': 'notifications.clearAll',
    '文件: 保存所有文件': 'workbench.action.files.saveFiles',
    '文件: 比较活动文件与...': 'workbench.files.action.compareFileWith',
    '文件: 比较新的无标题文本文件': 'workbench.files.action.compareNewUntitledTextFiles',
    '文件: 从文件打开工作区...': 'workbench.action.openWorkspace',
    '文件: 还原文件': 'workbench.action.files.revert',
    '文件: 聚焦到“文件资源管理器”视图': 'workbench.files.action.focusFilesExplorer',
    '文件: 切换开关自动保存': 'workbench.action.toggleAutoSave',
    '文件: 清除最近打开的…': 'workbench.action.clearRecentFiles',
    '文件: 全部保存在组中': 'workbench.files.action.saveAllInGroup',
    '文件: 新建文件...': 'explorer.newFile',
    '文件: 新建文件夹...': 'explorer.newFolder',
    '文件: 在会话中切换活动编辑器只读': 'workbench.action.files.toggleActiveEditorReadonlyInSession',
    '文件: 在会话中设置活动编辑器可写': 'workbench.action.files.setActiveEditorWriteableInSession',
    '文件: 在会话中设置活动编辑器只读': 'workbench.action.files.setActiveEditorReadonlyInSession',
    '文件: 在会话中重置活动编辑器只读': 'workbench.action.files.resetActiveEditorReadonlyInSession',
    '文件: 在新的空白工作区中打开活动文件': 'workbench.action.files.showOpenedFileInNewWindow',
    '文件: 在资源管理器视图中显示活动文件': 'workbench.files.action.showActiveFileInExplorer',
    '问题: 焦点在 问题 视图上': 'workbench.panel.markers.view.focus',
    '问题: 在单行中显示消息': 'problems.action.showSinglelineMessage',
    '问题: 在多行中显示消息': 'problems.action.showMultilineMessage',
    '下载 Visual Studio Code': 'workbench.action.download',
    '显示 Emmet 命令': 'workbench.action.showEmmetCommands',
    '显示当前行的 Code Lens 命令': 'codelens.showLensesInCurrentLine',
    显示定义预览悬停: 'editor.action.showDefinitionPreviewHover',
    显示或聚焦独立颜色选取器: 'editor.action.showOrFocusStandaloneColorPicker',
    显示排除选项: 'editor.action.unicodeHighlight.showExcludeOptions',
    显示自定义标题栏: 'showCustomTitleBar',
    向右移动所选文本: 'editor.action.moveCarretRightAction',
    向左移动所选文本: 'editor.action.moveCarretLeftAction',
    选择括号所有内容: 'editor.action.selectToBracket',
    移除排除的调用方: 'extension.js-debug.callers.remove',
    移除所有事件侦听器断点: 'extension.js-debug.removeAllCustomBreakpoints',
    '以 cURL 形式查看请求': 'extension.js-debug.network.viewRequest',
    '引用: 查找所有实现': 'references-view.findImplementations',
    '引用: 焦点在 引用搜索结果 视图上': 'references-view.tree.focus',
    '引用: 清除': 'references-view.clear',
    '引用: 清除历史记录': 'references-view.clearHistory',
    '引用: 刷新': 'references-view.refresh',
    '引用: 显示历史记录': 'references-view.pickFromHistory',
    隐藏自定义标题栏: 'hideCustomTitleBar',
    '源代码操作...': 'editor.action.sourceAction',
    '源代码管理: 焦点在 源代码管理 视图上': 'workbench.scm.focus',
    '源代码管理: 焦点在 源代码管理存储库 视图上': 'workbench.scm.repositories.focus',
    '源代码管理: 焦点在 源代码管理图 视图上': 'workbench.scm.history.focus',
    '远程: 安装远程开发拓展': 'workbench.action.remote.extensions',
    '远程: 关闭远程连接': 'workbench.action.remote.close',
    运行: 'npm.runScript',
    '运行 install': 'npm.runInstall',
    '运行和调试: 焦点在 变量 视图上': 'workbench.debug.action.focusVariablesView',
    '运行和调试: 焦点在 调用堆栈 视图上': 'workbench.debug.action.focusCallStackView',
    '运行和调试: 焦点在 断点 视图上': 'workbench.debug.action.focusBreakpointsView',
    '运行和调试: 焦点在 监视 视图上': 'workbench.debug.action.focusWatchView',
    '运行和调试: 焦点在 已载入的脚本 视图上': 'workbench.debug.loadedScriptsView.focus',
    '运行和调试: 焦点在 运行 视图上': 'workbench.debug.welcome.focus',
    '运行和调试: 焦点在 Event Listener Breakpoints 视图上': 'jsBrowserBreakpoints.focus',
    '运行和调试: 焦点在 Excluded Callers 视图上': 'jsExcludedCallers.focus',
    '运行和调试: 焦点在 Network 视图上': 'jsDebugNetworkTree.focus',
    运行脚本: 'npm.runSelectedScript',
    '运行文件夹中的NPM脚本...': 'npm.runScriptFromFolder',
    '在 Quick Open 中导航到上一个': 'workbench.action.quickOpenNavigatePrevious',
    '在 Quick Open 中导航到下一个': 'workbench.action.quickOpenNavigateNext',
    '在 Quick Open 中选择“上一步”': 'workbench.action.quickOpenSelectPrevious',
    '在 Quick Open 中选择“下一步”': 'workbench.action.quickOpenSelectNext',
    '在笔记本编辑器中打开 IPYNB 文件': 'ipynb.openIpynbInNotebookEditor',
    在地址处添加数据断点: 'workbench.debug.viewlet.action.addDataBreakpointOnAddress',
    在底部添加光标: 'editor.action.addCursorsToBottom',
    在顶部添加光标: 'editor.action.addCursorsToTop',
    在反汇编视图中切换源代码: 'debug.action.toggleDisassemblyViewSourceCode',
    在浏览器中打开端口: 'remote.tunnel.openCommandPalette',
    在全屏模式下隐藏自定义标题栏: 'hideCustomTitleBarInFullScreen',
    在十六进制编辑器中打开响应正文: 'extension.js-debug.network.openBodyInHex',
    在资源管理器中折叠文件夹: 'workbench.files.action.collapseExplorerFolders',
    增大编辑器字号: 'editor.action.fontZoomIn',
    增加编辑器高度: 'workbench.action.increaseViewHeight',
    增加编辑器宽度: 'workbench.action.increaseViewWidth',
    增加当前视图大小: 'workbench.action.increaseViewSize',
    '粘贴为...': 'editor.action.pasteAs',
    粘贴为文本: 'editor.action.pasteAsText',
    展开所有差异: 'multiDiffEditor.expandAll',
    折叠所有差异: 'multiDiffEditor.collapseAll',
    '终端: 拆分终端 (活动工作区)': 'workbench.action.terminal.splitInActiveWorkspace',
    '终端: 拆离会话': 'workbench.action.terminal.detachSession',
    '终端: 创建新终端(具有个人资料)': 'workbench.action.terminal.newWithProfile',
    '终端: 创建新终端(在活动工作区中)': 'workbench.action.terminal.newInActiveWorkspace',
    '终端: 从自定义工作目录开始创建新终端': 'workbench.action.terminal.newWithCwd',
    '终端: 打开最后一个 URL 链接': 'workbench.action.terminal.openUrlLink',
    '终端: 打开最后一个本地文件链接': 'workbench.action.terminal.openFileLink',
    '终端: 放弃': 'workbench.action.terminal.chat.discard',
    '终端: 附加到会话': 'workbench.action.terminal.attachToSession',
    '终端: 复制最后一个命令': 'workbench.action.terminal.copyLastCommand',
    '终端: 复制最后一个命令和输出': 'workbench.action.terminal.copyLastCommandAndLastCommandOutput',
    '终端: 复制最后一个命令输出': 'workbench.action.terminal.copyLastCommandOutput',
    '终端: 更改图标...': 'workbench.action.terminal.changeIcon',
    '终端: 更改颜色...': 'workbench.action.terminal.changeColor',
    '终端: 减小字体号': 'workbench.action.terminal.fontZoomOut',
    '终端: 将所选内容复制为 HTML': 'workbench.action.terminal.copySelectionAsHtml',
    '终端: 将终端移到面板中': 'workbench.action.terminal.moveToTerminalPanel',
    '终端: 将终端移动到编辑器区域中': 'workbench.action.terminal.moveToEditor',
    '终端: 将终端移动到新窗口': 'workbench.action.terminal.moveIntoNewWindow',
    '终端: 焦点在 终端 视图上': 'terminal.focus',
    '终端: 联接终端': 'workbench.action.terminal.joinActiveTab',
    '终端: 联接终端...': 'workbench.action.terminal.join',
    '终端: 配置终端设置': 'workbench.action.terminal.openSettings',
    '终端: 切换活动终端': 'workbench.action.quickOpenTerm',
    '终端: 切换粘滞滚动': 'workbench.action.terminal.toggleStickyScroll',
    '终端: 切换终端': 'workbench.action.terminal.switchTerminal',
    '终端: 清除': 'workbench.action.terminal.clear',
    '终端: 清除建议缓存': 'workbench.action.terminal.clearSuggestCache',
    '终端: 清除上一会话历史记录': 'workbench.action.terminal.clearPreviousSessionHistory',
    '终端: 取消拆分终端': 'workbench.action.terminal.unsplit',
    '终端: 取消聊天': 'workbench.action.terminal.chat.cancel',
    '终端: 设置固定维度': 'workbench.action.terminal.setDimensions',
    '终端: 显示环境贡献': 'workbench.action.terminal.showEnvironmentContributions',
    '终端: 向上重设终端大小': 'workbench.action.terminal.resizePaneUp',
    '终端: 向下重设终端大小': 'workbench.action.terminal.resizePaneDown',
    '终端: 向右重设终端大小': 'workbench.action.terminal.resizePaneRight',
    '终端: 向左重设终端大小': 'workbench.action.terminal.resizePaneLeft',
    '终端: 选择默认配置文件': 'workbench.action.terminal.selectDefaultShell',
    '终端: 选择全部': 'workbench.action.terminal.selectAll',
    '终端: 选择上一行的所有内容': 'workbench.action.terminal.selectToPreviousLine',
    '终端: 选择下一行的所有内容': 'workbench.action.terminal.selectToNextLine',
    '终端: 在编辑器区域内创建新终端': 'workbench.action.createTerminalEditor',
    '终端: 在活动终端运行所选文本': 'workbench.action.terminal.runSelectedText',
    '终端: 在活动终端中运行活动文件': 'workbench.action.terminal.runActiveFile',
    '终端: 在聊天中查看': 'workbench.action.terminal.chat.viewInChat',
    '终端: 在一侧的编辑器区域内创建新终端': 'workbench.action.createTerminalEditorSide',
    '终端: 增大字号': 'workbench.action.terminal.fontZoomIn',
    '终端: 终止活动终端实例': 'workbench.action.terminal.kill',
    '终端: 终止所有终端': 'workbench.action.terminal.killAll',
    '终端: 重命名...': 'workbench.action.terminal.rename',
    '终端: 重命名当前活动终端': 'workbench.action.terminal.renameWithArg',
    '终端: 重新启动活动终端': 'workbench.action.terminal.relaunch',
    '终端: 重置字号': 'workbench.action.terminal.fontZoomReset',
    重播请求: 'extension.js-debug.network.replayXHR',
    重复选择: 'editor.action.duplicateSelection',
    '重构预览: 焦点在 重构预览 视图上': 'refactorPreview.focus',
    重新缩进所选行: 'editor.action.reindentselectedlines',
    重新缩进行: 'editor.action.reindentlines',
    重新应用所有断点: 'workbench.debug.viewlet.action.reapplyBreakpointsAction',
    重新运行: 'references-view.refind',
    重置编辑器字号: 'editor.action.fontZoomReset',
    重置建议小组件大小: 'editor.action.resetSuggestSize',
    '注释: 在当前行上聚焦注释': 'workbench.action.focusCommentOnCurrentLine',
    '转到“匹配”...': 'editor.action.goToMatchFindAction',
    转到调用方位置: 'extension.js-debug.callers.goToCaller',
    转到类型定义: 'editor.action.goToTypeDefinition',
    转到目标位置: 'extension.js-debug.callers.gotToTarget',
    转到上一导航位置: 'workbench.action.navigateToLastNavigationLocation',
    转到上一个折叠范围: 'editor.gotoPreviousFold',
    转到上一页: 'workbench.action.navigateLast',
    转到声明: 'editor.action.revealDeclaration',
    转到下一个折叠范围: 'editor.gotoNextFold',
    转到选择定位点: 'editor.action.goToSelectionAnchor',
    转发端口: 'remote.tunnel.forwardCommandPalette',
    '转换为 Kebab 案例': 'editor.action.transformToKebabcase',
    转换为词首字母大写: 'editor.action.transformToTitlecase',
    转换为大写: 'editor.action.transformToUppercase',
    转换为帕斯卡式大小写形式: 'editor.action.transformToPascalcase',
    转换为蛇形命名法: 'editor.action.transformToSnakecase',
    转换为驼峰式大小写: 'editor.action.transformToCamelcase',
    转换为小写: 'editor.action.transformToLowercase',
    转置光标处的字符: 'editor.action.transpose',
    转置字母: 'editor.action.transposeLetters',
    '资源管理器: 焦点在 大纲 视图上': 'outline.focus',
    '资源管理器: 焦点在 时间线 视图上': 'timeline.focus',
    '资源管理器: 焦点在 文件夹 视图上': 'workbench.explorer.fileView.focus',
    '资源管理器: 焦点在 npm 脚本 视图上': 'npm.focus',
    '自定义布局...': 'workbench.action.customizeLayout',
    'Add Cell Tag': 'jupyter-cell-tags.addTag',
    'Black Formatter: 重启服务器': 'black-formatter.restart',
    'Calls: 显示传出调用': 'references-view.showOutgoingCalls',
    'Calls: 显示传入调用': 'references-view.showIncomingCalls',
    'Clear Profile Code Lenses': 'extension.jsProfileVisualizer.table.clearCodeLenses',
    'Code: 安装更新': 'update.installUpdate',
    'Code: 检查更新...': 'update.checkForUpdate',
    'Code: 下载更新': 'update.downloadUpdate',
    'Code: 显示发行说明': 'update.showCurrentReleaseNotes',
    'Code: 重启以更新': 'update.restartToUpdate',
    'Comments: 切换编辑器注释': 'workbench.action.toggleCommenting',
    'Comments: 展开所有注释': 'workbench.action.expandAllComments',
    'Comments: 展开未解决注释': 'workbench.action.expandUnresolvedComments',
    'Comments: 折叠所有注释': 'workbench.action.collapseAllComments',
    'Copy vscode.dev Link': 'github.copyVscodeDevLink',
    'Create: 新 Jupyter Notebook': 'ipynb.newUntitledIpynb',
    'Debug: 保存诊断 JS 调试日志': 'extension.js-debug.getDiagnosticLogs',
    'Debug: 打开链接': 'extension.js-debug.debugLink',
    'Debug: 打开浏览器开发工具': 'extension.js-debug.openEdgeDevTools',
    'Debug: 调试 npm 脚本': 'extension.js-debug.npmScript',
    'Debug: 附加到 Node 进程': 'extension.pwa-node-debug.attachNodeProcess',
    'Debug: 获取性能配置文件': 'extension.js-debug.startProfile',
    'Debug: 焦点选项卡': 'extension.js-debug.revealPage',
    'Debug: 排除调用方': 'extension.js-debug.callers.add',
    'Debug: 切换开关自动附加': 'extension.node-debug.toggleAutoAttach',
    'Debug: 跳过此文件的开关': 'extension.js-debug.toggleSkippingFile',
    'Debug: 停止性能配置文件': 'extension.js-debug.stopProfile',
    'Debug: 用于调试的美观格式打印': 'extension.js-debug.prettyPrint',
    'Debug: 诊断断点问题': 'extension.js-debug.createDiagnostics',
    'Debug: JavaScript 调试终端': 'extension.js-debug.createDebuggerTerminal',
    'Edit Cell Tags (JSON)': 'jupyter-cell-tags.editTagsInJSON',
    'Edit Slide Type (JSON)': 'jupyter-slideshow.editSlideShowInJSON',
    'Emmet: 分离/联接标记': 'editor.emmet.action.splitJoinTag',
    'Emmet: 更新标记': 'editor.emmet.action.updateTag',
    'Emmet: 更新图像大小': 'editor.emmet.action.updateImageSize',
    'Emmet: 合并行': 'editor.emmet.action.mergeLines',
    'Emmet: 减少 0.1': 'editor.emmet.action.decrementNumberByOneTenth',
    'Emmet: 减少 1': 'editor.emmet.action.decrementNumberByOne',
    'Emmet: 减少 10': 'editor.emmet.action.decrementNumberByTen',
    'Emmet: 平衡(向内)': 'editor.emmet.action.balanceIn',
    'Emmet: 平衡(向外)': 'editor.emmet.action.balanceOut',
    'Emmet: 切换注释': 'editor.emmet.action.toggleComment',
    'Emmet: 求数学表达式的值': 'editor.emmet.action.evaluateMathExpression',
    'Emmet: 删除标记': 'editor.emmet.action.removeTag',
    'Emmet: 使用缩写包围': 'editor.emmet.action.wrapWithAbbreviation',
    'Emmet: 选择上一项': 'editor.emmet.action.selectPrevItem',
    'Emmet: 选择下一项': 'editor.emmet.action.selectNextItem',
    'Emmet: 映射 CSS 值': 'editor.emmet.action.reflectCSSValue',
    'Emmet: 增加 0.1': 'editor.emmet.action.incrementNumberByOneTenth',
    'Emmet: 增加 1': 'editor.emmet.action.incrementNumberByOne',
    'Emmet: 增加 10': 'editor.emmet.action.incrementNumberByTen',
    'Emmet: 转到上一编辑点': 'editor.emmet.action.prevEditPoint',
    'Emmet: 转到下一编辑点': 'editor.emmet.action.nextEditPoint',
    'Emmet: 转至匹配对': 'editor.emmet.action.matchTag',
    'ESLint: Create ESLint configuration': 'eslint.createConfig',
    'ESLint: Fix all auto-fixable Problems': 'eslint.executeAutofix',
    'ESLint: Migrate Settings': 'eslint.migrateSettings',
    'ESLint: Restart ESLint Server': 'eslint.restart',
    'ESLint: Revalidate all open files': 'eslint.revalidate',
    'ESLint: Show Output Channel': 'eslint.showOutputChannel',
    'Git API: 获取仓库状态': 'git.api.getRepositoryState',
    'Git API: 获取存储库': 'git.api.getRepositories',
    'Git API: 获取远程源': 'git.api.getRemoteSources',
    'Git Base API: 获取远程源': 'git-base.api.getRemoteSources',
    'Git: 变基分支…': 'git.rebase',
    'Git: 查看储藏条目...': 'git.stashView',
    'Git: 查看更改': 'git.viewChanges',
    'Git: 查看所有更改': 'git.viewAllChanges',
    'Git: 查看提交': 'git.timeline.viewCommit',
    'Git: 查看未跟踪的更改': 'git.viewUntrackedChanges',
    'Git: 查看暂存的更改': 'git.viewStagedChanges',
    'Git: 撤消上次提交': 'git.undoCommit',
    'Git: 初始化仓库': 'git.init',
    'Git: 储藏': 'git.stash',
    'Git: 储藏(包含未跟踪)': 'git.stashIncludeUntracked',
    'Git: 储藏暂存': 'git.stashStaged',
    'Git: 创建标记...': 'git.createTag',
    'Git: 创建分支...': 'git.branch',
    'Git: 创建空提交': 'git.commitEmpty',
    'Git: 从所有远程存储库中拉取': 'git.fetchAll',
    'Git: 从现有来源创建新的分支...': 'git.branchFrom',
    'Git: 打开包含的文件夹': 'git.revealFileInOS.linux',
    'Git: 打开仓库': 'git.openRepository',
    'Git: 打开更改': 'git.openChange',
    'Git: 打开所有更改': 'git.openAllChanges',
    'Git: 打开文件': 'git.openFile',
    'Git: 打开文件 (HEAD)': 'git.openHEADFile',
    'Git: 弹出储藏...': 'git.stashPop',
    'Git: 弹出储藏条目': 'git.stashPopEditor',
    'Git: 弹出最新储藏': 'git.stashPopLatest',
    'Git: 发布分支...': 'git.publish',
    'Git: 放弃更改': 'git.clean',
    'Git: 放弃所有跟踪的更改': 'git.cleanAllTracked',
    'Git: 放弃所有更改': 'git.cleanAll',
    'Git: 放弃所有未跟踪的更改': 'git.cleanAllUntracked',
    'Git: 放弃提交消息': 'git.commitMessageDiscard',
    'Git: 复制提交 ID': 'git.copyCommitId',
    'Git: 复制提交消息': 'git.copyCommitMessage',
    'Git: 关闭仓库': 'git.close',
    'Git: 关闭其他存储库': 'git.closeOtherRepositories',
    'Git: 关闭所有差异编辑器': 'git.closeAllDiffEditors',
    'Git: 关闭所有未修改的编辑器': 'git.closeAllUnmodifiedEditors',
    'Git: 管理不安全的存储库': 'git.manageUnsafeRepositories',
    'Git: 还原更改': 'git.revertChange',
    'Git: 还原提交模板': 'git.restoreCommitTemplate',
    'Git: 合并...': 'git.merge',
    'Git: 获取 (删除)': 'git.fetchPrune',
    'Git: 计算与 Git 冲突': 'git.runGitMerge',
    'Git: 计算与 Git 冲突(Diff3)': 'git.runGitMergeDiff3',
    'Git: 接受提交消息': 'git.commitMessageAccept',
    'Git: 克隆': 'git.clone',
    'Git: 克隆(递归)': 'git.cloneRecursive',
    'Git: 空提交(不验证)': 'git.commitEmptyNoVerify',
    'Git: 拉取': 'git.pull',
    'Git: 拉取(变基)': 'git.pullRebase',
    'Git: 拉取自...': 'git.pullFrom',
    'Git: 签出(已分离)': 'git.checkoutRefDetached',
    'Git: 签出到...': 'git.checkout',
    'Git: 签出到(已分离)…': 'git.checkoutDetached',
    'Git: 取消暂存更改': 'git.unstage',
    'Git: 取消暂存所有更改': 'git.unstageAll',
    'Git: 全部提交': 'git.commitAll',
    'Git: 全部提交(不验证)': 'git.commitAllNoVerify',
    'Git: 全部提交(修改)': 'git.commitAllAmend',
    'Git: 全部提交(修正，不验证)': 'git.commitAllAmendNoVerify',
    'Git: 全部提交(已签收，不验证)': 'git.commitAllSignedNoVerify',
    'Git: 全部提交(已署名)': 'git.commitAllSigned',
    'Git: 删除标签...': 'git.deleteTag',
    'Git: 删除储藏...': 'git.stashDrop',
    'Git: 删除储藏条目': 'git.stashDropEditor',
    'Git: 删除分支...': 'git.deleteBranch',
    'Git: 删除所有储藏...': 'git.stashDropAll',
    'Git: 删除远程标记...': 'git.deleteRemoteTag',
    'Git: 删除远程存储库': 'git.removeRemote',
    'Git: 刷新': 'git.refresh',
    'Git: 提交': 'git.commit',
    'Git: 提交(不验证)': 'git.commitNoVerify',
    'Git: 提交(修改，不验证)': 'git.commitAmendNoVerify',
    'Git: 提交(修改)': 'git.commitAmend',
    'Git: 提交(已签收，不验证)': 'git.commitSignedNoVerify',
    'Git: 提交(已签收)': 'git.commitSigned',
    'Git: 提交已暂存内容(不验证)': 'git.commitStagedNoVerify',
    'Git: 提交已暂存内容(修正，不验证)': 'git.commitStagedAmendNoVerify',
    'Git: 提交已暂存内容(已签收，不验证)': 'git.commitStagedSignedNoVerify',
    'Git: 提交已暂存文件': 'git.commitStaged',
    'Git: 提交已暂存文件(修改)': 'git.commitStagedAmend',
    'Git: 提交已暂存文件(已署名)': 'git.commitStagedSigned',
    'Git: 添加到 .gitignore': 'git.ignore',
    'Git: 添加远程存储库…': 'git.addRemote',
    'Git: 挑拣': 'git.cherryPickRef',
    'Git: 挑拣…': 'git.cherryPick',
    'Git: 同步': 'git.sync',
    'Git: 同步(变基)': 'git.syncRebase',
    'Git: 推送': 'git.push',
    'Git: 推送(“关注”标记，强制)': 'git.pushWithTagsForce',
    'Git: 推送(“关注”标记)': 'git.pushWithTags',
    'Git: 推送(强制)': 'git.pushForce',
    'Git: 推送标记': 'git.pushTags',
    'Git: 推送到...': 'git.pushTo',
    'Git: 推送到...(强制)': 'git.pushToForce',
    'Git: 完成合并': 'git.acceptMerge',
    'Git: 显示 GIT 输出': 'git.showOutput',
    'Git: 选择以进行比较': 'git.timeline.selectForCompare',
    'Git: 应用储藏...': 'git.stashApply',
    'Git: 应用储藏条目': 'git.stashApplyEditor',
    'Git: 应用最新储藏': 'git.stashApplyLatest',
    'Git: 与已选项目进行比较': 'git.timeline.compareWithSelected',
    'Git: 在本地克隆存储库并在桌面上打开...': 'git.continueInLocalClone',
    'Git: 在查找器中显示': 'git.revealFileInOS.mac',
    'Git: 在父文件夹中打开存储库': 'git.openRepositoriesInParentFolders',
    'Git: 在合并编辑器中解析': 'git.openMergeEditor',
    'Git: 在文件资源管理器中显示': 'git.revealFileInOS.windows',
    'Git: 在资源管理器视图中显示': 'git.revealInExplorer',
    'Git: 暂存更改': 'git.stage',
    'Git: 暂存块': 'git.diff.stageHunk',
    'Git: 暂存所有跟踪的更改': 'git.stageAllTracked',
    'Git: 暂存所有更改': 'git.stageAll',
    'Git: 暂存所有合并更改': 'git.stageAllMerge',
    'Git: 暂存所有未跟踪的更改': 'git.stageAllUntracked',
    'Git: 暂存选择': 'git.diff.stageSelection',
    'Git: 中止变基': 'git.rebaseAbort',
    'Git: 中止合并': 'git.mergeAbort',
    'Git: 重命名': 'git.rename',
    'Git: 重命名分支...': 'git.renameBranch',
    'Git: 重新打开已关闭的存储库...': 'git.reopenClosedRepositories',
    'Git: 抓取': 'git.fetch',
    'Image Preview: 放大': 'imagePreview.zoomIn',
    'Image Preview: 复制': 'imagePreview.copyImage',
    'Image Preview: 缩小': 'imagePreview.zoomOut',
    'isort: 重启服务器': 'isort.restart',
    'JavaScript: 对导入进行排序': 'javascript.sortImports',
    'JavaScript: 删除未使用的导入': 'javascript.removeUnusedImports',
    'JavaScript: 重载项目': 'javascript.reloadProjects',
    'JavaScript: 转到项目配置(jsconfig/tsconfig)': 'javascript.goToProjectConfig',
    'JSON: 排序文档': 'json.sort',
    'JSON: 清除架构缓存': 'json.clearCache',
    'Jupyter (Dev): 步骤 Pylance 日志': 'jupyter.replayPylanceLogStep',
    'Jupyter (Dev): 清除高速缓存': 'dataScience.ClearCache',
    'Jupyter (Dev): 清除用户 Jupyter 服务器缓存': 'dataScience.ClearUserProviderJupyterServerCache',
    'Jupyter (Dev): 重播 Pylance 日志': 'jupyter.replayPylanceLog',
    'Jupyter: 创建交互窗口': 'jupyter.createnewinteractive',
    'Jupyter: 创建新 Jupyter Notebook': 'jupyter.createnewnotebook',
    'Jupyter: 打开变量视图': 'jupyter.openVariableView',
    'Jupyter: 单步跳过': 'jupyter.debugstepover',
    'Jupyter: 导出': 'jupyter.interactive.exportas',
    'Jupyter: 导出到 HTML': 'jupyter.exportToHTML',
    'Jupyter: 导出到 Jupyter Notebook': 'jupyter.interactive.exportasnotebook',
    'Jupyter: 导出到 Python 脚本': 'jupyter.exportAsPythonScript',
    'Jupyter: 导出为': 'jupyter.export',
    'Jupyter: 导出为 PDF': 'jupyter.exportToPDF',
    'Jupyter: 导入 Jupyter Notebook': 'jupyter.importnotebook',
    'Jupyter: 调试当前单元格': 'jupyter.debugcurrentcell.palette',
    'Jupyter: 复制单元格': 'jupyter.interactive.copyCell',
    'Jupyter: 管理对 Jupyter 内核的访问权限': 'jupyter.manageAccessToKernels',
    'Jupyter: 继续': 'jupyter.debugcontinue',
    'Jupyter: 将笔记本导入脚本': 'jupyter.importnotebookfile',
    'Jupyter: 将单元格滚动到视图中': 'jupyter.scrolltocell',
    'Jupyter: 将当前 Python 文件导出为 Jupyter Notebook': 'jupyter.exportfileasnotebook',
    'Jupyter: 将当前 Python 文件和输出导出为 Jupyter Notebook': 'jupyter.exportfileandoutputasnotebook',
    'Jupyter: 将交互窗口导出为 Jupyter Notebook': 'jupyter.exportoutputasnotebook',
    'Jupyter: 将空单元格添加到文件': 'jupyter.addcellbelow',
    'Jupyter: 交互窗口中的“运行到行”': 'jupyter.runtoline',
    'Jupyter: 焦点在 Cell Tags 视图上': 'cell-tag.focus',
    'Jupyter: 焦点在 Variables 视图上': 'jupyterViewVariables.focus',
    'Jupyter: 清除 Jupyter 远程服务器列表': 'jupyter.clearSavedJupyterUris',
    'Jupyter: 全部清除': 'jupyter.interactive.clearAllCells',
    'Jupyter: 筛选器内核': 'jupyter.filterKernels',
    'Jupyter: 停止': 'jupyter.debugstop',
    'Jupyter: 显示目录(大纲视图)': 'jupyter.openOutlineView',
    'Jupyter: 显示输出': 'jupyter.viewOutput',
    'Jupyter: 选择“解释器”以启动 Jupyter 服务器': 'jupyter.selectJupyterInterpreter',
    'Jupyter: 运行单元格': 'jupyter.runcell',
    'Jupyter: 运行当前单元格及更低版本': 'jupyter.runcurrentcellandallbelow.palette',
    'Jupyter: 运行所有单元格': 'jupyter.runallcells',
    'Jupyter: 运行以上': 'jupyter.runallcellsabove',
    'Jupyter: 在当前单元格上方运行单元格': 'jupyter.runallcellsabove.palette',
    'Jupyter: 在交互窗口中从行运行': 'jupyter.runfromline',
    'Jupyter: 在交互窗口中调试当前文件': 'jupyter.debugFileInteractive',
    'Jupyter: 在交互窗口中运行当前文件': 'jupyter.runFileInteractive',
    'Jupyter: 在数据查看器中查看值': 'jupyter.showDataViewer',
    'Jupyter: 在下面运行': 'jupyter.runcellandallbelow',
    'Jupyter: 在专用扩展主机中运行': 'jupyter.runInDedicatedExtensionHost',
    'Jupyter: 展开所有单元格输入': 'jupyter.expandallcells',
    'Jupyter: 折叠所有单元格输入': 'jupyter.collapseallcells',
    'Jupyter: 中断 Kernel': 'jupyter.interruptkernel',
    'Jupyter: 重启 Kernel': 'jupyter.restartkernel',
    'Jupyter: 重启内核并运行所有单元格': 'jupyter.restartkernelandrunallcells',
    'Jupyter: 重新启动内核并运行到所选单元格': 'jupyter.restartkernelandrunuptoselectedcell',
    'Jupyter: 转到代码': 'jupyter.interactive.goToCode',
    'Jupyter: Continue On Codespace': 'jupyter.continueEditSessionInCodespace',
    'Jupyter: DataScience.latestExtension': 'jupyter.latestExtension',
    'Jupyter: Debug Cell Symbols': 'jupyter.debugCellSymbols',
    'Jupyter: Execute with Dependent Cells': 'jupyter.runDependentCells',
    'Jupyter: Execute with Precedent Cells': 'jupyter.runPrecedentCells',
    'Jupyter: List Pip Packages': 'jupyter.listPipPackages',
    'Jupyter: List Variables': 'jupyter.listVariables',
    'Jupyter: Select Dependent Cells': 'jupyter.selectDependentCells',
    'Jupyter: Select Precedent Cells': 'jupyter.selectPrecedentCells',
    'Learn more about import resolution': 'pylance.learnMoreAboutImportResolution',
    'Mark Cell as Parameters': 'jupyter-cell-tags.paramaterize',
    'Markdown: 查找文件引用': 'markdown.findAllFileReferences',
    'Markdown: 从工作区插入映像': 'markdown.editor.insertImageFromWorkspace',
    'Markdown: 更改预览安全设置': 'markdown.showPreviewSecuritySelector',
    'Markdown: 切换开关锁定预览': 'markdown.preview.toggleLock',
    'Markdown: 刷新预览': 'markdown.preview.refresh',
    'Markdown: 显示源': 'markdown.showSource',
    'Markdown: 在侧边打开锁定的预览': 'markdown.showLockedPreviewToSide',
    'Markdown: 在工作区中插入文件链接': 'markdown.editor.insertLinkFromWorkspace',
    'Notebook: 导出为': 'jupyter.notebookeditor.export',
    'Notebook: 复制单元格输出': 'notebook.cellOutput.copy',
    'Notebook: 将空单元格添加到 Notebook 文件': 'jupyter.notebookeditor.addcellbelow',
    'Notebook: 删除所有 Notebook 编辑器单元格': 'jupyter.notebookeditor.removeallcells',
    'Notebook: 在文本编辑器中打开单元输出': 'notebook.cellOutput.openInTextEditor',
    'Open in vscode.dev': 'github.openOnVscodeDev',
    'Prettier：选择配置文件': 'prettier.createConfigFile',
    'Publish to GitHub': 'github.publish',
    'Pylance debugging: Dump parse tree ...': 'pylance.dumpNodes',
    'Pylance debugging: Dump token streams ...': 'pylance.dumpTokens',
    'Pylance debugging: Dump type info ...': 'pylance.dumpTypes',
    'Pylance debugging: Pylance: Dump cached type info ...': 'pylance.dumpCachedTypes',
    'Pylance debugging: Pylance: Dump code flow graph for node ...': 'pylance.dumpCodeFlowGraph',
    'Pylance: 报告问题...': 'pylance.reportIssue',
    'Pylance: 开始分析': 'pylance.profiling.start',
    'Pylance: 开始日志记录': 'pylance.logging.start',
    'Pylance: 清除所有持久索引': 'pylance.indexing.clearPersistedIndices',
    'Pylance: 停止分析': 'pylance.profiling.stop',
    'Pylance: 停止日志记录': 'pylance.logging.stop',
    'Pylance: 转到输出通道': 'pylance.gotoOutputChannel',
    'Python Debugger: 报告问题...': 'debugpy.reportIssue',
    'Python Debugger: 清除缓存并重新加载窗口': 'debugpy.clearCacheAndReload',
    'Python Debugger: 显示输出': 'debugpy.viewOutput',
    'Python Debugger: Python 调试程序: 调试 Python 文件': 'debugpy.debugInTerminal',
    'Python Debugger: Python 调试程序: 使用 launch.json 进行调试': 'debugpy.debugUsingLaunchConfig',
    'Python: 安装 Jupyter 扩展': 'python.installJupyter',
    'Python: 报告问题…': 'python.reportIssue',
    'Python: 创建环境...': 'python.createEnvironment',
    'Python: 创建终端': 'python.createTerminal',
    'Python: 配置测试': 'python.configureTests',
    'Python: 启动 Tensorboard': 'python.launchTensorBoard',
    'Python: 启动本机 Python REPL': 'python.startNativeREPL',
    'Python: 启动终端 REPL': 'python.startREPL',
    'Python: 清除工作区解释器设置': 'python.clearWorkspaceInterpreter',
    'Python: 清除缓存并重新加载窗口': 'python.clearCacheAndReload',
    'Python: 为扩展调试启用源映射支持': 'python.enableSourceMapSupport',
    'Python: 显示输出': 'python.viewOutput',
    'Python: 显示语言服务器输出': 'python.viewLanguageServerOutput',
    'Python: 新建 Python 文件': 'python.createNewFile',
    'Python: 选择解释器': 'python.setInterpreter',
    'Python: 运行 Python 文件': 'python.execInTerminal-icon',
    'Python: 在 Django Shell 中运行选择/行': 'python.execSelectionInDjangoShell',
    'Python: 在终端中运行 Python 文件': 'python.execInTerminal',
    'Python: 在专用终端中运行 Python 文件': 'python.execInDedicatedTerminal',
    'Python: 重启语言服务器': 'python.analysis.restartLanguageServer',
    'Remove Cell Tag': 'jupyter-cell-tags.removeTag',
    'Ruff: Fix all auto-fixable problems': 'ruff.executeAutofix',
    'Ruff: Format document': 'ruff.executeFormat',
    'Ruff: Format imports': 'ruff.executeOrganizeImports',
    'Ruff: Print debug information (native server only)': 'ruff.debugInformation',
    'Ruff: Restart Server': 'ruff.restart',
    'Ruff: Show logs': 'ruff.showLogs',
    'Simple Browser: Show': 'simpleBrowser.show',
    'Switch Slide Type': 'jupyter-slideshow.switchSlideType',
    'TOML: Copy as JSON': 'evenBetterToml.copyAsJson',
    'TOML: Copy as TOML': 'evenBetterToml.copyAsToml',
    'TOML: Paste as JSON': 'evenBetterToml.pasteAsJson',
    'TOML: Paste as TOML': 'evenBetterToml.pasteAsToml',
    'TOML: Select Schema': 'evenBetterToml.selectSchema',
    'Types: 显示超类型': 'references-view.showSupertypes',
    'Types: 显示类型层次结构': 'references-view.showTypeHierarchy',
    'Types: 显示子类型': 'references-view.showSubtypes',
    'TypeScript: 查找文件引用': 'typescript.findAllFileReferences',
    'TypeScript: 打开 TS 服务器日志': 'typescript.openTsServerLog',
    'TypeScript: 对导入进行排序': 'typescript.sortImports',
    'TypeScript: 删除未使用的导入': 'typescript.removeUnusedImports',
    'TypeScript: 选择 TypeScript 版本...': 'typescript.selectTypeScriptVersion',
    'TypeScript: 重启 TS 服务器': 'typescript.restartTsServer',
    'TypeScript: 重载项目': 'typescript.reloadProjects',
    'TypeScript: 转到项目配置(tsconfig)': 'typescript.goToProjectConfig',
    'TypeScript: 转到源定义': 'typescript.goToSourceDefinition',
    'View: 切换树粘滞滚动': 'tree.toggleStickyScroll',
};
