export interface StringDictionary {
    [key: string]: string;
}

export let commandNameToIDKo: StringDictionary = {
    '<Tab> 키로 포커스 이동 설정/해제': 'editor.action.toggleTabFocusMode',
    '가리키기 또는 포커스 표시': 'editor.action.showHover',
    '가져오기 구성': 'editor.action.organizeImports',
    '개발자: 개발자 도구 설정/해제': 'workbench.action.toggleDevTools',
    '개발자: 창 다시 로드': 'workbench.action.reloadWindow',
    '검색 편집기: 검색 편집기 입력 포커스': 'search.action.focusQueryEditorWidget',
    '검색 편집기: 다시 검색': 'rerunSearchEditorSearch',
    '검색 편집기: 단어 단위로 토글': 'toggleSearchEditorWholeWord',
    '검색 편집기: 대/소문자 구분 토글': 'toggleSearchEditorCaseSensitive',
    '검색 편집기: 모든 일치 항목 선택': 'selectAllSearchEditorMatches',
    '검색 편집기: 정규식 사용 토글': 'toggleSearchEditorRegex',
    '검색 편집기: 컨텍스트 줄 늘이기': 'increaseSearchEditorContextLines',
    '검색 편집기: 컨텍스트 줄 줄이기': 'decreaseSearchEditorContextLines',
    '검색 편집기: 컨텍스트 줄 토글': 'toggleSearchEditorContextLines',
    '검색 편집기: 파일 결과 삭제': 'search.searchEditor.action.deleteFileResults',
    '검색 편집기: 편집기에서 결과 열기': 'search.action.openInEditor',
    '검색: 검색 취소': 'search.action.cancel',
    '검색: 다음 검색 결과에 포커스': 'search.action.focusNextSearchResult',
    '검색: 이전 검색 결과에 포커스': 'search.action.focusPreviousSearchResult',
    '검색: 파일에서 바꾸기': 'workbench.action.replaceInFiles',
    '검색: 파일에서 찾기': 'workbench.action.findInFiles',
    '구현으로 이동': 'editor.action.goToImplementation',
    '기본 설정: 바로 가기 키 열기': 'workbench.action.openGlobalKeybindings',
    '기본 설정: 색 테마': 'workbench.action.selectTheme',
    '기본 설정: 설정 검색 결과 지우기': 'settings.action.clearSearchResults',
    '기본 설정: 설정 검색에 포커스': 'settings.action.search',
    '기본 설정: 설정 목차에 포커스': 'settings.action.focusTOC',
    '기본 설정: 설정 상황에 맞는 메뉴 표시': 'settings.action.showContextMenu',
    '기본 설정: 포커스를 한 수준 위로 이동': 'settings.action.focusLevelUp',
    '기호 이름 바꾸기': 'editor.action.rename',
    '다시 실행': 'redo',
    '다음 값으로 바꾸기': 'editor.action.inPlaceReplace.down',
    '다음 강조 기호로 이동': 'editor.action.wordHighlight.next',
    '다음 문제로 이동 (오류, 경고, 정보)': 'editor.action.marker.next',
    '다음 변경 내용 표시': 'editor.action.dirtydiff.next',
    '다음 변경으로 이동': 'workbench.action.compareEditor.nextChange',
    '다음 선택 찾기': 'editor.action.nextSelectionMatchFindAction',
    '다음 인라인 제안 표시': 'editor.action.inlineSuggest.showNext',
    '다음 인라인 편집으로 이동': 'editor.action.inlineSuggest.jump',
    '다음 일치 항목 찾기로 마지막 선택 항목 이동': 'editor.action.moveSelectionToNextFindMatch',
    '다음 일치 항목 찾기에 선택 항목 추가': 'editor.action.addSelectionToNextFindMatch',
    '다음 참조로 이동': 'references-view.next',
    '다음 찾기': 'editor.action.nextMatchFindAction',
    '대괄호 제거': 'editor.action.removeBrackets',
    '대괄호로 이동': 'editor.action.jumpToBracket',
    '대화형 창: 포커스 기록': 'interactive.history.focus',
    '대화형 창: 포커스 입력 편집기': 'interactive.input.focus',
    '도움말: 바로 가기 키 참조': 'workbench.action.keybindingsReference',
    '독립 실행형 Color Picker로 색 삽입': 'editor.action.insertColorWithStandaloneColorPicker',
    돌아가기: 'workbench.action.navigateBack',
    '디버그 콘솔: 입력 수락': 'repl.action.acceptInput',
    '디버그: 가리키기 표시': 'editor.debug.action.showDebugHover',
    '디버그: 계속': 'workbench.action.debug.continue',
    '디버그: 다시 시작': 'workbench.action.debug.restart',
    '디버그: 다음 포커스 디버그 콘솔': 'workbench.action.debug.nextConsole',
    '디버그: 단계 정보': 'workbench.action.debug.stepInto',
    '디버그: 단계 출력': 'workbench.action.debug.stepOut',
    '디버그: 단위 실행': 'workbench.action.debug.stepOver',
    '디버그: 대상으로 한 단계씩 코드 실행': 'workbench.action.debug.stepIntoTarget',
    '디버그: 디버깅 시작': 'workbench.action.debug.start',
    '디버그: 디버깅하지 않고 시작': 'workbench.action.debug.run',
    '디버그: 연결 끊기': 'workbench.action.debug.disconnect',
    '디버그: 이전 디버그 콘솔 포커스': 'workbench.action.debug.prevConsole',
    '디버그: 인라인 중단점': 'editor.debug.action.toggleInlineBreakpoint',
    '디버그: 일시 중지': 'workbench.action.debug.pause',
    '디버그: 중단점 설정/해제': 'editor.debug.action.toggleBreakpoint',
    '디버그: 중지': 'workbench.action.debug.stop',
    '리팩터링...': 'editor.action.refactor',
    '마지막 편집 위치로 이동': 'workbench.action.navigateToLastEditLocation',
    '만들기: 새 파일...': 'welcome.showNewFileEntries',
    '매개 변수 힌트 트리거': 'editor.action.triggerParameterHints',
    '모두 선택': 'editor.action.selectAll',
    '모두 접기': 'editor.foldAll',
    '모두 펼치기': 'editor.unfoldAll',
    '모든 명령 표시': 'workbench.action.showCommands',
    '모든 블록 코멘트를 접기': 'editor.foldAllBlockComments',
    '모든 영역 접기': 'editor.foldAllMarkerRegions',
    '모든 영역 펼치기': 'editor.unfoldAllMarkerRegions',
    '모든 항목 변경': 'editor.action.changeAll',
    '문서 서식': 'editor.action.formatDocument',
    바꾸기: 'editor.action.startFindReplaceAction',
    '보기: 검색 표시': 'workbench.view.search',
    '보기: 그룹에 편집기 조인': 'workbench.action.joinEditorInGroup',
    '보기: 그룹에서 가장 오래 전에 사용한 편집기 빨리 열기': 'workbench.action.quickOpenLeastRecentlyUsedEditorInGroup',
    '보기: 그룹에서 다음 편집기 열기': 'workbench.action.nextEditorInGroup',
    '보기: 그룹에서 이전 편집기 열기': 'workbench.action.previousEditorInGroup',
    '보기: 그룹에서 저장된 편집기 닫기': 'workbench.action.closeUnmodifiedEditors',
    '보기: 그룹에서 최근에 사용한 편집기 빨리 열기': 'workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup',
    '보기: 그룹의 마지막 편집기 열기': 'workbench.action.lastEditorInGroup',
    '보기: 그룹의 모든 편집기 닫기': 'workbench.action.closeEditorsInGroup',
    '보기: 기본 사이드 바 가시성 전환': 'workbench.action.toggleSidebarVisibility',
    '보기: 기본 사이드 바에 집중': 'workbench.action.focusSideBar',
    '보기: 다음 부분에 포커스 설정': 'workbench.action.focusNextPart',
    '보기: 다음 편집기 열기': 'workbench.action.nextEditor',
    '보기: 닫힌 편집기 다시 열기': 'workbench.action.reopenClosedEditor',
    '보기: 디버그 콘솔 토글': 'workbench.debug.action.toggleRepl',
    '보기: 모든 편집기 그룹 닫기': 'workbench.action.closeAllGroups',
    '보기: 모든 편집기 닫기': 'workbench.action.closeAllEditors',
    '보기: 문제 토글': 'workbench.actions.view.problems',
    '보기: 보조 사이드바 표시 설정/해제': 'workbench.action.toggleAuxiliaryBar',
    '보기: 소스 제어 표시': 'workbench.view.scm',
    '보기: 실행 및 디버그 표시': 'workbench.view.debug',
    '보기: 아래 포커스 편집기 그룹': 'workbench.action.focusBelowGroup',
    '보기: 오른쪽 편집기 그룹에 포커스': 'workbench.action.focusRightGroup',
    '보기: 오른쪽으로 편집기 이동': 'workbench.action.moveEditorRightInGroup',
    '보기: 왼쪽 편집기 그룹에 포커스': 'workbench.action.focusLeftGroup',
    '보기: 왼쪽으로 편집기 이동': 'workbench.action.moveEditorLeftInGroup',
    '보기: 위의 포커스 편집기 그룹': 'workbench.action.focusAboveGroup',
    '보기: 이전 부분에 포커스 설정': 'workbench.action.focusPreviousPart',
    '보기: 이전 편집기 열기': 'workbench.action.previousEditor',
    '보기: 자동 줄 바꿈 설정/해제': 'editor.action.toggleWordWrap',
    '보기: 전체 화면 설정/해제': 'workbench.action.toggleFullScreen',
    '보기: 첫 번째 편집기 그룹에 포커스': 'workbench.action.focusFirstEditorGroup',
    '보기: 축소': 'workbench.action.zoomOut',
    '보기: 출력 토글': 'workbench.action.output.toggleOutput',
    '보기: 탐색기 표시': 'workbench.view.explorer',
    '보기: 터미널 토글': 'workbench.action.terminal.toggleTerminal',
    '보기: 패널 표시 설정/해제': 'workbench.action.togglePanel',
    '보기: 편집기 고정': 'workbench.action.pinEditor',
    '보기: 편집기 고정 해제': 'workbench.action.unpinEditor',
    '보기: 편집기 그룹 최대화 토글': 'workbench.action.toggleMaximizeEditorGroup',
    '보기: 편집기 그룹을 아래로 이동': 'workbench.action.moveActiveEditorGroupDown',
    '보기: 편집기 그룹을 오른쪽으로 이동': 'workbench.action.moveActiveEditorGroupRight',
    '보기: 편집기 그룹을 왼쪽으로 이동': 'workbench.action.moveActiveEditorGroupLeft',
    '보기: 편집기 그룹을 위로 이동': 'workbench.action.moveActiveEditorGroupUp',
    '보기: 편집기 닫기': 'workbench.action.closeActiveEditor',
    '보기: 편집기 분할': 'workbench.action.splitEditor',
    '보기: 편집기 수직 분할': 'workbench.action.splitEditorOrthogonal',
    '보기: 편집기 왼쪽 분할': 'workbench.action.splitEditorLeft',
    '보기: 편집기 위쪽 분할': 'workbench.action.splitEditorUp',
    '보기: 편집기 유지': 'workbench.action.keepEditor',
    '보기: 편집기를 그룹으로 분할': 'workbench.action.splitEditorInGroup',
    '보기: 편집기를 다음 그룹으로 이동': 'workbench.action.moveEditorToNextGroup',
    '보기: 편집기를 마지막 그룹으로 이동': 'workbench.action.moveEditorToLastGroup',
    '보기: 편집기를 새 창에 복사': 'workbench.action.copyEditorToNewWindow',
    '보기: 편집기를 아래로 분할': 'workbench.action.splitEditorDown',
    '보기: 편집기를 오른쪽으로 분할': 'workbench.action.splitEditorRight',
    '보기: 편집기를 이전 그룹으로 이동': 'workbench.action.moveEditorToPreviousGroup',
    '보기: 편집기를 첫 번째 그룹으로 이동': 'workbench.action.moveEditorToFirstGroup',
    '보기: 확대': 'workbench.action.zoomIn',
    '보기: 확대/축소 다시 설정': 'workbench.action.zoomReset',
    '보기: 확장 표시': 'workbench.view.extensions',
    '보기: Zen 모드 설정/해제': 'workbench.action.toggleZenMode',
    복사: 'editor.action.clipboardCopyAction',
    붙여넣기: 'editor.action.clipboardPasteAction',
    '블록 주석 설정/해제': 'editor.action.blockComment',
    '빠른 수정...': 'editor.action.quickFix',
    '새 외부 터미널 열기': 'workbench.action.terminal.openNativeConsole',
    '새 창': 'workbench.action.newWindow',
    '선 선택 영역 확장': 'expandLineSelection',
    '선택 앵커 지점 설정': 'editor.action.setSelectionAnchor',
    '선택 앵커 지점 취소': 'editor.action.cancelSelectionAnchor',
    '선택 영역 서식': 'editor.action.formatSelection',
    '선택 영역 축소': 'editor.action.smartSelect.shrink',
    '선택 영역 확장': 'editor.action.smartSelect.expand',
    '선택 영역에서 접기 범위 만들기': 'editor.createFoldingRangeFromSelection',
    '선택한 항목을 제외한 모든 항목 접기': 'editor.foldAllExcept',
    '선택한 항목을 제외한 모든 항목 표시': 'editor.unfoldAllExcept',
    '설명: 다음 주석 처리된 범위로 이동': 'editor.action.nextCommentedRangeAction',
    '설명: 이전 주석 처리된 범위로 이동': 'editor.action.previousCommentedRangeAction',
    '세로/가로 편집기 레이아웃 설정/해제': 'workbench.action.toggleEditorGroupLayout',
    '셀 서식': 'notebook.formatCell',
    '수동 폴딩 범위 제거': 'editor.removeManualFoldingRanges',
    '수준 1 접기': 'editor.foldLevel1',
    '수준 2 접기': 'editor.foldLevel2',
    '수준 3 접기': 'editor.foldLevel3',
    '수준 4 접기': 'editor.foldLevel4',
    '수준 5 접기': 'editor.foldLevel5',
    '수준 6 접기': 'editor.foldLevel6',
    '수준 7 접기': 'editor.foldLevel7',
    '시작: 뒤로 이동': 'welcome.goBack',
    '실행 취소': 'undo',
    '아래로 스크롤 가리키기': 'editor.action.scrollDownHover',
    '아래에 줄 복사': 'editor.action.copyLinesDownAction',
    '아래에 줄 삽입': 'editor.action.insertLineAfter',
    '아래에 커서 추가': 'editor.action.insertCursorBelow',
    '아래쪽 가리키기로 이동': 'editor.action.goToBottomHover',
    '알림: 알림 기본 작업 수락': 'notification.acceptPrimaryAction',
    '알림: 알림 숨기기': 'notifications.hideList',
    '알림: 알림 표시': 'notifications.showList',
    '앞으로 이동': 'workbench.action.navigateForward',
    '액세스 가능한 보기 힌트 사용 안 함': 'editor.action.accessibleViewDisableHint',
    '액세스 가능한 Diff 뷰어: 다음 다른 항목으로 이동': 'editor.action.accessibleDiffViewer.next',
    '앵커에서 커서로 선택': 'editor.action.selectFromAnchorToCursor',
    '언어 모드 변경': 'workbench.action.editor.changeLanguageMode',
    '연결된 편집 시작': 'editor.action.linkedEditing',
    '예외 위젯 닫기': 'editor.debug.action.closeExceptionWidget',
    '오른쪽으로 스크롤 가리키기': 'editor.action.scrollRightHover',
    '왼쪽으로 스크롤 가리키기': 'editor.action.scrollLeftHover',
    '원격: 원격 메뉴 표시': 'workbench.action.remote.showMenu',
    '위로 스크롤 가리키기': 'editor.action.scrollUpHover',
    '위에 줄 복사': 'editor.action.copyLinesUpAction',
    '위에 줄 삽입': 'editor.action.insertLineBefore',
    '위에 커서 추가': 'editor.action.insertCursorAbove',
    '위쪽 가리키기로 이동': 'editor.action.goToTopHover',
    '음성: 편집기에서 받아쓰기 시작': 'workbench.action.editorDictation.start',
    '음성: 편집기에서 받아쓰기 중지': 'workbench.action.editorDictation.stop',
    '이동 경로에 포커스': 'breadcrumbs.focus',
    '이전 값으로 바꾸기': 'editor.action.inPlaceReplace.up',
    '이전 강조 기호로 이동': 'editor.action.wordHighlight.prev',
    '이전 문제로 이동 (오류, 경고, 정보)': 'editor.action.marker.prev',
    '이전 변경 내용 표시': 'editor.action.dirtydiff.previous',
    '이전 변경 내용으로 이동': 'workbench.action.compareEditor.previousChange',
    '이전 선택 찾기': 'editor.action.previousSelectionMatchFindAction',
    '이전 인라인 제안 표시': 'editor.action.inlineSuggest.showPrevious',
    '이전 참조로 이동': 'references-view.prev',
    '이전 찾기': 'editor.action.previousMatchFindAction',
    '인라인 완성 허용': 'editor.action.accessibleViewAcceptInlineCompletion',
    '인라인 제안 숨기기': 'editor.action.inlineSuggest.hide',
    '인라인 제안의 다음 단어 수락': 'editor.action.inlineSuggest.acceptNextWord',
    '인라인 채팅: 다음 변경 내용으로 이동': 'inlineChat.moveToNextHunk',
    '인라인 채팅: 변경 내용 수락': 'inlineChat.acceptChanges',
    '인라인 채팅: 이전 변경 내용으로 이동': 'inlineChat.moveToPreviousHunk',
    '인라인 채팅: 터미널에서 시작': 'workbench.action.terminal.chat.start',
    '인라인 채팅: 편집기 인라인 채팅': 'inlineChat.start',
    '인라인 채팅: 포커스 입력': 'inlineChat.focus',
    '인라인 채팅: 포커스 터미널 응답': 'workbench.action.terminal.chat.focusResponse',
    '인라인 채팅: 포커스 터미널 입력': 'workbench.action.terminal.chat.focusInput',
    '인라인 추천 수락': 'editor.action.inlineSuggest.commit',
    '인레이 힌트 읽기 중지': 'inlayHints.stopReadingLineWithHint',
    '일치 항목 찾기의 모든 항목 선택': 'editor.action.selectHighlights',
    '자동 수정...': 'editor.action.autoFix',
    '작업 영역: 작업 영역 닫기': 'workbench.action.closeFolder',
    '작업 영역에서 기호로 이동...': 'workbench.action.showAllSymbols',
    '작업: 빌드 작업 실행': 'workbench.action.tasks.build',
    잘라내기: 'editor.action.clipboardCutAction',
    '재귀적으로 접기': 'editor.foldRecursively',
    '재귀적으로 접기 토글': 'editor.toggleFoldRecursively',
    '재귀적으로 펼치기': 'editor.unfoldRecursively',
    '접근성 도움말 열기': 'editor.action.accessibilityHelp',
    '접근성 보기 열기': 'editor.action.accessibleView',
    '접근성 보기에서 기호로 이동': 'editor.action.accessibleViewGoToSymbol',
    '접근성 보기에서 다음 표시': 'editor.action.accessibleViewNext',
    '접근성 보기에서 이전 표시': 'editor.action.accessibleViewPrevious',
    접기: 'editor.fold',
    '접기 전환': 'editor.toggleFold',
    '정의 피킹': 'editor.action.peekDefinition',
    '정의로 이동': 'editor.action.revealDefinition',
    '제안 항목 트리거': 'editor.action.triggerSuggest',
    '줄 끝에 커서 추가': 'editor.action.insertCursorAtEndOfEachLineSelected',
    '줄 내어쓰기': 'editor.action.outdentLines',
    '줄 들여쓰기': 'editor.action.indentLines',
    '줄 삭제': 'editor.action.deleteLines',
    '줄 아래로 이동': 'editor.action.moveLinesDownAction',
    '줄 위로 이동': 'editor.action.moveLinesUpAction',
    '줄 주석 설정/해제': 'editor.action.commentLine',
    '줄 주석 제거': 'editor.action.removeCommentLine',
    '줄 주석 추가': 'editor.action.addCommentLine',
    '줄/열로 이동...': 'workbench.action.gotoLine',
    '참조: 모든 참조 찾기': 'references-view.findReferences',
    '참조로 이동': 'editor.action.goToReferences',
    '창 닫기': 'workbench.action.closeWindow',
    찾기: 'actions.find',
    '채팅: 다음 코드 블록': 'workbench.action.chat.nextCodeBlock',
    '채팅: 다음 파일 트리': 'workbench.action.chat.nextFileTree',
    '채팅: 듣기 중지': 'workbench.action.chat.stopListening',
    '채팅: 새 채팅': 'workbench.action.chat.newChat',
    '채팅: 소리 내어 읽기 중지': 'workbench.action.speech.stopReadAloud',
    '채팅: 수신 중지 및 제출': 'workbench.action.chat.stopListeningAndSubmit',
    '채팅: 음성 채팅 시작': 'workbench.action.chat.startVoiceChat',
    '채팅: 이전 코드 블록': 'workbench.action.chat.previousCodeBlock',
    '채팅: 이전 파일 트리': 'workbench.action.chat.previousFileTree',
    '채팅: 채팅 열기': 'workbench.action.chat.open',
    '채팅: 커서 위치에 삽입': 'workbench.action.chat.insertCodeBlock',
    '채팅: 터미널에 삽입': 'workbench.action.chat.runInTerminal',
    '채팅: 편집기에서 적용': 'workbench.action.chat.applyInEditor',
    '측면에서 정의 열기': 'editor.action.revealDefinitionAside',
    '커서 실행 취소': 'cursorUndo',
    '코드 조각: 조각 삽입': 'editor.action.insertSnippet',
    '콘텐츠에서 언어 검색': 'editor.detectLanguage',
    '키 바인딩 정의': 'editor.action.defineKeybinding',
    '탐색기: 열려 있는 편집기 보기에 포커스': 'workbench.files.action.focusOpenEditorsView',
    '터미널: 검색된 링크 열기': 'workbench.action.terminal.openDetectedLink',
    '터미널: 기록에서 다음': 'workbench.action.terminal.chat.nextFromHistory',
    '터미널: 다음 명령까지 선택': 'workbench.action.terminal.selectToNextCommand',
    '터미널: 다음 명령으로 스크롤': 'workbench.action.terminal.scrollToNextCommand',
    '터미널: 다음 찾기': 'workbench.action.terminal.findNext',
    '터미널: 대/소문자 구분을 사용하여 찾기 설정/해제': 'workbench.action.terminal.toggleFindCaseSensitive',
    '터미널: 맨 아래로 스크롤': 'workbench.action.terminal.scrollToBottom',
    '터미널: 맨 위로 스크롤': 'workbench.action.terminal.scrollToTop',
    '터미널: 새 터미널 만들기': 'workbench.action.terminal.new',
    '터미널: 선택 영역 복사': 'workbench.action.terminal.copySelection',
    '터미널: 선택 영역 복사 및 지우기': 'workbench.action.terminal.copyAndClearSelection',
    '터미널: 선택 영역 지우기': 'workbench.action.terminal.clearSelection',
    '터미널: 아래로 스크롤(줄)': 'workbench.action.terminal.scrollDown',
    '터미널: 아래로 스크롤(페이지)': 'workbench.action.terminal.scrollDownPage',
    '터미널: 액세스 가능한 버퍼 다음 명령으로 이동': 'workbench.action.terminal.accessibleBufferGoToNextCommand',
    '터미널: 액세스 가능한 버퍼 이전 명령으로 이동': 'workbench.action.terminal.accessibleBufferGoToPreviousCommand',
    '터미널: 위로 스크롤(줄)': 'workbench.action.terminal.scrollUp',
    '터미널: 위로 스크롤(페이지)': 'workbench.action.terminal.scrollUpPage',
    '터미널: 이전 기록에서': 'workbench.action.terminal.chat.previousFromHistory',
    '터미널: 이전 명령까지 선택': 'workbench.action.terminal.selectToPreviousCommand',
    '터미널: 이전 명령으로 스크롤': 'workbench.action.terminal.scrollToPreviousCommand',
    '터미널: 이전 찾기': 'workbench.action.terminal.findPrevious',
    '터미널: 작업 영역 검색': 'workbench.action.terminal.searchWorkspace',
    '터미널: 전체 단어를 사용하여 찾기 설정/해제': 'workbench.action.terminal.toggleFindWholeWord',
    '터미널: 접근성 보기 아래쪽으로 스크롤': 'workbench.action.terminal.scrollToBottomAccessibleView',
    '터미널: 접근성 보기 위쪽으로 스크롤': 'workbench.action.terminal.scrollToTopAccessibleView',
    '터미널: 찾기 숨기기': 'workbench.action.terminal.hideFind',
    '터미널: 찾기 포커스': 'workbench.action.terminal.focusFind',
    '터미널: 채팅 닫기': 'workbench.action.terminal.chat.close',
    '터미널: 채팅 명령 실행': 'workbench.action.terminal.chat.runCommand',
    '터미널: 채팅 삽입 명령': 'workbench.action.terminal.chat.insertCommand',
    '터미널: 채팅 요청': 'workbench.action.terminal.chat.makeRequest',
    '터미널: 첫 번째 채팅 명령 실행': 'workbench.action.terminal.chat.runFirstCommand',
    '터미널: 첫 번째 채팅 삽입 명령': 'workbench.action.terminal.chat.insertFirstCommand',
    '터미널: 최근 디렉터리로 이동...': 'workbench.action.terminal.goToRecentDirectory',
    '터미널: 최근 명령 실행...': 'workbench.action.terminal.runRecentCommand',
    '터미널: 크기를 콘텐츠 너비로 전환': 'workbench.action.terminal.sizeToContentWidth',
    '터미널: 터미널 그룹의 다음 터미널 포커스': 'workbench.action.terminal.focusNextPane',
    '터미널: 터미널 그룹의 이전 터미널 포커스': 'workbench.action.terminal.focusPreviousPane',
    '터미널: 터미널 분할': 'workbench.action.terminal.split',
    '터미널: 터미널 빠른 수정 표시': 'workbench.action.terminal.showQuickFixes',
    '터미널: 터미널에 포커스': 'workbench.action.terminal.focus',
    '터미널: 편집기 영역에서 활성 터미널 종료': 'workbench.action.terminal.killEditor',
    '터미널: 포커스 가리키기': 'workbench.action.terminal.focusHover',
    '터미널: 포커스 다음 터미널 그룹': 'workbench.action.terminal.focusNext',
    '터미널: 포커스 이전 터미널 그룹': 'workbench.action.terminal.focusPrevious',
    '터미널: 포커스 터미널 탭 보기': 'workbench.action.terminal.focusTabs',
    '터미널: 활성 터미널에 붙여넣기': 'workbench.action.terminal.paste',
    '터미널: regex를 사용하여 찾기 설정/해제': 'workbench.action.terminal.toggleFindRegex',
    '테스트: 다음 테스트 실패로 이동': 'testing.goToNextMessage',
    '테스트: 마지막 실행 다시 실행': 'testing.reRunLastRun',
    '테스트: 마지막 실행 디버그': 'testing.debugLastRun',
    '테스트: 모든 테스트 디버그': 'testing.debugAll',
    '테스트: 모든 테스트 실행': 'testing.runAll',
    '테스트: 실패한 테스트 디버그': 'testing.debugFailTests',
    '테스트: 이전 테스트 실패로 이동': 'testing.goToPreviousMessage',
    '테스트: 인라인 적용 범위 설정/해제': 'testing.toggleInlineCoverage',
    '테스트: 인라인 테스트 출력 토글': 'testing.toggleInlineTestOutput',
    '테스트: 적용 범위로 마지막 실행 다시 실행': 'testing.coverageLastRun',
    '테스트: 적용 범위로 모든 테스트 실행': 'testing.coverageAll',
    '테스트: 출력 표시': 'testing.showMostRecentOutput',
    '테스트: 출력 피킹': 'testing.openOutputPeek',
    '테스트: 커서에서 적용 범위로 테스트 실행': 'testing.coverageAtCursor',
    '테스트: 커서에서 테스트 디버그': 'testing.debugAtCursor',
    '테스트: 커서에서 테스트 실행': 'testing.runAtCursor',
    '테스트: 테스트 새로 고침': 'testing.refreshTests',
    '테스트: 피킹에서 테스트 기록 전환': 'testing.toggleTestingPeekHistory',
    '테스트: 현재 파일에서 적용 범위로 테스트 실행': 'testing.coverageCurrentFile',
    '테스트: 현재 파일에서 테스트 디버그': 'testing.debugCurrentFile',
    '테스트: 현재 파일에서 테스트 실행': 'testing.runCurrentFile',
    '파일: 다른 이름으로 저장...': 'workbench.action.files.saveAs',
    '파일: 모양별로 모든 편집기 표시': 'workbench.action.showAllEditors',
    '파일: 열기...': 'workbench.action.files.openFileFolder',
    '파일: 저장': 'workbench.action.files.save',
    '파일: 제목 없는 새 텍스트 파일': 'workbench.action.files.newUntitledFile',
    '파일: 최근 항목 열기...': 'workbench.action.openRecent',
    '파일: 파일 열기...': 'workbench.action.files.openFile',
    '파일: 파일 탐색기에 표시': 'revealFileInOS',
    '파일: 폴더 열기...': 'workbench.action.files.openFolder',
    '파일: 형식 지정 없이 저장': 'workbench.action.files.saveWithoutFormatting',
    '파일: 활성 파일을 저장된 파일과 비교': 'workbench.files.action.compareWithSaved',
    '파일: 활성 파일을 클립보드와 비교': 'workbench.files.action.compareWithClipboard',
    '파일: 활성 파일의 경로 복사': 'copyFilePath',
    '파일: 활성 파일의 상대 경로 복사': 'copyRelativeFilePath',
    '파일로 이동...': 'workbench.action.quickOpen',
    '파일의 다음 문제로 이동 (오류, 경고, 정보)': 'editor.action.marker.nextInFiles',
    '파일의 이전 문제로 이동 (오류, 경고, 정보)': 'editor.action.marker.prevInFiles',
    '페이지 아래쪽 가리키기': 'editor.action.pageDownHover',
    '페이지 위로 가리키기': 'editor.action.pageUpHover',
    '편집기 상황에 맞는 메뉴 표시': 'editor.action.showContextMenu',
    '편집기에서 기호로 이동...': 'workbench.action.gotoSymbol',
    펼치기: 'editor.unfold',
    '포커스 및 이동 경로 선택': 'breadcrumbs.focusAndSelect',
    '피킹 구현': 'editor.action.peekImplementation',
    '호출 계층 구조 보기': 'editor.showCallHierarchy',
    '화면 읽기 프로그램 접근성 모드 설정/해제': 'editor.action.toggleScreenReaderAccessibilityMode',
    '후행 공백 자르기': 'editor.action.trimTrailingWhitespace',
    'Accept Inline Edit': 'editor.action.inlineEdit.accept',
    'C/C++: 헤더/소스 전환': 'C_Cpp.SwitchHeaderSource',
    'Calls: 호출 계층 구조 표시': 'references-view.showCallHierarchy',
    'Color Picker 숨기기': 'editor.action.hideColorPicker',
    'Comments: 다음 주석 범위로 이동': 'editor.action.nextCommentingRange',
    'Comments: 이전 주석 범위로 이동': 'editor.action.previousCommentingRange',
    'Comments: 현재 선택 영역에 메모 추가': 'workbench.action.addComment',
    'Debug: 디버깅 시작 및 항목에서 중지': 'extension.node-debug.startWithStopOnEntry',
    'Emmet: 약어 확장': 'editor.emmet.action.expandAbbreviation',
    'File: 파일 탐색기에 표시': 'remote-wsl.revealInExplorer',
    'Git: 선택한 범위 되돌리기': 'git.revertSelectedRanges',
    'Git: 선택한 범위 스테이징': 'git.stageSelectedRanges',
    'Git: 선택한 범위 스테이징 취소': 'git.unstageSelectedRanges',
    'Java: 정리 작업을 수행합니다': 'java.action.doCleanup',
    'Java: 클립보드 텍스트를 파일에 붙여넣기': 'java.action.filesExplorerPasteAction',
    'Java: 프로젝트 다시 로드': 'java.projectConfiguration.update',
    'Java: Copy Path': 'java.view.package.copyFilePath',
    'Java: Copy Relative Path': 'java.view.package.copyRelativeFilePath',
    'Java: Delete': 'java.view.package.moveFileToTrash',
    'Java: Delete Permanently': 'java.view.package.deleteFilePermanently',
    'Java: Help Center': 'java.welcome',
    'Java: Java 강제 컴파일': 'java.workspace.compile',
    'Java: Rename': 'java.view.package.renameFile',
    'Java: Reveal in Explorer': 'java.view.package.revealFileInOS',
    'Jump Back from Inline Edit': 'editor.action.inlineEdit.jumpBack',
    'Jump to Inline Edit': 'editor.action.inlineEdit.jumpTo',
    'Markdown: 미리 보기 열기': 'markdown.showPreview',
    'Markdown: 측면에서 미리 보기 열기': 'markdown.showPreviewToSide',
    'Notebook: 다음 셀 편집기에 포커스': 'notebook.focusNextEditor',
    'Notebook: 다음 셀과 조인': 'notebook.cell.joinBelow',
    'Notebook: 다중 커서 모드 종료': 'noteMultiCursor.exit',
    'Notebook: 마지막 셀에 포커스 설정': 'notebook.focusBottom',
    'Notebook: 모두 선택': 'notebook.cell.output.selectAll',
    'Notebook: 선택 영역에 찾기 일치 항목 추가': 'notebook.addFindMatchToSelection',
    'Notebook: 선택한 셀 메모': 'notebook.commentSelectedCells',
    'Notebook: 셀 분할': 'notebook.cell.split',
    'Notebook: 셀 삭제': 'notebook.cell.delete',
    'Notebook: 셀 실행': 'notebook.cell.execute',
    'Notebook: 셀 오류 작업 표시': 'notebook.cell.openFailureActions',
    'Notebook: 셀 입력 축소': 'notebook.cell.collapseCellInput',
    'Notebook: 셀 입력 확장': 'notebook.cell.expandCellInput',
    'Notebook: 셀 접기': 'notebook.fold',
    'Notebook: 셀 출력 스크롤 설정/해제': 'notebook.cell.toggleOutputScrolling',
    'Notebook: 셀 출력 지우기': 'notebook.cell.clearOutputs',
    'Notebook: 셀 출력 축소': 'notebook.cell.collapseCellOutput',
    'Notebook: 셀 출력 확장': 'notebook.cell.expandCellOutput',
    'Notebook: 셀 커서 페이지 아래로': 'notebook.cell.cursorPageDown',
    'Notebook: 셀 커서 페이지 아래로 선택': 'notebook.cell.cursorPageDownSelect',
    'Notebook: 셀 커서 페이지 위로': 'notebook.cell.cursorPageUp',
    'Notebook: 셀 커서 페이지 위로 선택': 'notebook.cell.cursorPageUpSelect',
    'Notebook: 셀 편집': 'notebook.cell.edit',
    'Notebook: 셀 편집 중지': 'notebook.cell.quitEdit',
    'Notebook: 셀 펼치기': 'notebook.unfold',
    'Notebook: 셀에 대해 감지된 언어 수락': 'notebook.cell.detectLanguage',
    'Notebook: 셀을 코드로 변경': 'notebook.cell.changeToCode',
    'Notebook: 셀을 Markdown으로 변경': 'notebook.cell.changeToMarkdown',
    'Notebook: 아래로 셀 복사': 'notebook.cell.copyDown',
    'Notebook: 아래로 셀 이동': 'notebook.cell.moveDown',
    'Notebook: 아래에 코드 셀 삽입': 'notebook.cell.insertCodeCellBelow',
    'Notebook: 오른쪽 삭제': 'noteMultiCursor.deleteRight',
    'Notebook: 왼쪽 삭제': 'noteMultiCursor.deleteLeft',
    'Notebook: 위로 셀 복사': 'notebook.cell.copyUp',
    'Notebook: 위로 셀 이동': 'notebook.cell.moveUp',
    'Notebook: 위에 셀 붙여넣기': 'notebook.cell.pasteAbove',
    'Notebook: 위에 코드 셀 삽입': 'notebook.cell.insertCodeCellAbove',
    'Notebook: 이전 셀 편집기에 포커스': 'notebook.focusPreviousEditor',
    'Notebook: 이전 셀과 조인': 'notebook.cell.joinAbove',
    'Notebook: 첫 번째 셀에 포커스 설정': 'notebook.focusTop',
    'Notebook: 활성 셀 가운데 맞춤': 'notebook.centerActiveCell',
    'Notebook: 활성 셀 출력 포커스 아웃': 'notebook.cell.focusOutOutput',
    'Notebook: 활성 셀 출력 포커스 인': 'notebook.cell.focusInOutput',
    'Notebook: Notebook 서식': 'notebook.format',
    'Notebook: Notebook 셀 실행 및 아래에 삽입': 'notebook.cell.executeAndInsertBelow',
    'Notebook: Notebook 셀 실행 및 아래에서 선택': 'notebook.cell.executeAndSelectBelow',
    'Notebook: Notebook에서 찾기': 'notebook.find',
    'PowerShell: Expand Alias': 'PowerShell.ExpandAlias',
    'PowerShell: Get Help for Command': 'PowerShell.ShowHelp',
    'PowerShell: Run Selection': 'PowerShell.RunSelection',
    'PowerShell: Show Additional Commands from PowerShell Modules': 'PowerShell.ShowAdditionalCommands',
    'Python: Python 터미널에서 선택/줄 실행': 'python.execSelectionInTerminal',
    'Python: Python REPL에서 선택/줄 실행': 'python.execInREPL',
    'Python: TensorBoard 새로 고침': 'python.refreshTensorBoard',
    'Reject Inline Edit': 'editor.action.inlineEdit.reject',
    'Snippet search': 'reactSnippets.search',
    'Test: 실패한 테스트 다시 실행': 'testing.reRunFailTests',
    'Trigger Inline Edit': 'editor.action.inlineEdit.trigger',
    "'파일 작업에 미리 보기 필요'에 대한 선택 재설정": 'files.participants.resetChoice',
    '‘launch.json’ 열기': 'workbench.action.debug.configure',
    '16진수 편집기에서 응답 본문 열기': 'extension.js-debug.network.openBodyInHex',
    '가리키기 세부 정보 표시 수준 감소': 'editor.action.decreaseHoverVerbosityLevel',
    '가리키기 세부 정보 표시 수준 늘리기': 'editor.action.increaseHoverVerbosityLevel',
    '가져오기 접기 설정/해제': 'editor.toggleImportFold',
    '개발자: 강제로 다시 토큰화': 'editor.action.forceRetokenize',
    '개발자: 대용량 스토리지 데이터베이스 항목 제거...': 'workbench.action.removeLargeStorageDatabaseEntries',
    '개발자: 디버그 편집기 GPU 렌더러': 'editor.action.debugEditorGpuRenderer',
    '개발자: 레이아웃 토글 문제 해결': 'notebook.toggleLayoutTroubleshoot',
    '개발자: 로그 수준 설정...': 'workbench.action.setLogLevel',
    '개발자: 로그 스토리지 데이터베이스 콘텐츠': 'workbench.action.logStorage',
    '개발자: 로그 채팅 입력 기록': 'workbench.action.chat.logInputHistory',
    '개발자: 바로 가기 키 문제 해결 토글': 'workbench.action.toggleKeybindingsLog',
    '개발자: 발화기 프로필 인쇄': 'perf.event.profiling',
    '개발자: 사용자 데이터 폴더 열기': 'workbench.action.openUserDataFolder',
    '개발자: 새 창에서 확장 호스트 디버깅 시작': 'workbench.extensions.action.debugExtensionHost',
    '개발자: 설정 동기화 작업 다운로드': 'workbench.userDataSync.actions.downloadSyncActivity',
    '개발자: 스크린캐스트 모드 토글': 'workbench.action.toggleScreencastMode',
    '개발자: 시작 성능': 'perfview.show',
    '개발자: 시작 페이지 연습 진행률 다시 설정': 'resetGettingStartedProgress',
    '개발자: 실행 중인 확장 표시': 'workbench.action.showRuntimeExtensions',
    '개발자: 연결: 소켓 쓰기 일시 중지': 'workbench.action.pauseSocketWriting',
    '개발자: 연결: 트리거 다시 연결': 'workbench.action.triggerReconnect',
    '개발자: 웹 보기 다시 로드': 'workbench.action.webview.reloadWebviewAction',
    '개발자: 인쇄 서비스 주기': 'perf.insta.printAsyncCycles',
    '개발자: 인쇄 서비스 추적': 'perf.insta.printTraces',
    '개발자: 작업 복사본 로깅': 'workbench.action.logWorkingCopies',
    '개발자: 작업 영역 프로필 연결 초기화': 'workbench.profiles.actions.resetWorkspaces',
    '개발자: 전자 필기장 다시 설정 시작': 'workbench.notebook.layout.gettingStarted',
    '개발자: 전자 필기장 클립보드 문제 해결 토글': 'workbench.action.toggleNotebookClipboardLog',
    '개발자: 전자 필기장 편집기 유형 캐시 지우기': 'notebook.clearNotebookEdtitorTypeCache',
    '개발자: 추적 중지': 'workbench.action.stopTracing',
    '개발자: 컨텍스트 키 검사': 'workbench.action.inspectContextKeys',
    '개발자: 키 매핑 검사': 'workbench.action.inspectKeyMappings',
    '개발자: 키 매핑 검사(JSON)': 'workbench.action.inspectKeyMappingsJSON',
    '개발자: 터미널 세션 기록': 'workbench.action.terminal.recordSession',
    '개발자: 터미널 텍스처 Atlas 표시': 'workbench.action.terminal.showTextureAtlas',
    '개발자: 터미널에 데이터 쓰기': 'workbench.action.terminal.writeDataToTerminal',
    '개발자: 편집기 토큰 및 범위 검사': 'editor.action.inspectTMScopes',
    '개발자: 프로세스 탐색기 열기': 'workbench.action.openProcessExplorer',
    '개발자: 프로필 정리': 'workbench.profiles.actions.cleanupProfiles',
    '개발자: 현재 설정에서 색 테마 생성': 'workbench.action.generateColorTheme',
    '개발자: 현재 파일을 릴리스 정보로 열기': 'developer.showCurrentFileAsReleaseNotes',
    '개발자: 확장 로그 폴더 열기': 'workbench.action.openExtensionLogsFolder',
    '개발자: 확장 호스트 다시 시작': 'workbench.action.restartExtensionHost',
    '개발자: 확장 호스트 대기 시간 측정': 'editor.action.measureExtHostLatency',
    '개발자: 확장을 사용하지 않도록 설정한 후 다시 로드': 'workbench.action.reloadWindowWithExtensionsDisabled',
    '개발자: Logs 폴더 열기': 'workbench.action.openLogsFolder',
    '개발자: Notebook 레이아웃 검사': 'notebook.inspectLayout',
    '개발자: Notebook 커널 MRU 캐시 지우기': 'notebook.clearNotebookKernelsMRUCache',
    '개발자: pty 호스트 다시 시작': 'workbench.action.terminal.restartPtyHost',
    '개발자: TextMate 구문 문법 기록 시작': 'editor.action.startDebugTextMate',
    '개발자: URL 열기': 'workbench.action.url.openUrl',
    '개발자: Webview 개발자 도구 열기': 'workbench.action.webview.openDeveloperTools',
    '검색 편집기: 검색 편집기 열기': 'search.action.openEditor',
    '검색 편집기: 새 검색 편집기': 'search.action.openNewEditor',
    '검색 편집기: 새 검색 편집기를 측면에서 열기': 'search.action.openNewEditorToSide',
    '검색 편집기: 제외할 포커스 검색 편집기 파일': 'search.action.focusFilesToExclude',
    '검색 편집기: 포함할 포커스 검색 편집기 파일': 'search.action.focusFilesToInclude',
    '검색: 검색 결과 지우기': 'search.action.clearSearchResults',
    '검색: 검색 기록 지우기': 'search.action.clearHistory',
    '검색: 검색 보기에 포커스': 'workbench.view.search.focus',
    '검색: 모두 축소': 'search.action.collapseSearchResults',
    '검색: 모두 확장': 'search.action.expandSearchResults',
    '검색: 목록으로 보기': 'search.action.viewAsList',
    '검색: 빠른 검색': 'workbench.action.quickTextSearch',
    '검색: 새로 고침': 'search.action.refreshSearchResults',
    '검색: 집중 목록': 'search.action.focusSearchList',
    '검색: 트리로 보기': 'search.action.viewAsTree',
    '경로 복사': 'references-view.copyPath',
    '공백을 사용한 들여쓰기': 'editor.action.indentUsingSpaces',
    '괄호까지 선택': 'editor.action.selectToBracket',
    '구문을 강조 표시하여 복사': 'editor.action.clipboardCopyWithSyntaxHighlightingAction',
    '구성된 패키지 관리자 가져오기': 'npm.packageManager',
    '기록에서 이전 편집기 빨리 열기': 'workbench.action.openPreviousEditorFromHistory',
    '기본 설정: 기본 바로 가기 키 열기(JSON)': 'workbench.action.openDefaultKeybindingsFile',
    '기본 설정: 기본 설정 열기(JSON)': 'workbench.action.openRawDefaultSettings',
    '기본 설정: 런타임 인수 구성': 'workbench.action.configureRuntimeArguments',
    '기본 설정: 마켓플레이스에서 색 테마 찾아보기': 'workbench.action.browseColorThemesInMarketplace',
    '기본 설정: 바로 가기 키 검색 기록 지우기': 'keybindings.editor.clearSearchHistory',
    '기본 설정: 바로 가기 키 열기(JSON)': 'workbench.action.openGlobalKeybindingsFile',
    '기본 설정: 밝은/어두운 테마 간 전환': 'workbench.action.toggleLightDarkThemes',
    '기본 설정: 사용자 설정 열기': 'workbench.action.openGlobalSettings',
    '기본 설정: 사용자 설정 열기(JSON)': 'workbench.action.openSettingsJson',
    '기본 설정: 설정 열기(UI)': 'workbench.action.openSettings2',
    '기본 설정: 애플리케이션 설정 열기(JSON)': 'workbench.action.openApplicationSettingsJson',
    '기본 설정: 언어별 설정 구성...': 'workbench.action.configureLanguageBasedSettings',
    '기본 설정: 작업 영역 설정 열기': 'workbench.action.openWorkspaceSettings',
    '기본 설정: 작업 영역 설정 열기(JSON)': 'workbench.action.openWorkspaceSettingsFile',
    '기본 설정: 접근성 설정 열기': 'workbench.action.openAccessibilitySettings',
    '기본 설정: 제품 아이콘 테마': 'workbench.action.selectProductIconTheme',
    '기본 설정: 파일 아이콘 테마': 'workbench.action.selectIconTheme',
    '기본 설정: 폴더 설정 열기': 'workbench.action.openFolderSettings',
    '기본 설정: 폴더 설정 열기(JSON)': 'workbench.action.openFolderSettingsFile',
    '기본 설정: 프로필 열기(UI)': 'workbench.profiles.actions.manageProfiles',
    '기본이 아닌 ASCII 문자 강조 표시 사용 안 함':
        'editor.action.unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters',
    '기호 강조 표시 트리거': 'editor.action.wordHighlight.trigger',
    '네트워크 로그 지우기': 'extension.js-debug.network.clear',
    '다른 이름으로 붙여넣기...': 'editor.action.pasteAs',
    '다음 접기 범위로 이동': 'editor.gotoNextFold',
    '다음 커서 포커스': 'editor.action.focusNextCursor',
    '다중 커서 한정자 설정/해제': 'workbench.action.toggleMultiCursorModifier',
    '단어 삭제': 'deleteInsideWord',
    '단어의 첫 글자를 대문자로 변환': 'editor.action.transformToTitlecase',
    '대문자로 변환': 'editor.action.transformToUppercase',
    '대상 위치로 이동': 'extension.js-debug.callers.gotToTarget',
    '대상으로 한 단계씩 코드 실행': 'editor.debug.action.stepIntoTargets',
    '도움말: 개인정보처리방침': 'workbench.action.openPrivacyStatementUrl',
    '도움말: 기능 요청 검색': 'workbench.action.openRequestFeatureUrl',
    '도움말: 대화형 편집기 플레이그라운드': 'workbench.action.showInteractivePlayground',
    '도움말: 라이센스 보기': 'workbench.action.openLicenseUrl',
    '도움말: 문서': 'workbench.action.openDocumentationUrl',
    '도움말: 문제 해결 중지': 'workbench.action.troubleshootIssue.stop',
    '도움말: 문제 해결...': 'workbench.action.troubleshootIssue.start',
    '도움말: 비디오 자습서': 'workbench.action.openVideoTutorialsUrl',
    '도움말: 시작': 'workbench.action.openWalkthrough',
    '도움말: 신호 소리 나열': 'signals.sounds.help',
    '도움말: 신호 알림 나열': 'accessibility.announcement.help',
    '도움말: 에 대한': 'workbench.action.showAboutDialog',
    '도움말: 접근성 기능 시작': 'workbench.action.getStartedWithAccessibilityFeatures',
    '도움말: 팁과 요령': 'workbench.action.openTipsAndTricksUrl',
    '도움말: 프로필': 'workbench.profiles.actions.help',
    '도움말: 확장 이등분 계속': 'extension.bisect.next',
    '도움말: 확장 이등분 시작': 'extension.bisect.start',
    '도움말: 확장 이등분 중지': 'extension.bisect.stop',
    '도움말: VS Code 뉴스레터 등록': 'workbench.action.openNewsletterSignupUrl',
    '도움말: YouTube에서 참여': 'workbench.action.openYouTubeUrl',
    '독립 실행형 Color Picker 표시 또는 포커스': 'editor.action.showOrFocusStandaloneColorPicker',
    '들여쓰기를 공백으로 변환': 'editor.action.indentationToSpaces',
    '들여쓰기를 탭으로 변환': 'editor.action.indentationToTabs',
    디버그: 'npm.debugScript',
    '디버그 : Logpoint 추가...': 'editor.debug.action.addLogPoint',
    '디버그 콘솔: 디버그 콘솔 보기에 포커스': 'workbench.panel.repl.view.focus',
    '디버그: 구성 추가...': 'debug.addConfiguration',
    '디버그: 다음 문 설정': 'debug.jumpToCursor',
    '디버그: 다음 중단점으로 이동': 'editor.debug.action.goToNextBreakpoint',
    '디버그: 디버그 세션 시작': 'workbench.action.debug.selectDebugSession',
    '디버그: 디버그 콘솔 뷰에 포커스 설정': 'workbench.debug.action.focusRepl',
    '디버그: 디버그 콘솔 선택': 'workbench.action.debug.selectDebugConsole',
    '디버그: 디버그 콘솔에서 평가': 'editor.debug.action.selectionToRepl',
    '디버그: 디버깅 선택 및 시작': 'workbench.action.debug.selectandstart',
    '디버그: 로드된 스크립트 열기': 'workbench.action.debug.showLoadedScripts',
    '디버그: 모두 콘솔 복사': 'repl.action.copyAll',
    '디버그: 스레드 종료': 'workbench.action.debug.terminateThread',
    '디버그: 연결 끊기 및 일시 중단': 'workbench.action.debug.disconnectAndSuspend',
    '디버그: 이전 중단점으로 이동': 'editor.debug.action.goToPreviousBreakpoint',
    '디버그: 조건부 중단점 추가...': 'editor.debug.action.conditionalBreakpoint',
    '디버그: 조사식에 추가': 'editor.debug.action.selectionToWatch',
    '디버그: 중단점 편집': 'editor.debug.action.editBreakpoint',
    '디버그: 커서까지 실행': 'editor.debug.action.runToCursor',
    '디버그: 트리거된 중단점 추가...': 'editor.debug.action.triggerByBreakpoint',
    '디버그: 호출 스택 아래로 이동': 'workbench.action.debug.callStackDown',
    '디버그: 호출 스택 위로 이동': 'workbench.action.debug.callStackUp',
    '디버그: 호출 스택의 맨 아래로 이동': 'workbench.action.debug.callStackBottom',
    '디버그: 호출 스택의 맨 위로 이동': 'workbench.action.debug.callStackTop',
    '디스어셈블리 보기 열기': 'debug.action.openDisassemblyView',
    '디스어셈블리 보기에서 소스 코드 토글': 'debug.action.toggleDisassemblyViewSourceCode',
    '레이아웃 사용자 지정...': 'workbench.action.customizeLayout',
    '로컬 기록: 모두 삭제': 'workbench.action.localHistory.deleteAll',
    '로컬 기록: 복원할 항목 찾기': 'workbench.action.localHistory.restoreViaPicker',
    '로컬 기록: 항목 만들기': 'workbench.action.localHistory.create',
    '리팩터링 미리 보기: 리팩터링 미리 보기 보기에 포커스': 'refactorPreview.focus',
    '링크 열기': 'editor.action.openLink',
    '마지막 선택 항목을 이전 일치 항목 찾기로 이동': 'editor.action.moveSelectionToPreviousFindMatch',
    '마지막 탐색 위치로 이동': 'workbench.action.navigateToLastNavigationLocation',
    '맨 아래에 커서 추가': 'editor.action.addCursorsToBottom',
    '맨 위에 커서 추가': 'editor.action.addCursorsToTop',
    '명령 기록 지우기': 'workbench.action.clearCommandHistory',
    '모두 복사': 'references-view.copyAll',
    '모두 수정': 'editor.action.fixAll',
    '모두 저장': 'workbench.action.files.saveAll',
    '모든 이벤트 수신기 중단점 제거': 'extension.js-debug.removeAllCustomBreakpoints',
    '모든 중단점 다시 적용': 'workbench.debug.viewlet.action.reapplyBreakpointsAction',
    '모든 중단점 설정': 'workbench.debug.viewlet.action.enableAllBreakpoints',
    '모든 중단점 제거': 'workbench.debug.viewlet.action.removeAllBreakpoints',
    '모든 중단점 해제': 'workbench.debug.viewlet.action.disableAllBreakpoints',
    '모든 Diff 축소': 'multiDiffEditor.collapseAll',
    '모든 Diff 확장': 'multiDiffEditor.expandAll',
    '모호한 문자 강조 표시 사용 안 함': 'editor.action.unicodeHighlight.disableHighlightingOfAmbiguousCharacters',
    '목록: 열 크기 조정': 'list.resizeColumn',
    '문서 서식 프로그램...': 'editor.action.formatDocument.multiple',
    '문자 바꾸기': 'editor.action.transposeLetters',
    '문제: 메시지를 여러 줄로 표시': 'problems.action.showMultilineMessage',
    '문제: 메시지를 한 줄로 표시': 'problems.action.showSinglelineMessage',
    '문제: 문제 보기에 포커스': 'workbench.panel.markers.view.focus',
    '발신자 위치로 이동': 'extension.js-debug.callers.goToCaller',
    "병합 편집기: '충돌과 함께 닫기'에 대한 선택 다시 설정": 'mergeEditor.resetCloseWithConflictsChoice',
    '병합 편집기: 결과 다시 설정': 'mergeEditor.resetResultToBaseAndAutoMerge',
    '병합 편집기: 기본 파일 열기': 'merge.openBaseEditor',
    '병합 편집기: 다음 처리되지 않은 충돌로 이동': 'merge.goToNextUnhandledConflict',
    '병합 편집기: 오른쪽에서 모든 변경 내용 적용': 'merge.acceptAllInput2',
    '병합 편집기: 왼쪽에서 모든 변경 내용 적용': 'merge.acceptAllInput1',
    '병합 편집기: 왼쪽에서 현재 충돌 전환': 'merge.toggleActiveConflictInput1',
    '병합 편집기: 이전 처리되지 않은 충돌로 이동': 'merge.goToPreviousUnhandledConflict',
    '병합 편집기: 입력 1을 베이스와 비교': 'mergeEditor.compareInput1WithBase',
    '병합 편집기: 입력 2를 베이스와 비교': 'mergeEditor.compareInput2WithBase',
    '병합 편집기: 현재 충돌을 오른쪽에서 전환': 'merge.toggleActiveConflictInput2',
    '병합 편집기(개발): 병합 편집기 상태를 폴더에 저장': 'merge.dev.saveContentsToFolder',
    '병합 편집기(개발): 병합 편집기 상태를 JSON으로 복사': 'merge.dev.copyContentsJson',
    '병합 편집기(개발): 임시 병합 편집기에서 선택 영역 열기': 'merge.dev.openSelectionInTemporaryMergeEditor',
    '병합 편집기(개발): 폴더에서 병합 편집기 상태 로드': 'merge.dev.loadContentsFromFolder',
    '병합 편집기(개발): JSON에서 병합 편집기 상태 열기': 'merge.dev.openContentsJson',
    '보기: 2개 열 아래쪽 편집기 레이아웃': 'workbench.action.editorLayoutTwoColumnsBottom',
    '보기: 2개 열 편집기 레이아웃': 'workbench.action.editorLayoutTwoColumns',
    '보기: 2개 행 오른쪽 편집기 레이아웃': 'workbench.action.editorLayoutTwoRowsRight',
    '보기: 2개 행 편집기 레이아웃': 'workbench.action.editorLayoutTwoRows',
    '보기: 3개 열 편집기 레이아웃': 'workbench.action.editorLayoutThreeColumns',
    '보기: 3개 행 편집기 레이아웃': 'workbench.action.editorLayoutThreeRows',
    '보기: 가운데 맞춤된 레이아웃 설정/해제': 'workbench.action.toggleCenteredLayout',
    '보기: 가장 오래 전에 사용한 편집기 빨리 열기': 'workbench.action.quickOpenLeastRecentlyUsedEditor',
    '보기: 가장 최근에 사용한 항목별로 모든 편집기 표시': 'workbench.action.showAllEditorsByMostRecentlyUsed',
    '보기: 가장 최근에 사용한 항목별로 활성 그룹의 편집기 표시': 'workbench.action.showEditorsInActiveGroup',
    '보기: 고정된 편집기 닫기': 'workbench.action.closeActivePinnedEditor',
    '보기: 고정된 편집기 탭 구분': 'workbench.action.toggleSeparatePinnedEditorTabs',
    '보기: 공백 렌더링 설정/해제': 'editor.action.toggleRenderWhitespace',
    '보기: 그룹 내 분할 편집기 레이아웃 전환': 'workbench.action.toggleSplitEditorInGroupLayout',
    '보기: 그룹에서 분할 편집기 설정/해제': 'workbench.action.toggleSplitEditorInGroup',
    '보기: 그룹에서 오른쪽에 있는 편집기 닫기': 'workbench.action.closeEditorsToTheRight',
    '보기: 그룹에서 왼쪽에 있는 편집기 닫기': 'workbench.action.closeEditorsToTheLeft',
    '보기: 그룹에서 최근에 사용한 다음 편집기 열기': 'workbench.action.openNextRecentlyUsedEditorInGroup',
    '보기: 그룹에서 최근에 사용한 이전 편집기 열기': 'workbench.action.openPreviousRecentlyUsedEditorInGroup',
    '보기: 그룹의 다른 편집기 닫기': 'workbench.action.closeOtherEditors',
    '보기: 그룹의 첫 번째 편집기 열기': 'workbench.action.firstEditorInGroup',
    '보기: 그리드 편집기 레이아웃(2x2)': 'workbench.action.editorLayoutTwoByTwoGrid',
    '보기: 기본 사이드 바 닫기': 'workbench.action.closeSidebar',
    '보기: 기본 사이드 바 위치 전환': 'workbench.action.toggleSidebarPosition',
    '보기: 다른 그룹의 편집기 닫기': 'workbench.action.closeEditorsInOtherGroups',
    '보기: 다음 기본 사이드 바 보기': 'workbench.action.nextSideBarView',
    '보기: 다음 패널 보기': 'workbench.action.nextPanelView',
    '보기: 다음 편집기 그룹에 포커스': 'workbench.action.focusNextGroup',
    '보기: 단일 열 편집기 레이아웃': 'workbench.action.editorLayoutSingle',
    '보기: 단일 편집기 탭 표시': 'workbench.action.showEditorTab',
    '보기: 리팩터링 미리 보기 토글': 'refactorPreview',
    '보기: 마지막 편집기 그룹에 포커스': 'workbench.action.focusLastEditorGroup',
    '보기: 메뉴 모음 설정/해제': 'workbench.action.toggleMenuBar',
    '보기: 모든 그룹에서 편집기 닫기': 'workbench.action.closeEditorInAllGroups',
    '보기: 모든 메뉴 다시 설정': 'menu.resetHiddenStates',
    '보기: 모든 편집기 그룹 조인': 'workbench.action.joinAllGroups',
    '보기: 미니맵 토글': 'editor.action.toggleMinimap',
    '보기: 보기 이동': 'workbench.action.moveView',
    '보기: 보조 사이드바 보기를 패널로 이동': 'workbench.action.moveSecondarySideBarToPanel',
    '보기: 보조 사이드바 숨기기': 'workbench.action.closeAuxiliaryBar',
    '보기: 보조 사이드바에 포커스': 'workbench.action.focusAuxiliaryBar',
    '보기: 뷰 아래로 이동': 'workbench.action.navigateDown',
    '보기: 뷰 열기': 'workbench.action.openView',
    '보기: 뷰 오른쪽으로 이동': 'workbench.action.navigateRight',
    '보기: 뷰 왼쪽으로 이동': 'workbench.action.navigateLeft',
    '보기: 뷰 위로 이동': 'workbench.action.navigateUp',
    '보기: 뷰 위치 다시 설정': 'workbench.action.resetViewLocations',
    '보기: 빈 편집기 창 새로 만들기': 'workbench.action.newEmptyEditorWindow',
    '보기: 상태 표시줄 표시 설정/해제': 'workbench.action.toggleStatusbarVisibility',
    '보기: 아래쪽의 새 편집기 그룹': 'workbench.action.newGroupBelow',
    '보기: 언어 상태 상호 작용 카운터 다시 설정': 'editor.inlayHints.Reset',
    '보기: 여러 편집기 탭 표시': 'workbench.action.showMultipleEditorTabs',
    '보기: 오른쪽으로 패널 이동': 'workbench.action.positionPanelRight',
    '보기: 오른쪽의 새 편집기 그룹': 'workbench.action.newGroupRight',
    '보기: 왼쪽으로 패널 이동': 'workbench.action.positionPanelLeft',
    '보기: 왼쪽의 새 편집기 그룹': 'workbench.action.newGroupLeft',
    '보기: 원격 탐색기 표시': 'workbench.view.remote',
    '보기: 위쪽의 새 편집기 그룹': 'workbench.action.newGroupAbove',
    '보기: 이동 경로 설정/해제': 'breadcrumbs.toggle',
    '보기: 이전 기본 사이드 바 보기': 'workbench.action.previousSideBarView',
    '보기: 이전 패널 보기': 'workbench.action.previousPanelView',
    '보기: 이전 편집기 그룹에 포커스': 'workbench.action.focusPreviousGroup',
    '보기: 작업 막대 숨기기': 'workbench.action.activityBarLocation.hide',
    '보기: 작업 막대에 포커스': 'workbench.action.focusActivityBar',
    '보기: 작업 표시줄을 맨 위로 이동': 'workbench.action.activityBarLocation.top',
    '보기: 작업 표시줄을 아래쪽으로 이동': 'workbench.action.activityBarLocation.bottom',
    '보기: 작업 표시줄을 측면으로 이동': 'workbench.action.activityBarLocation.default',
    '보기: 전자 필기장 고정 스크롤 설정/해제': 'notebook.action.toggleNotebookStickyScroll',
    '보기: 제어 문자 설정/해제': 'editor.action.toggleRenderControlCharacter',
    '보기: 참조 표시': 'workbench.view.extension.references-view',
    '보기: 채팅 표시': 'workbench.panel.chatSidebar',
    '보기: 최근에 사용한 다음 편집기 열기': 'workbench.action.openNextRecentlyUsedEditor',
    '보기: 최근에 사용한 이전 편집기 열기': 'workbench.action.openPreviousRecentlyUsedEditor',
    '보기: 최근에 사용한 편집기 빨리 열기': 'workbench.action.quickOpenPreviousRecentlyUsedEditor',
    '보기: 최대화된 패널 설정/해제': 'workbench.action.toggleMaximizedPanel',
    '보기: 테스트 표시': 'workbench.view.extension.test',
    '보기: 텍스트 편집기를 사용하여 편집기 다시 열기': 'workbench.action.reopenTextEditor',
    '보기: 패널 맞춤을 가운데로 설정': 'workbench.action.alignPanelCenter',
    '보기: 패널 맞춤을 양쪽 맞춤으로 설정': 'workbench.action.alignPanelJustify',
    '보기: 패널 맞춤을 오른쪽으로 설정': 'workbench.action.alignPanelRight',
    '보기: 패널 맞춤을 왼쪽으로 설정': 'workbench.action.alignPanelLeft',
    '보기: 패널 보기를 보조 사이드바로 이동': 'workbench.action.movePanelToSecondarySideBar',
    '보기: 패널 숨기기': 'workbench.action.closePanel',
    '보기: 패널로 포커스 이동': 'workbench.action.focusPanel',
    '보기: 패널을 맨 위로 이동': 'workbench.action.positionPanelTop',
    '보기: 패널을 아래쪽으로 이동': 'workbench.action.positionPanelBottom',
    '보기: 편집기 고정 스크롤 토글': 'editor.action.toggleStickyScroll',
    '보기: 편집기 그룹 간 탐색': 'workbench.action.navigateEditorGroups',
    '보기: 편집기 그룹 닫기': 'workbench.action.closeEditorsAndGroup',
    '보기: 편집기 그룹 잠금': 'workbench.action.lockEditorGroup',
    '보기: 편집기 그룹 잠금 토글': 'workbench.action.toggleEditorGroupLock',
    '보기: 편집기 그룹 잠금 해제': 'workbench.action.unlockEditorGroup',
    '보기: 편집기 그룹 최대화 및 사이드바 숨기기': 'workbench.action.maximizeEditorHideSidebar',
    '보기: 편집기 그룹 크기 다시 설정': 'workbench.action.evenEditorWidths',
    '보기: 편집기 그룹 크기 전환': 'workbench.action.toggleEditorWidths',
    '보기: 편집기 그룹 확장': 'workbench.action.minimizeOtherEditors',
    '보기: 편집기 그룹 확장 및 사이드바 숨기기': 'workbench.action.minimizeOtherEditorsHideSidebar',
    '보기: 편집기 그룹을 다음 그룹에 조인': 'workbench.action.joinTwoGroups',
    '보기: 편집기 그룹을 새 창으로 복사': 'workbench.action.copyEditorGroupToNewWindow',
    '보기: 편집기 그룹을 새 창으로 이동': 'workbench.action.moveEditorGroupToNewWindow',
    '보기: 편집기 그룹을 아래에 복제': 'workbench.action.duplicateActiveEditorGroupDown',
    '보기: 편집기 그룹을 오른쪽에 복제': 'workbench.action.duplicateActiveEditorGroupRight',
    '보기: 편집기 그룹을 왼쪽에 복제': 'workbench.action.duplicateActiveEditorGroupLeft',
    '보기: 편집기 그룹을 위에 복제': 'workbench.action.duplicateActiveEditorGroupUp',
    '보기: 편집기 다시 열기...': 'workbench.action.reopenWithEditor',
    '보기: 편집기 되돌리기 및 닫기': 'workbench.action.revertAndCloseActiveEditor',
    '보기: 편집기 영역 가시성 전환': 'workbench.action.toggleEditorVisibility',
    '보기: 편집기 유형 설정/해제': 'workbench.action.toggleEditorType',
    '보기: 편집기 작업 숨기기': 'workbench.action.hideEditorActions',
    '보기: 편집기 작업 표시': 'workbench.action.showEditorActions',
    '보기: 편집기 작업을 제목 표시줄로 이동': 'workbench.action.editorActionsTitleBar',
    '보기: 편집기 작업을 탭 표시줄로 이동': 'workbench.action.editorActionsDefault',
    '보기: 편집기 탭 숨기기': 'workbench.action.hideEditorTabs',
    '보기: 편집기를 다음 그룹으로 분할': 'workbench.action.splitEditorToNextGroup',
    '보기: 편집기를 마지막 그룹으로 분할': 'workbench.action.splitEditorToLastGroup',
    '보기: 편집기를 새 창으로 이동': 'workbench.action.moveEditorToNewWindow',
    '보기: 편집기를 아래 그룹으로 분할': 'workbench.action.splitEditorToBelowGroup',
    '보기: 편집기를 아래 그룹으로 이동': 'workbench.action.moveEditorToBelowGroup',
    '보기: 편집기를 오른쪽 그룹으로 분할': 'workbench.action.splitEditorToRightGroup',
    '보기: 편집기를 오른쪽 그룹으로 이동': 'workbench.action.moveEditorToRightGroup',
    '보기: 편집기를 왼쪽 그룹으로 분할': 'workbench.action.splitEditorToLeftGroup',
    '보기: 편집기를 왼쪽 그룹으로 이동': 'workbench.action.moveEditorToLeftGroup',
    '보기: 편집기를 위의 그룹으로 분할': 'workbench.action.splitEditorToAboveGroup',
    '보기: 편집기를 위의 그룹으로 이동': 'workbench.action.moveEditorToAboveGroup',
    '보기: 편집기를 이전 그룹으로 분할': 'workbench.action.splitEditorToPreviousGroup',
    '보기: 편집기를 주 창으로 복원': 'workbench.action.restoreEditorsToMainWindow',
    '보기: 편집기를 첫 번째 그룹으로 분할': 'workbench.action.splitEditorToFirstGroup',
    '보기: 포커스 문제(오류, 경고, 정보)': 'workbench.action.problems.focus',
    '보기: 포커스 배너': 'workbench.action.focusBanner',
    '보기: 포커스 상태 표시줄': 'workbench.action.focusStatusBar',
    '보기: 포커스 제목 표시줄': 'workbench.action.focusTitleBar',
    '보기: 포커스가 지정된 뷰 이동': 'workbench.action.moveFocusedView',
    '보기: 포커스된 뷰 위치 다시 설정': 'workbench.action.resetFocusedViewLocation',
    '보기: 활성 편집기 그룹에 포커스': 'workbench.action.focusActiveEditorGroup',
    '보기: 활성 편집기에서 다른 측면 포커스': 'workbench.action.focusOtherSideEditor',
    '보기: 활성 편집기에서 두 번째 측면 포커스': 'workbench.action.focusSecondSideEditor',
    '보기: 활성 편집기에서 첫 번째 측면 포커스': 'workbench.action.focusFirstSideEditor',
    '보기: Gradle 표시': 'workbench.view.extension.gradleContainerView',
    '보기: PowerShell 표시': 'workbench.view.extension.PowerShell',
    '보기: Zen 모드에서 단일 편집기 탭 표시': 'workbench.action.zenShowEditorTab',
    '보기: Zen 모드에서 여러 편집기 탭 표시': 'workbench.action.zenShowMultipleEditorTabs',
    '보기: Zen 모드에서 편집기 탭 숨기기': 'workbench.action.zenHideEditorTabs',
    '보이지 않는 문자 강조 표시 사용 안 함': 'editor.action.unicodeHighlight.disableHighlightingOfInvisibleCharacters',
    '부모 폴딩으로 이동': 'editor.gotoParentFold',
    '브라우저에서 포트 열기': 'remote.tunnel.openCommandPalette',
    '비교: 인라인 보기 토글': 'toggle.diff.renderSideBySide',
    '비교: 편집기 방향 왼쪽과 오른쪽 바꾸기': 'workbench.action.compareEditor.swapSides',
    '사용자 지정 제목 표시줄 숨기기': 'hideCustomTitleBar',
    '사용자 지정 제목 표시줄 표시': 'showCustomTitleBar',
    '새 원격': 'remote-explorer.add',
    '새 창에서 연결...': 'remote-explorer.connectToFolderInNewWindow',
    '새 창에서 Distro를 사용하여 연결...': 'remote-explorer.connectToWslUsingDistroInNewWindow',
    '새로 고침': 'npm.refresh',
    '선언 미리 보기': 'editor.action.peekDeclaration',
    '선언으로 이동': 'editor.action.revealDeclaration',
    '선택 앵커 지점으로 이동': 'editor.action.goToSelectionAnchor',
    '선택 영역에서 찾기': 'actions.findWithSelection',
    '선택한 줄 다시 들여쓰기': 'editor.action.reindentselectedlines',
    '선택한 텍스트를 오른쪽으로 이동': 'editor.action.moveCarretRightAction',
    '선택한 텍스트를 왼쪽으로 이동': 'editor.action.moveCarretLeftAction',
    '설명: 현재 줄의 메모 포커스': 'workbench.action.focusCommentOnCurrentLine',
    '설정 동기화: 로컬 백업 폴더 열기': 'workbench.userData.actions.openSyncBackupsFolder',
    '설치 실행': 'npm.runInstall',
    '소문자로 변환': 'editor.action.transformToLowercase',
    '소스 작업...': 'editor.action.sourceAction',
    '소스 제어: 소스 제어 그래프 보기에 포커스': 'workbench.scm.history.focus',
    '소스 제어: 소스 제어 리포지토리 보기에 포커스': 'workbench.scm.repositories.focus',
    '소스 제어: 소스 제어 보기에 포커스': 'workbench.scm.focus',
    '수정된 줄 포맷': 'editor.action.formatChanges',
    '스네이크 표기법으로 변환': 'editor.action.transformToSnakecase',
    '스크립트 실행': 'npm.runSelectedScript',
    '시작: 연습 열기...': 'welcome.showAllWalkthroughs',
    '신뢰할 수 있는 도메인 관리': 'workbench.action.manageTrustedDomain',
    실행: 'npm.runScript',
    '실행 및 디버그: 로드된 스크립트 보기에 포커스': 'workbench.debug.loadedScriptsView.focus',
    '실행 및 디버그: 변수 보기에 포커스': 'workbench.debug.action.focusVariablesView',
    '실행 및 디버그: 실행 보기에 포커스': 'workbench.debug.welcome.focus',
    '실행 및 디버그: 조사식 보기에 포커스': 'workbench.debug.action.focusWatchView',
    '실행 및 디버그: 중단점 보기에 포커스': 'workbench.debug.action.focusBreakpointsView',
    '실행 및 디버그: 호출 스택 보기에 포커스': 'workbench.debug.action.focusCallStackView',
    '실행 및 디버그: Cpptools: SSH 대상 보기에 포커스': 'CppSshTargetsView.focus',
    '실행 및 디버그: Event Listener Breakpoints 보기에 포커스': 'jsBrowserBreakpoints.focus',
    '실행 및 디버그: Excluded Callers 보기에 포커스': 'jsExcludedCallers.focus',
    '실행 및 디버그: Network 보기에 포커스': 'jsDebugNetworkTree.focus',
    '알림: 모든 알림 지우기': 'notifications.clearAll',
    '알림: 방해 금지 모드 전환': 'notifications.toggleDoNotDisturbMode',
    '알림: 소스별 방해 금지 모드 설정/해제...': 'notifications.toggleDoNotDisturbModeBySource',
    '알림: 포커스 알림 메시지': 'notifications.focusToasts',
    '열 선택 모드 토글': 'editor.action.toggleColumnSelection',
    열기: 'npm.openScript',
    '왼쪽 모두 삭제': 'deleteAllLeft',
    '요청 URL 복사': 'extension.js-debug.network.copyUri',
    '요청을 cURL로 보기': 'extension.js-debug.network.viewRequest',
    '우측에 있는 항목 삭제': 'deleteAllRight',
    '원격 탐색기: 원격(터널/SSH) 보기에 포커스': 'remoteTargets.focus',
    '원격 탐색기: WSL 대상 보기에 포커스': 'targetsWsl.focus',
    '원격: 원격 개발 확장 설치': 'workbench.action.remote.extensions',
    '원격: 원격 연결 닫기': 'workbench.action.remote.close',
    '원본 매핑된 단계별 실행 사용': 'extension.js-debug.enableSourceMapStepping',
    '원본 매핑된 단계별 실행 사용 안 함': 'extension.js-debug.disableSourceMapStepping',
    '위치 편집에서 앞으로 이동': 'workbench.action.navigateForwardInEditLocations',
    '위치 편집에서 이전으로 이동': 'workbench.action.navigatePreviousInEditLocations',
    '위치 편집으로 돌아가기': 'workbench.action.navigateBackInEditLocations',
    '응답 본문 열기': 'extension.js-debug.network.openBody',
    '이벤트 수신기 중단점 토글': 'extension.js-debug.addCustomBreakpoints',
    '이전 일치 항목 찾기에 선택 항목 추가': 'editor.action.addSelectionToPreviousFindMatch',
    '이전 접기 범위로 이동': 'editor.gotoPreviousFold',
    '이전 커서 포커스': 'editor.action.focusPreviousCursor',
    '이전으로 이동': 'workbench.action.navigateLast',
    '인라인 제안 트리거': 'editor.action.inlineSuggest.trigger',
    '인라인 제안의 다음 줄 수락': 'editor.action.inlineSuggest.acceptNextLine',
    '인라인 채팅: 수락 및 실행': 'notebook.inlineChat.acceptChangesAndRun',
    '인라인 채팅: 인라인 채팅 구성': 'inlineChat.configure',
    '인라인 채팅: 편집기에서 현재 줄로 시작': 'inlineChat.startWithCurrentLine',
    '인라인 힌트가 있는 줄 읽기': 'inlayHints.startReadingLineWithHint',
    '인수로 찾기': 'editor.actions.findWithArgs',
    '일치 항목으로 이동...': 'editor.action.goToMatchFindAction',
    '작업 영역: 새 창에 작업 영역으로 복제': 'workbench.action.duplicateWorkspaceInNewWindow',
    '작업 영역: 작업 영역 구성 파일 열기': 'workbench.action.openWorkspaceConfigFile',
    '작업 영역: 작업 영역 신뢰 관리': 'workbench.trust.manage',
    '작업 영역: 작업 영역 트러스트 설정 구성': 'workbench.trust.configure',
    '작업 영역: 작업 영역에 폴더 추가...': 'workbench.action.addRootFolder',
    '작업 영역: 작업 영역에서 폴더 제거...': 'workbench.action.removeRootFolder',
    '작업 영역: 작업 영역을 다른 이름으로 저장...': 'workbench.action.saveWorkspaceAs',
    '작업: 기본 빌드 작업 구성': 'workbench.action.tasks.configureDefaultBuildTask',
    '작업: 기본 테스트 작업 구성': 'workbench.action.tasks.configureDefaultTestTask',
    '작업: 마지막 작업 다시 실행': 'workbench.action.tasks.reRunTask',
    '작업: 사용자 작업 열기': 'workbench.action.tasks.openUserTasks',
    '작업: 실행 중인 작업 다시 시작': 'workbench.action.tasks.restartTask',
    '작업: 실행 중인 작업 표시': 'workbench.action.tasks.showTasks',
    '작업: 자동 작업 관리': 'workbench.action.tasks.manageAutomaticRunning',
    '작업: 작업 구성': 'workbench.action.tasks.configureTaskRunner',
    '작업: 작업 로그 표시': 'workbench.action.tasks.showLog',
    '작업: 작업 실행': 'workbench.action.tasks.runTask',
    '작업: 작업 영역 작업 열기': 'workbench.action.tasks.openWorkspaceFileTasks',
    '작업: 작업 종료': 'workbench.action.tasks.terminate',
    '작업: 테스트 작업 실행': 'workbench.action.tasks.test',
    '잘못된 이미지 첨부 파일 참조 정리': 'ipynb.cleanInvalidImageAttachment',
    '재생 요청': 'extension.js-debug.network.replayXHR',
    '전달된 포트 주소 복사': 'remote.tunnel.copyAddressCommandPalette',
    '전체 화면에서 사용자 지정 제목 표시줄 숨기기': 'hideCustomTitleBarInFullScreen',
    '정의 미리 보기 가리킨 항목 표시': 'editor.action.showDefinitionPreviewHover',
    '제안 위젯 크기 다시 설정': 'editor.action.resetSuggestSize',
    '제외 옵션 표시': 'editor.action.unicodeHighlight.showExcludeOptions',
    '제외된 모든 호출자 제거': 'extension.js-debug.callers.removeAll',
    '제외된 호출자 제거': 'extension.js-debug.callers.remove',
    '주소에 데이터 중단점 추가': 'workbench.debug.viewlet.action.addDataBreakpointOnAddress',
    '줄 다시 들여쓰기': 'editor.action.reindentlines',
    '줄 시퀀스의 끝 변경': 'workbench.action.editor.changeEOL',
    '줄 연결': 'editor.action.joinLines',
    '줄을 내림차순으로 정렬': 'editor.action.sortLinesDescending',
    '줄을 오름차순 정렬': 'editor.action.sortLinesAscending',
    '중단점 활성화 토글': 'workbench.debug.viewlet.action.toggleBreakpointsActivatedAction',
    '중복 라인 삭제': 'editor.action.removeDuplicateLines',
    '중복된 선택 영역': 'editor.action.duplicateSelection',
    '참조 미리 보기': 'editor.action.referenceSearch.trigger',
    '참조: 기록 지우기': 'references-view.clearHistory',
    '참조: 기록 표시': 'references-view.pickFromHistory',
    '참조: 모든 구현 찾기': 'references-view.findImplementations',
    '참조: 삭제': 'references-view.clear',
    '참조: 새로 고침': 'references-view.refresh',
    '참조: 참조 검색 결과 보기에 포커스': 'references-view.tree.focus',
    '참조: C/C++: 기타 참조 결과 보기에 포커스': 'CppReferencesView.focus',
    '창 전환...': 'workbench.action.switchWindow',
    '채팅: 모든 작업 영역 채팅 지우기': 'workbench.action.chat.clearHistory',
    '채팅: 모든 편집 내용 적용': 'workbench.action.chat.applyAll',
    '채팅: 빠른 음성 채팅': 'workbench.action.chat.quickVoiceChat',
    '채팅: 빠른 채팅 열기': 'workbench.action.openQuickChat',
    '채팅: 사이드바에서 채팅 열기': 'workbench.action.chat.openInSidebar',
    '채팅: 새 창에서 채팅 열기': 'workbench.action.chat.openInNewWindow',
    '채팅: 새 파일에 삽입': 'workbench.action.chat.insertIntoNewFile',
    '채팅: 세션 편집 시작': 'chatEditing.startSession',
    '채팅: 세션 편집 중지': 'chatEditing.stopSession',
    '채팅: 인라인 음성 채팅': 'workbench.action.chat.inlineVoiceChat',
    '채팅: 입력 기록 지우기': 'workbench.action.chat.clearInputHistory',
    '채팅: 채팅 가져오기...': 'workbench.action.chat.import',
    '채팅: 채팅 내보내기...': 'workbench.action.chat.export',
    '채팅: 채팅 보기의 음성 채팅': 'workbench.action.chat.voiceChatInChatView',
    '채팅: 채팅 표시...': 'workbench.action.chat.history',
    '채팅: 편집기 열기': 'workbench.action.openChat',
    '채팅: 편집기에서 채팅 열기': 'workbench.action.chat.openInEditor',
    '채팅: GitHub Copilot 보기에 포커스': 'workbench.panel.chat.view.copilot.focus',
    '최근 목록에서 제거': 'remote-explorer.deleteFolderHistoryItem',
    '출력: 출력 보기에 포커스': 'workbench.panel.output.focus',
    '충돌 병합: 다음 충돌': 'merge-conflict.next',
    '충돌 병합: 둘 다 모두 수락': 'merge-conflict.accept.all-both',
    '충돌 병합: 둘 다 수락': 'merge-conflict.accept.both',
    '충돌 병합: 모든 현재 사항 수락': 'merge-conflict.accept.all-current',
    '충돌 병합: 선택 수락': 'merge-conflict.accept.selection',
    '충돌 병합: 수신 모두 수락': 'merge-conflict.accept.all-incoming',
    '충돌 병합: 수신 수락': 'merge-conflict.accept.incoming',
    '충돌 병합: 이전 충돌': 'merge-conflict.previous',
    '충돌 병합: 현재 수락': 'merge-conflict.accept.current',
    '충돌 병합: 현재 충돌 비교': 'merge-conflict.compare',
    '커서 다시 실행': 'cursorRedo',
    '커서 주위 문자 바꾸기': 'editor.action.transpose',
    '코드 조각: 코드 조각 구성': 'workbench.action.openSnippets',
    '코드 조각: 코드 조각으로 둘러싸기...': 'editor.action.surroundWithSnippet',
    '코드 조각: 코드 조각으로 파일 채우기': 'workbench.action.populateFileFromSnippet',
    '콘솔 지우기': 'workbench.debug.panel.action.clearReplAction',
    '콘텐츠에서 들여쓰기 감지': 'editor.action.detectIndentation',
    '탐색 위치로 돌아가기': 'workbench.action.navigateBackInNavigationLocations',
    '탐색 위치에서 앞으로 이동': 'workbench.action.navigateForwardInNavigationLocations',
    '탐색 위치에서 이전으로 이동': 'workbench.action.navigatePreviousInNavigationLocations',
    '탐색기 새로 고침': 'workbench.files.action.refreshFilesExplorer',
    '탐색기: 개요 보기에 포커스': 'outline.focus',
    '탐색기: 열린 폴더 없음 보기에 포커스': 'workbench.explorer.fileView.focus',
    '탐색기: 타임라인 보기에 포커스': 'timeline.focus',
    '탐색기: Java Projects 보기에 포커스': 'javaProjectExplorer.focus',
    '탐색기: Maven 보기에 포커스': 'mavenProjects.focus',
    '탐색기: Npm 스크립트 보기에 포커스': 'npm.focus',
    '탐색기에서 폴더 축소': 'workbench.files.action.collapseExplorerFolders',
    '탭 표시 크기 변경': 'editor.action.changeTabDisplaySize',
    '탭을 사용한 들여쓰기': 'editor.action.indentUsingTabs',
    '터널 등록 취소': 'remote-explorer.unregisterTunnel',
    '터미널: 고정 스크롤 설정/해제': 'workbench.action.terminal.toggleStickyScroll',
    '터미널: 고정 차원 설정': 'workbench.action.terminal.setDimensions',
    '터미널: 글꼴 크기 늘리기': 'workbench.action.terminal.fontZoomIn',
    '터미널: 글꼴 크기 다시 초기화': 'workbench.action.terminal.fontZoomReset',
    '터미널: 글꼴 크기 작게': 'workbench.action.terminal.fontZoomOut',
    '터미널: 기본 프로필 선택': 'workbench.action.terminal.selectDefaultShell',
    '터미널: 다음 줄까지 선택': 'workbench.action.terminal.selectToNextLine',
    '터미널: 마지막 로컬 파일 링크 열기': 'workbench.action.terminal.openFileLink',
    '터미널: 마지막 명령 및 출력 복사': 'workbench.action.terminal.copyLastCommandAndLastCommandOutput',
    '터미널: 마지막 명령 복사': 'workbench.action.terminal.copyLastCommand',
    '터미널: 마지막 명령 출력 복사': 'workbench.action.terminal.copyLastCommandOutput',
    '터미널: 마지막 URL 링크 열기': 'workbench.action.terminal.openUrlLink',
    '터미널: 모두 선택': 'workbench.action.terminal.selectAll',
    '터미널: 모든 터미널 종료': 'workbench.action.terminal.killAll',
    '터미널: 사용자 지정 작업 디렉터리에서 시작하는 새 터미널 만들기': 'workbench.action.terminal.newWithCwd',
    '터미널: 새 터미널 만들기(프로필 포함)': 'workbench.action.terminal.newWithProfile',
    '터미널: 새 터미널 만들기(활성 작업 영역에서)': 'workbench.action.terminal.newInActiveWorkspace',
    '터미널: 색 변경...': 'workbench.action.terminal.changeColor',
    '터미널: 선택 항목을 HTML로 복사': 'workbench.action.terminal.copySelectionAsHtml',
    '터미널: 세션 분리': 'workbench.action.terminal.detachSession',
    '터미널: 세션에 연결': 'workbench.action.terminal.attachToSession',
    '터미널: 아이콘 변경...': 'workbench.action.terminal.changeIcon',
    '터미널: 이름 바꾸기...': 'workbench.action.terminal.rename',
    '터미널: 이전 세션 기록 지우기': 'workbench.action.terminal.clearPreviousSessionHistory',
    '터미널: 이전 줄까지 선택': 'workbench.action.terminal.selectToPreviousLine',
    '터미널: 제안 캐시 지우기': 'workbench.action.terminal.clearSuggestCache',
    '터미널: 지우기': 'workbench.action.terminal.clear',
    '터미널: 채팅 취소': 'workbench.action.terminal.chat.cancel',
    '터미널: 채팅에서 보기': 'workbench.action.terminal.chat.viewInChat',
    '터미널: 취소': 'workbench.action.terminal.chat.discard',
    '터미널: 터미널 보기에 포커스': 'terminal.focus',
    '터미널: 터미널 분할 해제': 'workbench.action.terminal.unsplit',
    '터미널: 터미널 분할(활성 작업 영역에서)': 'workbench.action.terminal.splitInActiveWorkspace',
    '터미널: 터미널 설정 구성': 'workbench.action.terminal.openSettings',
    '터미널: 터미널 아래 크기 조정': 'workbench.action.terminal.resizePaneDown',
    '터미널: 터미널 오른쪽 크기 조정': 'workbench.action.terminal.resizePaneRight',
    '터미널: 터미널 왼쪽 크기 조정': 'workbench.action.terminal.resizePaneLeft',
    '터미널: 터미널 위 크기 조정': 'workbench.action.terminal.resizePaneUp',
    '터미널: 터미널 전환': 'workbench.action.terminal.switchTerminal',
    '터미널: 터미널 조인': 'workbench.action.terminal.joinActiveTab',
    '터미널: 터미널 조인...': 'workbench.action.terminal.join',
    '터미널: 터미널을 새 창으로 이동': 'workbench.action.terminal.moveIntoNewWindow',
    '터미널: 터미널을 패널로 이동': 'workbench.action.terminal.moveToTerminalPanel',
    '터미널: 터미널을 편집기 영역으로 이동': 'workbench.action.terminal.moveToEditor',
    '터미널: 편집기 영역에서 새 터미널 만들기': 'workbench.action.createTerminalEditor',
    '터미널: 편집기 영역에서 측면에 새 터미널 만들기': 'workbench.action.createTerminalEditorSide',
    '터미널: 현재 활성 터미널의 이름 바꾸기': 'workbench.action.terminal.renameWithArg',
    '터미널: 환경 기여 표시': 'workbench.action.terminal.showEnvironmentContributions',
    '터미널: 활성 터미널 다시 시작': 'workbench.action.terminal.relaunch',
    '터미널: 활성 터미널 인스턴스 종료': 'workbench.action.terminal.kill',
    '터미널: 활성 터미널 전환': 'workbench.action.quickOpenTerm',
    '터미널: 활성 터미널에서 선택한 텍스트 실행': 'workbench.action.terminal.runSelectedText',
    '터미널: 활성 터미널에서 활성 파일 실행': 'workbench.action.terminal.runActiveFile',
    '테스트 결과: 테스트 결과 보기에 포커스': 'workbench.panel.testResults.view.focus',
    '테스트: 관련 코드 피킹': 'testing.peekRelatedCode',
    '테스트: 관련 코드로 이동': 'testing.goToRelatedCode',
    '테스트: 관련 테스트 피킹': 'testing.peekRelatedTest',
    '테스트: 관련 테스트로 이동': 'testing.goToRelatedTest',
    '테스트: 모든 결과 지우기': 'testing.clearTestResults',
    '테스트: 연속 실행 시작': 'testing.startContinuousRun',
    '테스트: 연속 실행 중지': 'testing.stopContinuousRun',
    '테스트: 적용 범위 열기': 'testing.openCoverage',
    '테스트: 적용 범위 지우기': 'testing.coverage.close',
    '테스트: 테스트 새로 고침 취소': 'testing.cancelTestRefresh',
    '테스트: 테스트 적용 범위 도구 모음': 'testing.coverageToggleToolbar',
    '테스트: 테스트 적용 범위 보기에 포커스': 'workbench.view.testCoverage.focus',
    '테스트: 테스트 탐색기 보기에 포커스': 'workbench.view.testing.focus',
    '테스트: 테스트 프로필 구성': 'testing.configureProfile',
    '테스트: 테스트별로 적용 범위 필터링': 'testing.coverageFilterToTest',
    '텍스트로 붙여넣기': 'editor.action.pasteAsText',
    '파일 인코딩 변경': 'workbench.action.editor.changeEncoding',
    '파일: 그룹으로 모두 저장': 'workbench.files.action.saveAllInGroup',
    '파일: 새 빈 작업 영역에서 활성 파일 열기': 'workbench.action.files.showOpenedFileInNewWindow',
    '파일: 새 파일...': 'explorer.newFile',
    '파일: 새 폴더...': 'explorer.newFolder',
    '파일: 세션에서 쓰기 가능한 활성 편집기 설정': 'workbench.action.files.setActiveEditorWriteableInSession',
    '파일: 세션에서 활성 편집기 읽기 전용 설정': 'workbench.action.files.setActiveEditorReadonlyInSession',
    '파일: 세션에서 활성 편집기 읽기 전용 설정/해제': 'workbench.action.files.toggleActiveEditorReadonlyInSession',
    '파일: 세션에서 활성 편집기 읽기 전용으로 다시 설정': 'workbench.action.files.resetActiveEditorReadonlyInSession',
    '파일: 자동 저장 설정/해제': 'workbench.action.toggleAutoSave',
    '파일: 제목 없는 새 텍스트 파일 비교': 'workbench.files.action.compareNewUntitledTextFiles',
    '파일: 최근 사용 항목 지우기...': 'workbench.action.clearRecentFiles',
    '파일: 탐색기 보기에서 활성 파일 표시': 'workbench.files.action.showActiveFileInExplorer',
    '파일: 파일 되돌리기': 'workbench.action.files.revert',
    '파일: 파일 모두 저장': 'workbench.action.files.saveFiles',
    '파일: 파일 탐색기에 포커스': 'workbench.files.action.focusFilesExplorer',
    '파일: 파일에서 작업 영역 열기...': 'workbench.action.openWorkspace',
    '파일: 활성 파일을 다음과 비교...': 'workbench.files.action.compareFileWith',
    '편집기 고정 스크롤에 포커스': 'editor.action.focusStickyScroll',
    '편집기 글꼴 크기 늘리기': 'editor.action.fontZoomIn',
    '편집기 글꼴 크기 다시 설정': 'editor.action.fontZoomReset',
    '편집기 글꼴 크기 줄이기': 'editor.action.fontZoomOut',
    '편집기 기록 지우기': 'workbench.action.clearEditorHistory',
    '편집기 너비 늘리기': 'workbench.action.increaseViewWidth',
    '편집기 너비 줄이기': 'workbench.action.decreaseViewWidth',
    '편집기 높이 늘리기': 'workbench.action.increaseViewHeight',
    '편집기 높이 줄이기': 'workbench.action.decreaseViewHeight',
    '포트 전달': 'remote.tunnel.forwardCommandPalette',
    '포트 전달 중지': 'remote.tunnel.closeCommandPalette',
    '포트 전달: 로그 표시': 'tunnel-forwarding.showLog',
    '포트 전달: 전달 시스템 다시 시작': 'tunnel-forwarding.restart',
    '폴더에서 NPM 스크립트 실행...': 'npm.runScriptFromFolder',
    '프로필: 기본값 프로필 열기': 'workbench.action.openProfile.기본값',
    '프로필: 새 프로필...': 'workbench.profiles.actions.createProfile',
    '프로필: 임시 프로필 만들기': 'workbench.profiles.actions.createTemporaryProfile',
    '프로필: 프로필 내보내기...': 'workbench.profiles.actions.exportProfile',
    '프로필: 프로필 삭제...': 'workbench.profiles.actions.deleteProfile',
    '프로필: 프로필 전환...': 'workbench.profiles.actions.switchProfile',
    '프로필: 프로필이 있는 새 창...': 'workbench.profiles.actions.newWindowWithProfile',
    '프로필: 현재 프로필을 다른 이름으로 저장...': 'workbench.profiles.actions.createFromCurrentProfile',
    '함수 중단점 추가': 'workbench.debug.viewlet.action.addFunctionBreakpointAction',
    해제: 'references-view.removeCallItem',
    '현재 뷰 크기 늘리기': 'workbench.action.increaseViewSize',
    '현재 뷰 크기 줄이기': 'workbench.action.decreaseViewSize',
    '현재 줄에 대한 코드 렌즈 명령 표시': 'codelens.showLensesInCurrentLine',
    '현재 창에서 연결...': 'remote-explorer.connectToFolderInCurrentWindow',
    '현재 창에서 Distro를 사용하여 연결...': 'remote-explorer.connectToWslUsingDistro',
    '형식 계층 구조 피킹': 'editor.showTypeHierarchy',
    '형식 선택...': 'editor.action.formatSelection.multiple',
    '형식 정의 미리 보기': 'editor.action.peekTypeDefinition',
    '형식 정의로 이동': 'editor.action.goToTypeDefinition',
    '확장: 허가된 확장 URI 관리...': 'workbench.extensions.action.manageAuthorizedExtensionURIs',
    'Auto Expand Lazy Variables': 'java.debug.variables.autoExpandLazyVariables',
    'C/C++: 구성 공급자 변경...': 'C_Cpp.ConfigurationProviderSelect',
    'C/C++: 구성 선택...': 'C_Cpp.ConfigurationSelect',
    'C/C++: 구성 편집(JSON)': 'C_Cpp.ConfigurationEditJSON',
    'C/C++: 구성 편집(UI)': 'C_Cpp.ConfigurationEditUI',
    'C/C++: 디버그 구성 추가': 'C_Cpp.AddDebugConfiguration',
    'C/C++: 모든 파일에 대한 코드 분석 실행': 'C_Cpp.RunCodeAnalysisOnAllFiles',
    'C/C++: 모든 Code Analysis 문제 해결': 'C_Cpp.RemoveAllCodeAnalysisProblems',
    'C/C++: 비활성 영역 색 지정 설정/해제': 'C_Cpp.ToggleDimInactiveRegions',
    'C/C++: 새 터미널에서 이 SSH 대상에 연결': 'C_Cpp.sshTerminal',
    'C/C++: 새로 고침': 'C_Cpp.refreshCppSshTargetsView',
    'C/C++: 선언/정의 만들기': 'C_Cpp.CreateDeclarationOrDefinition',
    'C/C++: 설문 조사 참여': 'C_Cpp.TakeSurvey',
    'C/C++: 열린 파일에서 코드 분석 실행': 'C_Cpp.RunCodeAnalysisOnOpenFiles',
    'C/C++: 오류 표시선 사용': 'C_Cpp.EnableErrorSquiggles',
    'C/C++: 오류 표시선 사용 안 함': 'C_Cpp.DisableErrorSquiggles',
    'C/C++: 이 SSH 대상을 활성 대상으로 설정': 'C_Cpp.setActiveSshTarget',
    'C/C++: 작업 영역 다시 검사': 'C_Cpp.RescanWorkspace',
    'C/C++: 조건부 그룹의 다음 전처리기 지시문으로 이동': 'C_Cpp.GoToNextDirectiveInGroup',
    'C/C++: 조건부 그룹의 이전 전처리기 지시문으로 이동': 'C_Cpp.GoToPrevDirectiveInGroup',
    'C/C++: 진단 정보 로그': 'C_Cpp.LogDiagnostics',
    'C/C++: 참조 형식으로 그룹화': 'C_Cpp.referencesViewGroupByType',
    'C/C++: 참조 형식으로 그룹화 해제': 'C_Cpp.referencesViewUngroupByType',
    'C/C++: 컴파일러 관련 재검사': 'C_Cpp.RescanCompilers',
    'C/C++: 포함 오류 발생 시 IntelliSense 엔진 대체 설정/해제': 'C_Cpp.ToggleIncludeFallback',
    'C/C++: 활성 파일에 대한 IntelliSense 다시 시작': 'C_Cpp.RestartIntelliSenseForFile',
    'C/C++: 활성 파일에서 코드 분석 실행': 'C_Cpp.RunCodeAnalysisOnActiveFile',
    'C/C++: 활성 SSH 대상 가져오기': 'C_Cpp.activeSshTarget',
    'C/C++: 활성 SSH 대상 선택': 'C_Cpp.selectActiveSshTarget',
    'C/C++: C/C++ 파일 디버그': 'C_Cpp.BuildAndDebugFile',
    'C/C++: C/C++ 파일 실행': 'C_Cpp.BuildAndRunFile',
    'C/C++: C++ 컴파일러 설치': 'C_Cpp.InstallCompiler',
    'C/C++: Doxygen 주석 생성': 'C_Cpp.GenerateDoxygenComment',
    'C/C++: IntelliSense 구성 선택...': 'C_Cpp.SelectIntelliSenseConfiguration',
    'C/C++: IntelliSense 데이터베이스 다시 설정': 'C_Cpp.ResetDatabase',
    'C/C++: SSH 대상 선택': 'C_Cpp.selectSshTarget',
    'C/C++: SSH 대상 제거': 'C_Cpp.removeSshTarget',
    'C/C++: SSH 대상 추가': 'C_Cpp.addSshTarget',
    'C/C++: VC 형식 설정에서 EditorConfig 콘텐츠 생성': 'C_Cpp.GenerateEditorConfig',
    'C/C++: vcpkg 도움말 페이지 방문': 'C_Cpp.VcpkgOnlineHelpSuggested',
    'C/C++: vcpkg install 명령을 클립보드에 복사': 'C_Cpp.VcpkgClipboardInstallSuggested',
    'Calls: 발신 전화 표시': 'references-view.showOutgoingCalls',
    'Calls: 수신 호출 표시': 'references-view.showIncomingCalls',
    'Camel Case로 변환': 'editor.action.transformToCamelcase',
    'Cancel Task': 'gradle.cancelBuild',
    'Cancelling Task': 'gradle.cancellingTreeItemTask',
    'Clean Workspace': 'java.project.clean.workspace',
    'Clear Profile Code Lenses': 'extension.jsProfileVisualizer.table.clearCodeLenses',
    'Clear Recent Tasks': 'gradle.clearAllRecentTasks',
    'Close All Terminals': 'gradle.closeAllTaskTerminals',
    'Close Terminal/s': 'gradle.closeTaskTerminals',
    'CMake: Online Help': 'cmake.onlineHelp',
    'Code: 릴리스 정보 표시': 'update.showCurrentReleaseNotes',
    'Code: 업데이트 다운로드': 'update.downloadUpdate',
    'Code: 업데이트 설치': 'update.installUpdate',
    'Code: 업데이트 확인...': 'update.checkForUpdate',
    'Code: 업데이트를 위해 다시 시작': 'update.restartToUpdate',
    'Comments: 모든 메모 축소': 'workbench.action.collapseAllComments',
    'Comments: 모든 메모 확장': 'workbench.action.expandAllComments',
    'Comments: 편집기 주석 달기 설정/해제': 'workbench.action.toggleCommenting',
    'Comments: 확인되지 않은 주석 확장': 'workbench.action.expandUnresolvedComments',
    'Continue All': 'java.debug.continueAll',
    'Continue Others': 'java.debug.continueOthers',
    'Copy vscode.dev Link': 'github.copyVscodeDevLink',
    'Create: 새 Jupyter Notebook': 'ipynb.newUntitledIpynb',
    Debug: 'java.debug.debugFromProjectView',
    'Debug Java': 'java.debug.debugJavaFile',
    'Debug Task': 'gradle.debugTask',
    'Debug Task With Args': 'gradle.debugTaskWithArgs',
    'Debug: 디버그를 위한 예쁜 인쇄': 'extension.js-debug.prettyPrint',
    'Debug: 링크 열기': 'extension.js-debug.debugLink',
    'Debug: 브라우저 Devtools 열기': 'extension.js-debug.openEdgeDevTools',
    'Debug: 성능 프로필 수행': 'extension.js-debug.startProfile',
    'Debug: 성능 프로필 중지': 'extension.js-debug.stopProfile',
    'Debug: 이 파일 건너뛰기 토글': 'extension.js-debug.toggleSkippingFile',
    'Debug: 자동 연결 설정/해제': 'extension.node-debug.toggleAutoAttach',
    'Debug: 중단점 문제 진단': 'extension.js-debug.createDiagnostics',
    'Debug: 진단 JS 디버그 로그 저장': 'extension.js-debug.getDiagnosticLogs',
    'Debug: 포커스 탭': 'extension.js-debug.revealPage',
    'Debug: 호출자 제외': 'extension.js-debug.callers.add',
    'Debug: JavaScript 디버그 터미널': 'extension.js-debug.createDebuggerTerminal',
    'Debug: Node 프로세스에 연결': 'extension.pwa-node-debug.attachNodeProcess',
    'Debug: npm 스크립트 디버그': 'extension.js-debug.npmScript',
    'diff 편집기: 변경되지 않은 모든 영역 축소': 'diffEditor.collapseAllUnchangedRegions',
    'diff 편집기: 변경되지 않은 모든 영역 표시': 'diffEditor.showAllUnchangedRegions',
    'diff 편집기: 스위치 쪽': 'diffEditor.switchSide',
    "Disable 'toString()' Object View": 'java.debug.variables.notShowToString',
    'Disable Logical Structure View': 'java.debug.variables.notShowLogicalStructure',
    'Emmet 명령 표시': 'workbench.action.showEmmetCommands',
    'Emmet: 0.1씩 감소': 'editor.emmet.action.decrementNumberByOneTenth',
    'Emmet: 0.1씩 증가': 'editor.emmet.action.incrementNumberByOneTenth',
    'Emmet: 10씩 감소': 'editor.emmet.action.decrementNumberByTen',
    'Emmet: 10씩 증가': 'editor.emmet.action.incrementNumberByTen',
    'Emmet: 1씩 감소': 'editor.emmet.action.decrementNumberByOne',
    'Emmet: 1씩 증가': 'editor.emmet.action.incrementNumberByOne',
    'Emmet: 균형있게(바깥쪽으로)': 'editor.emmet.action.balanceOut',
    'Emmet: 균형있게(안쪽으로)': 'editor.emmet.action.balanceIn',
    'Emmet: 다음 편집 점으로 이동': 'editor.emmet.action.nextEditPoint',
    'Emmet: 다음 항목 선택': 'editor.emmet.action.selectNextItem',
    'Emmet: 수식 평가': 'editor.emmet.action.evaluateMathExpression',
    'Emmet: 약어로 래핑': 'editor.emmet.action.wrapWithAbbreviation',
    'Emmet: 이미지 크기 업데이트': 'editor.emmet.action.updateImageSize',
    'Emmet: 이전 편집 점으로 이동': 'editor.emmet.action.prevEditPoint',
    'Emmet: 이전 항목 선택': 'editor.emmet.action.selectPrevItem',
    'Emmet: 일치하는 쌍으로 이동': 'editor.emmet.action.matchTag',
    'Emmet: 주석 토글': 'editor.emmet.action.toggleComment',
    'Emmet: 줄 병합': 'editor.emmet.action.mergeLines',
    'Emmet: 태그 분할/조인': 'editor.emmet.action.splitJoinTag',
    'Emmet: 태그 업데이트': 'editor.emmet.action.updateTag',
    'Emmet: 태그 제거': 'editor.emmet.action.removeTag',
    'Emmet: CSS 값 반영': 'editor.emmet.action.reflectCSSValue',
    "Enable 'toString()' Object View": 'java.debug.variables.showToString',
    'Enable Logical Structure View': 'java.debug.variables.showLogicalStructure',
    'ESLint: Create ESLint configuration': 'eslint.createConfig',
    'ESLint: Fix all auto-fixable Problems': 'eslint.executeAutofix',
    'ESLint: Migrate Settings': 'eslint.migrateSettings',
    'ESLint: Restart ESLint Server': 'eslint.restart',
    'ESLint: Revalidate all open files': 'eslint.revalidate',
    'ESLint: Show Output Channel': 'eslint.showOutputChannel',
    'Format Document (Forced)': 'prettier.forceFormatDocument',
    'Git API: 리포지토리 상태 가져오기': 'git.api.getRepositoryState',
    'Git API: 원격 원본 가져오기': 'git.api.getRemoteSources',
    'Git API: Git 리포지토리': 'git.api.getRepositories',
    'Git Base API: 원격 원본 가져오기': 'git-base.api.getRemoteSources',
    'Git: ...로 푸시 (강제)': 'git.pushToForce',
    'Git: .gitignore에 추가': 'git.ignore',
    'Git: 가져올 위치...': 'git.pullFrom',
    'Git: 다른 리포지토리 닫기': 'git.closeOtherRepositories',
    'Git: 다시 지정 중단': 'git.rebaseAbort',
    'Git: 다음으로 체크 아웃...': 'git.checkout',
    'Git: 다음으로 푸시...': 'git.pushTo',
    'Git: 닫힌 리포지토리 다시 열기...': 'git.reopenClosedRepositories',
    'Git: 동기화': 'git.sync',
    'Git: 동기화(다시 지정)': 'git.syncRebase',
    'Git: 리포지토리 닫기': 'git.close',
    'Git: 리포지토리 열기': 'git.openRepository',
    'Git: 리포지토리 초기화': 'git.init',
    'Git: 리포지토리를 로컬로 복제하고 데스크톱에서 열기...': 'git.continueInLocalClone',
    'Git: 마지막 커밋 실행 취소': 'git.undoCommit',
    'Git: 모두 커밋': 'git.commitAll',
    'Git: 모두 커밋 (수정)': 'git.commitAllAmend',
    'Git: 모두 커밋(로그오프됨, 확인 안 함)': 'git.commitAllSignedNoVerify',
    'Git: 모두 커밋(로그오프됨)': 'git.commitAllSigned',
    'Git: 모두 커밋(수정, 확인 안 함)': 'git.commitAllAmendNoVerify',
    'Git: 모두 커밋(확인 안 함)': 'git.commitAllNoVerify',
    'Git: 모든 변경 내용 보기': 'git.viewAllChanges',
    'Git: 모든 변경 내용 스테이징': 'git.stageAll',
    'Git: 모든 변경 내용 스테이징 취소': 'git.unstageAll',
    'Git: 모든 변경 내용 열기': 'git.openAllChanges',
    'Git: 모든 변경 내용 취소': 'git.cleanAll',
    'Git: 모든 병합 변경 내용 스테이징': 'git.stageAllMerge',
    'Git: 모든 스태시 삭제...': 'git.stashDropAll',
    'Git: 모든 원격에서 페치': 'git.fetchAll',
    'Git: 모든 diff 편집기 닫기': 'git.closeAllDiffEditors',
    'Git: 변경 내용 되돌리기': 'git.revertChange',
    'Git: 변경 내용 스테이징': 'git.stage',
    'Git: 변경 내용 스테이징 취소': 'git.unstage',
    'Git: 변경 내용 열기': 'git.openChange',
    'Git: 변경 내용 취소': 'git.clean',
    'Git: 변경 사항 보기': 'git.viewChanges',
    'Git: 병합 완료': 'git.acceptMerge',
    'Git: 병합 중단': 'git.mergeAbort',
    'Git: 병합 편집기에서 확인': 'git.openMergeEditor',
    'Git: 병합...': 'git.merge',
    'Git: 복제(재귀)': 'git.cloneRecursive',
    'Git: 부모 폴더에서 리포지토리 열기': 'git.openRepositoriesInParentFolders',
    'Git: 분기 게시...': 'git.publish',
    'Git: 분기 다시 지정...': 'git.rebase',
    'Git: 분기 삭제...': 'git.deleteBranch',
    'Git: 분기 이름 바꾸기...': 'git.renameBranch',
    'Git: 비교를 위해 선택': 'git.timeline.selectForCompare',
    'Git: 빈 내용을 커밋합니다.': 'git.commitEmpty',
    'Git: 빈 상태로 커밋(확인 안 함)': 'git.commitEmptyNoVerify',
    'Git: 상위 폴더 열기': 'git.revealFileInOS.linux',
    'Git: 새 분기 만들기...': 'git.branch',
    'Git: 새로 고침': 'git.refresh',
    'Git: 선택한 항목과 비교': 'git.timeline.compareWithSelected',
    'Git: 수정되지 않은 편집기 모두 닫기': 'git.closeAllUnmodifiedEditors',
    'Git: 스태시': 'git.stash',
    'Git: 스태시 꺼내기...': 'git.stashPop',
    'Git: 스태시 보기...': 'git.stashView',
    'Git: 스태시 삭제': 'git.stashDropEditor',
    'Git: 스태시 삭제...': 'git.stashDrop',
    'Git: 스태시 적용하기': 'git.stashApplyEditor',
    'Git: 스태시 적용하기...': 'git.stashApply',
    'Git: 스태시 표시': 'git.stashPopEditor',
    'Git: 스태시(미추적 포함)': 'git.stashIncludeUntracked',
    'Git: 스테이지 블록': 'git.diff.stageHunk',
    'Git: 스테이지 선택': 'git.diff.stageSelection',
    'Git: 스테이징된 변경 사항 보기': 'git.viewStagedChanges',
    'Git: 스테이징된 스태시': 'git.stashStaged',
    'Git: 스테이징된 항목 커밋': 'git.commitStaged',
    'Git: 스테이징된 항목 커밋(로그오프됨)': 'git.commitStagedSigned',
    'Git: 스테이징된 항목 커밋(수정)': 'git.commitStagedAmend',
    'Git: 안전하지 않은 리포지토리 관리': 'git.manageUnsafeRepositories',
    'Git: 원격 제거': 'git.removeRemote',
    'Git: 원격 추가...': 'git.addRemote',
    'Git: 원격 태그 삭제...': 'git.deleteRemoteTag',
    'Git: 이름 바꾸기': 'git.rename',
    'Git: 체크 아웃(분리됨)': 'git.checkoutRefDetached',
    'Git: 체크 아웃(분리됨)...': 'git.checkoutDetached',
    'Git: 최신 스태시 꺼내기': 'git.stashPopLatest',
    'Git: 최신 스태시 적용하기': 'git.stashApplyLatest',
    'Git: 추적되지 않은 모든 변경 내용 스테이징': 'git.stageAllUntracked',
    'Git: 추적되지 않은 모든 변경 내용 취소': 'git.cleanAllUntracked',
    'Git: 추적되지 않은 변경 내용 보기': 'git.viewUntrackedChanges',
    'Git: 추적된 모든 변경 내용 스테이징': 'git.stageAllTracked',
    'Git: 추적된 모든 변경 내용 취소': 'git.cleanAllTracked',
    'Git: 커밋': 'git.commit',
    'Git: 커밋 메시지 복사': 'git.copyCommitMessage',
    'Git: 커밋 메시지 삭제': 'git.commitMessageDiscard',
    'Git: 커밋 메시지 수락': 'git.commitMessageAccept',
    'Git: 커밋 보기': 'git.timeline.viewCommit',
    'Git: 커밋 스테이징 됨(수정, 확인 안 함)': 'git.commitStagedAmendNoVerify',
    'Git: 커밋 스테이징됨(로그오프됨, 확인 안 함)': 'git.commitStagedSignedNoVerify',
    'Git: 커밋 스테이징됨(확인 안 함)': 'git.commitStagedNoVerify',
    'Git: 커밋 템플릿 복원': 'git.restoreCommitTemplate',
    'Git: 커밋 ID 복사': 'git.copyCommitId',
    'Git: 커밋(로그오프됨, 확인 안 함)': 'git.commitSignedNoVerify',
    'Git: 커밋(로그오프됨)': 'git.commitSigned',
    'Git: 커밋(수정, 확인 안 함)': 'git.commitAmendNoVerify',
    'Git: 커밋(수정)': 'git.commitAmend',
    'Git: 커밋(확인 안 함)': 'git.commitNoVerify',
    'Git: 클론': 'git.clone',
    'Git: 타 분기에서 새 분기 만들기...': 'git.branchFrom',
    'Git: 탐색기 보기에 표시': 'git.revealInExplorer',
    'Git: 태그 만들기...': 'git.createTag',
    'Git: 태그 삭제...': 'git.deleteTag',
    'Git: 파일 열기': 'git.openFile',
    'Git: 파일 열기(HEAD)': 'git.openHEADFile',
    'Git: 파일 탐색기에 표시': 'git.revealFileInOS.windows',
    'Git: 페치': 'git.fetch',
    'Git: 페치(정리)': 'git.fetchPrune',
    'Git: 푸시': 'git.push',
    'Git: 푸시 태그': 'git.pushTags',
    'Git: 푸시(강제)': 'git.pushForce',
    'Git: 푸시(태그 팔로우, 강제 적용)': 'git.pushWithTagsForce',
    'Git: 푸시(태그 팔로우)': 'git.pushWithTags',
    'Git: 풀': 'git.pull',
    'Git: 풀(다시 지정)': 'git.pullRebase',
    'Git: Cherry Pick': 'git.cherryPickRef',
    'Git: cherry-pick...': 'git.cherryPick',
    'Git: Finder에 표시': 'git.revealFileInOS.mac',
    'Git: Git 출력 표시': 'git.showOutput',
    'Git: Git과 충돌 계산': 'git.runGitMerge',
    'Git: Git과 충돌 계산(Diff3)': 'git.runGitMergeDiff3',
    'GitHub로 로그인': 'remote-explorer.signIntoTunnelGithub',
    'Go to Dependency': 'gradle.dependency.reveal',
    'Gradle: Create a Gradle Java Project...': 'gradle.createProject',
    'Gradle: Create a Gradle Java Project... (Advanced)': 'gradle.createProjectAdvanced',
    'Gradle: Find Gradle Task': 'gradle.findTask',
    'Gradle: Gradle Daemons 보기에 포커스': 'gradleDaemonsView.focus',
    'Gradle: Gradle Projects 보기에 포커스': 'gradleDefaultProjectsView.focus',
    'Gradle: Recent Tasks 보기에 포커스': 'recentTasksView.focus',
    'Gradle: Refresh Gradle Projects View': 'gradle.refresh',
    'Gradle: Reload All Gradle Projects': 'gradle.java.projectConfiguration.update',
    'Gradle: Run a Gradle Build': 'gradle.runBuild',
    'Gradle: Run Gradle Tasks...': 'gradle.runTasks',
    'Hide Static Variables': 'java.debug.variables.notShowStaticVariables',
    'Hide Stopped Daemons': 'gradle.hideStoppedDaemons',
    'Hot Code Replace': 'java.debug.hotCodeReplace',
    'Image Preview: 복사': 'imagePreview.copyImage',
    'Image Preview: 축소': 'imagePreview.zoomOut',
    'Image Preview: 확대': 'imagePreview.zoomIn',
    'Java Language Server 오류 로그 파일 열기': 'java.open.serverStderrLog',
    'Java Language Server 출력 로그 파일 열기': 'java.open.serverStdoutLog',
    'Java: 모든 로그 파일 열기': 'java.open.logs',
    'Java: 모든 Java Source 경로를 나열': 'java.project.listSourcePaths.command',
    'Java: 빌드 작업 상태 표시': 'java.show.server.task.status',
    'Java: 상위 구현으로 이동': 'java.action.navigateToSuperImplementation',
    'Java: 이 유형을 기준으로': 'java.action.changeBaseType',
    'Java: 작업 영역으로 Java 프로젝트 가져오기': 'java.project.import.command',
    'Java: 프로젝트 다시 빌드': 'java.project.build',
    'Java: Abstract Class...': 'java.view.package.newJavaAbstractClass',
    'Java: Add Jar Libraries to Project Classpath...': 'java.project.addLibraries',
    'Java: Add Library Folders to Project Classpath...': 'java.project.addLibraryFolders',
    'Java: Annotation...': 'java.view.package.newJavaAnnotation',
    'Java: Attach Source...': 'java.project.updateSourceAttachment.command',
    'Java: Change Search Scope': 'java.change.searchScope',
    'Java: Class 계층 구조 표시': 'java.action.showClassHierarchy',
    'Java: Class...': 'java.view.package.newJavaClass',
    'Java: Clean Shared Indexes': 'java.clean.sharedIndexes',
    'Java: Configure Classpath': 'java.classpathConfiguration',
    'Java: Configure Java Runtime': 'java.runtime',
    'Java: Create Java Project...': 'java.project.create',
    'Java: Debug Tests': 'java.test.debugFromJavaProjectExplorer',
    'Java: Enum...': 'java.view.package.newJavaEnum',
    'Java: Export Jar...': 'java.view.package.exportJar',
    'Java: Extensions Guide': 'java.extGuide',
    'Java: File...': 'java.view.package.newFile',
    'Java: Flat View': 'java.view.package.changeToFlatPackageView',
    'Java: Folder...': 'java.view.package.newFolder',
    'Java: Go to Test': 'java.test.goToTest',
    'Java: Go to Test Subject': 'java.test.goToTestSubject',
    'Java: Hide Non-Java Resources': 'java.project.explorer.hideNonJavaResources',
    'Java: Hierarchical View': 'java.view.package.changeToHierarchicalPackageView',
    'Java: Install New JDK': 'java.installJdk',
    'Java: Interface...': 'java.view.package.newJavaInterface',
    'Java: Java Extension 로그 파일 열기': 'java.open.clientLog',
    'Java: Java Formatter 설정 열기': 'java.open.formatter.settings',
    'Java: Java Language Server 로그 파일 열기': 'java.open.serverLog',
    'Java: Java Language Server 작업 영역 정리': 'java.clean.workspace',
    'Java: Java Source 경로에 폴더 추가': 'java.project.addToSourcePath.command',
    'Java: Java Source 경로에서 폴더 제거': 'java.project.removeFromSourcePath.command',
    'Java: Link with Editor': 'java.view.package.linkWithFolderExplorer',
    'Java: module-info.java 생성': 'java.project.createModuleInfo.command',
    'Java: New Java File': 'java.view.menus.file.newJavaClass',
    'Java: New Java Package...': 'java.view.fileExplorer.newPackage',
    'Java: New...': 'java.view.package.new',
    'Java: Open Java Formatter Settings with Preview': 'java.formatterSettings',
    'Java: Open Project Settings': 'java.projectSettings',
    'Java: Open Text Editor': 'java.formatterSettings.showTextEditor',
    'Java: Overview': 'java.overview',
    'Java: Package...': 'java.view.package.newPackage',
    'Java: Record...': 'java.view.package.newJavaRecord',
    'Java: Refresh': 'java.project.refreshLibraries',
    'Java: Reload Java Project': 'java.project.reloadProjectFromActiveFile',
    'Java: Remove from Project Classpath': 'java.project.removeLibrary',
    'Java: Restart Java Language Server': 'java.server.restart',
    'Java: Reveal in Java Project Explorer': 'java.view.package.revealInProjectExplorer',
    'Java: Run Tests': 'java.test.editor.run',
    'Java: Show Non-Java Resources': 'java.project.explorer.showNonJavaResources',
    'Java: Show Release Notes': 'java.showReleaseNotes',
    'Java: Standard 모드로 전환': 'java.server.mode.switch',
    'Java: Subtype 계층 구조 표시': 'java.action.showSubtypeHierarchy',
    'Java: Supertype 계층 구조 표시': 'java.action.showSupertypeHierarchy',
    'Java: Tips for Beginners': 'java.gettingStarted',
    'Java: Type 계층 구조 표시': 'java.action.showTypeHierarchy',
    'Java: Unlink with Editor': 'java.view.package.unlinkWithFolderExplorer',
    'JavaScript: 가져오기 정렬': 'javascript.sortImports',
    'JavaScript: 사용하지 않는 가져오기 제거': 'javascript.removeUnusedImports',
    'JavaScript: 프로젝트 구성(jsconfig/tsconfig)으로 이동합니다.': 'javascript.goToProjectConfig',
    'JavaScript: 프로젝트 다시 로드': 'javascript.reloadProjects',
    'JSON: 문서 정렬': 'json.sort',
    'JSON: 스키마 캐시 지우기': 'json.clearCache',
    'Kebab 사례로 변환': 'editor.action.transformToKebabcase',
    'Learn more about import resolution': 'pylance.learnMoreAboutImportResolution',
    'Manual Expand Lazy Variables': 'java.debug.variables.manualExpandLazyVariables',
    'Markdown: 미리 보기 보안 설정 변경': 'markdown.showPreviewSecuritySelector',
    'Markdown: 미리 보기 새로 고침': 'markdown.preview.refresh',
    'Markdown: 미리 보기 잠금 설정/해제': 'markdown.preview.toggleLock',
    'Markdown: 소스 표시': 'markdown.showSource',
    'Markdown: 작업 영역에 파일 링크 삽입': 'markdown.editor.insertLinkFromWorkspace',
    'Markdown: 작업 영역에서 이미지 삽입': 'markdown.editor.insertImageFromWorkspace',
    'Markdown: 측면에서 잠긴 미리 보기 열기': 'markdown.showLockedPreviewToSide',
    'Markdown: 파일 참조 찾기': 'markdown.findAllFileReferences',
    'Maven: Add a dependency...': 'maven.project.addDependency',
    'Maven: Add a favorite...': 'maven.project.addFavorite',
    'Maven: clean': 'maven.goal.clean',
    'Maven: compile': 'maven.goal.compile',
    'Maven: Custom... ': 'maven.goal.custom',
    'Maven: Debug': 'maven.plugin.debug',
    'Maven: deploy': 'maven.goal.deploy',
    'Maven: Deselect': 'maven.profile.deselect',
    'Maven: Exclude Dependency': 'maven.project.excludeDependency',
    'Maven: Execute Commands...': 'maven.goal.execute',
    'Maven: Favorites...': 'maven.favorites',
    'Maven: Go to Definition': 'maven.project.goToDefinition',
    'Maven: Go to Effective Dependency': 'maven.dependency.goToEffective',
    'Maven: History...': 'maven.history',
    'Maven: install': 'maven.goal.install',
    'Maven: New Module...': 'maven.new.module',
    'Maven: New Project...': 'maven.archetype.generate',
    'Maven: Open POM file': 'maven.project.openPom',
    'Maven: package': 'maven.goal.package',
    'Maven: Refresh': 'maven.explorer.refresh',
    'Maven: Reload All Maven Projects': 'maven.java.projectConfiguration.update',
    'Maven: Resolve Conflict...': 'maven.project.setDependencyVersion',
    'Maven: Run': 'maven.goal.execute.fromFavoritesMenu',
    'Maven: Run Maven Commands...': 'maven.goal.execute.fromProjectManager',
    'Maven: Select': 'maven.profile.select',
    'Maven: Show Dependencies': 'maven.project.showDependencies',
    'Maven: Show Effective POM': 'maven.project.effectivePom',
    'Maven: site': 'maven.goal.site',
    'Maven: Switch to flat view': 'maven.view.flat',
    'Maven: Switch to hierarchical view': 'maven.view.hierarchical',
    'Maven: test': 'maven.goal.test',
    'Maven: test-compile': 'maven.goal.test-compile',
    'Maven: Update Maven Archetype Catalog': 'maven.archetype.update',
    'Maven: validate': 'maven.goal.validate',
    'Maven: verify': 'maven.goal.verify',
    'Microsoft에 로그인': 'remote-explorer.signIntoTunnelMicrosoft',
    'Notebook 편집기에서 IPYNB 파일 열기': 'ipynb.openIpynbInNotebookEditor',
    'Notebook: 가장 최근에 실패한 셀로 이동': 'notebook.revealLastFailedCell',
    'Notebook: 노트북 레이아웃 사용자 지정': 'workbench.notebook.layout.configure',
    'Notebook: 노트북 레이아웃 중에서 선택': 'workbench.notebook.layout.select',
    'Notebook: 들여쓰기 선택': 'notebook.selectIndentation',
    'Notebook: 모두 실행': 'notebook.execute',
    'Notebook: 모든 셀 입력 축소': 'notebook.cell.collapseAllCellInputs',
    'Notebook: 모든 셀 입력 확장': 'notebook.cell.expandAllCellInputs',
    'Notebook: 모든 셀 출력 축소': 'notebook.cell.collapseAllCellOutputs',
    'Notebook: 모든 셀 출력 확장': 'notebook.cell.expandAllCellOutputs',
    'Notebook: 모든 Markdown 셀 렌더링': 'notebook.renderAllMarkdownCells',
    'Notebook: 선택한 셀 조인': 'notebook.cell.joinSelected',
    'Notebook: 셀 및 포커스 컨테이너 실행': 'notebook.cell.executeAndFocusContainer',
    'Notebook: 셀 복사': 'notebook.cell.copy',
    'Notebook: 셀 붙여넣기': 'notebook.cell.paste',
    'Notebook: 셀 실행 및 아래': 'notebook.cell.executeCellAndBelow',
    'Notebook: 셀 실행 중지': 'notebook.cell.cancelExecution',
    'Notebook: 셀 언어 변경': 'notebook.cell.changeLanguage',
    'Notebook: 셀 잘라내기': 'notebook.cell.cut',
    'Notebook: 셀 줄 번호 표시': 'notebook.cell.toggleLineNumbers',
    'Notebook: 셀 출력 복사': 'notebook.cellOutput.copy',
    'Notebook: 실행 중인 셀로 이동': 'notebook.revealRunningCell',
    'Notebook: 실행 중지': 'notebook.cancelExecution',
    'Notebook: 아래에 Markdown 셀 삽입': 'notebook.cell.insertMarkdownCellBelow',
    'Notebook: 아래의 코드 셀 및 포커스 컨테이너 삽입': 'notebook.cell.insertCodeCellBelowAndFocusContainer',
    'Notebook: 위에 Markdown 셀 삽입': 'notebook.cell.insertMarkdownCellAbove',
    'Notebook: 위의 셀 실행': 'notebook.cell.executeCellsAbove',
    'Notebook: 위의 코드 셀 및 포커스 컨테이너 삽입': 'notebook.cell.insertCodeCellAboveAndFocusContainer',
    'Notebook: 전자 필기장 줄 번호 설정/해제': 'notebook.toggleLineNumbers',
    'Notebook: 중단': 'notebook.interruptExecution',
    'Notebook: 출력 모두 지우기': 'notebook.clearAllCellsOutputs',
    'Notebook: 텍스트 편집기에서 셀 출력 열기': 'notebook.cellOutput.openInTextEditor',
    'Notebook: 토글 출력': 'notebook.cell.toggleOutputs',
    'Notebook: Mimetype 표시 순서 저장': 'notebook.saveMimeTypeOrder',
    'Open Build File': 'gradle.openBuildFile',
    'Open in vscode.dev': 'github.openOnVscodeDev',
    'Open Settings': 'gradle.openSettings',
    'Pascal Case 변환': 'editor.action.transformToPascalcase',
    'Pause All': 'java.debug.pauseAll',
    'Pause Others': 'java.debug.pauseOthers',
    'Pin Task': 'gradle.pinTask',
    'Pin Task With Args': 'gradle.pinTaskWithArgs',
    'PowerShell: Close panel': 'PowerShell.ClosePanel',
    'PowerShell: Command Explorer 보기에 포커스': 'PowerShellCommands.focus',
    'PowerShell: Debug Pester tests': 'PowerShell.DebugPesterTestsFromFile',
    'PowerShell: Disable ISE Mode (restore to defaults)': 'PowerShell.DisableISEMode',
    'PowerShell: Enable ISE Mode': 'PowerShell.EnableISEMode',
    'PowerShell: Find/Install PowerShell Modules from the Gallery': 'PowerShell.PowerShellFindModule',
    'PowerShell: Insert Command': 'PowerShell.InsertCommand',
    'PowerShell: Invoke Registered Editor Command': 'PowerShell.InvokeRegisteredEditorCommand',
    'PowerShell: Move panel left': 'PowerShell.PositionPanelLeft',
    'PowerShell: Move panel to bottom': 'PowerShell.PositionPanelBottom',
    'PowerShell: Open Current File in PowerShell ISE': 'PowerShell.OpenInISE',
    'PowerShell: Open Examples Folder': 'PowerShell.OpenExamplesFolder',
    'PowerShell: Open PowerShell Extension Logs Folder': 'PowerShell.OpenLogFolder',
    'PowerShell: Refresh Command Explorer': 'PowerShell.RefreshCommandsExplorer',
    'PowerShell: Restart Session': 'PowerShell.RestartSession',
    'PowerShell: Run': 'PowerShell.Debug.Start',
    'PowerShell: Run Pester tests': 'PowerShell.RunPesterTestsFromFile',
    'PowerShell: Show Extension Terminal': 'PowerShell.ShowSessionConsole',
    'PowerShell: Show PowerShell Extension Logs': 'PowerShell.ShowLogs',
    'PowerShell: Show Session Menu': 'PowerShell.ShowSessionMenu',
    'PowerShell: Toggle ISE Mode': 'PowerShell.ToggleISEMode',
    'PowerShell: Upload Bug Report to GitHub': 'PowerShell.GenerateBugReport',
    'Prettier: Create Configuration File': 'prettier.createConfigFile',
    'Publish to GitHub': 'github.publish',
    'Pylance debugging: Dump parse tree ...': 'pylance.dumpNodes',
    'Pylance debugging: Dump token streams ...': 'pylance.dumpTokens',
    'Pylance debugging: Dump type info ...': 'pylance.dumpTypes',
    'Pylance debugging: Pylance: Dump cached type info ...': 'pylance.dumpCachedTypes',
    'Pylance debugging: Pylance: Dump code flow graph for node ...': 'pylance.dumpCodeFlowGraph',
    'Pylance: 로깅 시작': 'pylance.logging.start',
    'Pylance: 로깅 중지': 'pylance.logging.stop',
    'Pylance: 문제 보고...': 'pylance.reportIssue',
    'Pylance: 지속형 인덱스 모두 지우기': 'pylance.indexing.clearPersistedIndices',
    'Pylance: 출력 채널로 이동': 'pylance.gotoOutputChannel',
    'Pylance: 프로파일링 시작': 'pylance.profiling.start',
    'Pylance: 프로파일링 중지': 'pylance.profiling.stop',
    'Python Debugger: %debugpy.command.clearCacheAndReload.title%': 'debugpy.clearCacheAndReload',
    'Python Debugger: %debugpy.command.debugInTerminal.title%': 'debugpy.debugInTerminal',
    'Python Debugger: %debugpy.command.debugUsingLaunchConfig.title%': 'debugpy.debugUsingLaunchConfig',
    'Python Debugger: %debugpy.command.reportIssue.title%': 'debugpy.reportIssue',
    'Python Debugger: %debugpy.command.viewOutput.title%': 'debugpy.viewOutput',
    'Python: 네이티브 Python REPL 시작': 'python.startNativeREPL',
    'Python: 문제 보고...': 'python.reportIssue',
    'Python: 새 Python 파일': 'python.createNewFile',
    'Python: 언어 서버 다시 시작': 'python.analysis.restartLanguageServer',
    'Python: 언어 서버 출력 표시': 'python.viewLanguageServerOutput',
    'Python: 인터프리터 선택': 'python.setInterpreter',
    'Python: 작업 영역 인터프리터 설정 지우기': 'python.clearWorkspaceInterpreter',
    'Python: 전용 터미널에서 Python 파일 실행': 'python.execInDedicatedTerminal',
    'Python: 출력 표시': 'python.viewOutput',
    'Python: 캐시 지우기 및 창 다시 로드': 'python.clearCacheAndReload',
    'Python: 터미널 만들기': 'python.createTerminal',
    'Python: 터미널 REPL 시작': 'python.startREPL',
    'Python: 터미널에서 Python 파일 실행': 'python.execInTerminal',
    'Python: 테스트 구성': 'python.configureTests',
    'Python: 확장 디버깅에 소스 맵 지원 사용': 'python.enableSourceMapSupport',
    'Python: 환경 만들기…': 'python.createEnvironment',
    'Python: Django Shell에서 선택/줄 실행': 'python.execSelectionInDjangoShell',
    'Python: Jupyter 확장 설치': 'python.installJupyter',
    'Python: Python 파일 실행': 'python.execInTerminal-icon',
    'Python: Tensorboard 시작': 'python.launchTensorBoard',
    'Quick Open에서 다음 선택': 'workbench.action.quickOpenSelectNext',
    'Quick Open에서 다음 탐색': 'workbench.action.quickOpenNavigateNext',
    'Quick Open에서 이전 선택': 'workbench.action.quickOpenSelectPrevious',
    'Quick Open에서 이전 탐색': 'workbench.action.quickOpenNavigatePrevious',
    'React: class to className': 'extension.stayClassy',
    'Rebuild All': 'java.project.build.workspace',
    'Rebuild Project': 'java.project.rebuild',
    'Refresh Daemon Status': 'gradle.refreshDaemonStatus',
    'Reload Project': 'java.project.update',
    'Remote-SSH: 도움말': 'opensshremotes.getHelp',
    'Remote-SSH: 로그 표시': 'opensshremotes.showLog',
    'Remote-SSH: 문제 보고...': 'opensshremotes.reportIssue',
    'Remote-SSH: 새 SSH 호스트 추가...': 'opensshremotes.addNewSshHost',
    'Remote-SSH: 설정': 'opensshremotes.settings',
    'Remote-SSH: 웹 UI 열기': 'opensshremotes.openWebUI',
    'Remote-SSH: 피드백 제공': 'opensshremotes.provideFeedback',
    'Remote-SSH: 현재 VS Code 서버 중지': 'opensshremotes.cleanCurrentRemoteServer',
    'Remote-SSH: 호스트에 대한 로컬 연결 서버 종료...': 'opensshremotes.cleanLocalServer',
    'Remote-SSH: 호스트에 연결...': 'opensshremotes.openEmptyWindow',
    'Remote-SSH: 호스트에 현재 창 연결...': 'opensshremotes.openEmptyWindowInCurrentWindow',
    'Remote-SSH: 호스트에서 VS Code 서버 제거...': 'opensshremotes.cleanDevBox',
    'Remote-SSH: 호스트의 VS Code 서버 종료...': 'opensshremotes.cleanRemoteServer',
    'Remote-SSH: 활성 호스트의 새 창': 'opensshremotes.openEmptyWindowOnCurrentHost',
    'Remote-SSH: SSH 구성 파일 열기...': 'opensshremotes.openConfigFile',
    'Remote-SSH: SSH 시작하기': 'opensshremotes.getStarted',
    'Remove Recent Task': 'gradle.removeRecentTask',
    'Restart Task': 'gradle.restartTask',
    Run: 'java.debug.runFromProjectView',
    'Run Java': 'java.debug.runJavaFile',
    'Run Task': 'gradle.runTask',
    'Run Task With Args': 'gradle.runTaskWithArgs',
    'Show as Dec': 'java.debug.variables.notShowHex',
    'Show as Hex': 'java.debug.variables.showHex',
    'Show Flat Tasks': 'gradle.explorerFlat',
    'Show Gradle process information message box': 'gradle.showProcessMessage',
    'Show Gradle Tasks': 'gradle.showTasks',
    'Show Hierarchical Tasks': 'gradle.explorerTree',
    'Show logs': 'gradle.showLogs',
    'Show Qualified Names': 'java.debug.variables.showQualifiedNames',
    'Show Simple Names': 'java.debug.variables.notShowQualifiedNames',
    'Show Static Variables': 'java.debug.variables.showStaticVariables',
    'Show Stopped Daemons': 'gradle.showStoppedDaemons',
    'Show Terminal': 'gradle.showTaskTerminal',
    'Simple Browser: Show': 'simpleBrowser.show',
    'SSH 구성 파일 열기': 'remote-explorer.configureSsh',
    'Stop Daemon': 'gradle.stopDaemon',
    'Stop Daemons': 'gradle.stopDaemons',
    'Types: 상위 형식 표시': 'references-view.showSupertypes',
    'Types: 하위 형식 표시': 'references-view.showSubtypes',
    'Types: 형식 계층 구조 표시': 'references-view.showTypeHierarchy',
    'TypeScript: 가져오기 정렬': 'typescript.sortImports',
    'TypeScript: 사용하지 않는 가져오기 제거': 'typescript.removeUnusedImports',
    'TypeScript: 원본 정의로 이동': 'typescript.goToSourceDefinition',
    'TypeScript: 파일 참조 찾기': 'typescript.findAllFileReferences',
    'TypeScript: 프로젝트 구성(tsconfig)으로 이동': 'typescript.goToProjectConfig',
    'TypeScript: 프로젝트 다시 로드': 'typescript.reloadProjects',
    'TypeScript: TS 서버 다시 시작': 'typescript.restartTsServer',
    'TypeScript: TS 서버 로그 열기': 'typescript.openTsServerLog',
    'TypeScript: TypeScript 버전 선택...': 'typescript.selectTypeScriptVersion',
    'Unpin all Tasks': 'gradle.unpinAllTasks',
    'Unpin Task': 'gradle.unpinTask',
    'View: 트리 고정 스크롤 설정/해제': 'tree.toggleStickyScroll',
    'Visual Studio Code 다운로드': 'workbench.action.download',
    'WSL: 기본 배포판으로 설정': 'remote-wsl.explorer.setDefaultDistro',
    'WSL: 도움말': 'remote-wsl.getHelp',
    'WSL: 로그 표시': 'remote-wsl.showLog',
    'WSL: 문제 보고...': 'remote-wsl.reportIssue',
    'WSL: 배포판 삭제': 'remote-wsl.explorer.deleteDistro',
    'WSL: 배포판 추가': 'remote-wsl.explorer.addDistro',
    'WSL: 배포판을 사용하여 WSL에 연결...': 'remote-wsl.connectUsingDistro',
    'WSL: 새 창에서 연결': 'remote-wsl.explorer.connectInNewWindow',
    'WSL: 새 창에서 Distro를 사용하여 WSL에 연결...': 'remote-wsl.connectUsingDistroInNewWindow',
    'WSL: 새 창에서 WSL에 연결': 'remote-wsl.connectInNewWindow',
    'WSL: 새로 고침': 'remote-wsl.explorer.refresh',
    'WSL: 최근 폴더 제거': 'remote-wsl.explorer.removeFolder',
    'WSL: 피드백 제공': 'remote-wsl.provideFeedback',
    'WSL: 현재 창에서 연결': 'remote-wsl.explorer.connectInCurrentWindow',
    'WSL: Windows에서 폴더 다시 열기': 'remote-wsl.reopenInWindows',
    'WSL: WSL 시작하기': 'remote-wsl.getStarted',
    'WSL: WSL에 연결': 'remote-wsl.connect',
    'WSL: WSL에서 폴더 다시 열기': 'remote-wsl.reopenInWSL',
    'WSL: WSL에서 폴더 열기': 'remote-wsl.reopenFromRecommendation',
    'WSL: WSL에서 폴더 열기...': 'remote-wsl.openFolder',
    'XHR/fetch 중단점 제거': 'extension.js-debug.removeXHRBreakpoint',
    'XHR/fetch 중단점 추가': 'extension.js-debug.addXHRBreakpoints',
    'XHR/fetch 중단점 편집': 'extension.js-debug.editXHRBreakpoints',
};
